Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2019-11, with the labels that each got.

#465 #450 fix
  A3-Antistasi/Templates/Vanilla_Occ_AAF_Altis.sqf
Labels: Bug-fix

#464 Removed duplicated Class preventing Tanoa load.
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: Bug-fix

#452 Creation of Logging Function
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Utility/fn_log.sqf
  A3-Antistasi/initServer.sqf
  A3-Antistasi/initVar.sqf
  A3-Antistasi/log.sqf
Labels: enhancement

#466 Fixes warning about author class error when LAN hosting
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi.Malden/mission.sqm
Labels: Bug-fix

#470 Fixes a bad variable in arsenalManage.sqf and public declares a missi…
  A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf
  A3-Antistasi/functions/CREATE/fn_FIAinitBASES.sqf
  A3-Antistasi/functions/REINF/fn_FIAinit.sqf
  A3-Antistasi/initVar.sqf
Labels: Bug-fix

#472 Convoy fix
  A3-Antistasi/functions/Garrison/fn_updatePreference.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
Labels: Bug-fix

#475 Added instruction for the new packing tool
  README.md
Labels: change

#474 Description.EXT and mission.SQM cleanup and unify
  A3-Antistasi/MissionDescription/gameSettings.hpp
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/init.sqf
  Map-Templates/Antistasi-ArmiaKrajowa.chernarus_summer/description.ext
  Map-Templates/Antistasi-ArmiaKrajowa.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-BLUFOR.Altis/description.ext
  Map-Templates/Antistasi-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/description.ext
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/description.ext
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
  Map-Templates/Antistasi.Altis/description.ext
  Map-Templates/Antistasi.Altis/mission.sqm
  Map-Templates/Antistasi.Kunduz/description.ext
  Map-Templates/Antistasi.Kunduz/mission.sqm
  Map-Templates/Antistasi.Malden/description.ext
  Map-Templates/Antistasi.Malden/mission.sqm
  Map-Templates/Antistasi.Tembelan/description.ext
  Map-Templates/Antistasi.Tembelan/mission.sqm
Labels: Bug-fix, localisation, low priority

#488 Set Weighted changes to the ammo crates for weapons
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
  A3-Antistasi/functions/Ammunition/fn_crateLootParams.sqf
Labels: enhancement

#496 Added changelog updates
  A3-Antistasi/changelog_2_2.txt
Labels: enhancement

#501 191115 fixes
  A3-Antistasi/functions/CREATE/fn_freeSpawnPositions.sqf
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
Labels: Bug-fix

#502 Spawn marker fix
  A3-Antistasi/functions/CREATE/fn_AAFroadPatrol.sqf
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/init/fn_prepareMarkerArrays.sqf
Labels: Bug-fix

#507 Give AT guys and squad leaders a rifle
  A3-Antistasi/functions/REINF/fn_FIAinit.sqf
Labels: Bug-fix

#508 matched CSAT loot crate script with NATO
  A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf
Labels: Bug-fix

#513 Add debug logging for Boss assignment
  A3-Antistasi/functions/OrgPlayers/fn_assigntheBoss.sqf
  A3-Antistasi/functions/OrgPlayers/fn_theBossInit.sqf
  A3-Antistasi/initPlayerLocal.sqf
Labels: bug, info needed

#530 Marker change logging
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_mrkWIN.sqf
  A3-Antistasi/functions/Utility/fn_log.sqf
Labels: Priority

#562 Fixes an issue with cargoGroup not set
  A3-Antistasi/functions/Convoy/fn_onSpawnedArrival.sqf
Labels: Bug-fix

#565 Kunduz map overhaul
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
Labels: Bug-fix

#564 Malden - Island marker overhaul
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
Labels: Bug-fix

#563 Translate _puentes into _bridges
  A3-Antistasi/functions/AI/fn_inmuneConvoy.sqf
Labels: change

#571 Fixed breaching script
  A3-Antistasi/initVar.sqf
Labels: Bug-fix

#572 ESSENTIAL Tembelan overhaul
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
Labels: Priority

#544 Added more logs to find the quad bug, also improved code a bit
  A3-Antistasi/functions/Garrison/fn_createGarrisonLine.sqf
  A3-Antistasi/functions/Garrison/fn_logArray.sqf
  A3-Antistasi/functions/Garrison/fn_selectReinfUnits.sqf
  A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf
Labels: bug

#566 Rhs launcher change
  A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
Labels: change

#567 Cdf traitors
  A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
Labels: change

#577 Anizay Map Port
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/initPlayerLocal.sqf
  A3-Antistasi/initVar.sqf
  Map-Templates/Antistasi-Anizay.tem_anizay/PIC.jpg
  Map-Templates/Antistasi-Anizay.tem_anizay/description.ext
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
Labels: Map Issue, enhancement

#578 Fix CGRCAT vehicle typo in USAF templates
  A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
Labels: Bug-fix, Priority
