Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2019-12, with the labels that each got.

#579 Fix spamming of vehicles in convoys
  A3-Antistasi/functions/Garrison/fn_selectReinfUnits.sqf
Labels: Bug-fix, Priority

#586 removes missing forms of priest outfit I missed
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
Labels: Bug-fix

#597 Tembelan carrier position update
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
Labels: Merge pending, change

#592 Upgrade AltisB start LR
  A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
Labels: change

#610 Petros gear init
  A3-Antistasi/functions/Ammunition/fn_unlockEquipment.sqf
  A3-Antistasi/functions/Base/fn_createPetros.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
Labels: Bug-fix, Merge pending, Priority

#606 Fix error cases in crate generation, change from call to spawn
  A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf
  A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/CREATE/fn_createAISite.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Ammo.sqf
Labels: Bug-fix, Change Requested, enhancement

#617 Enable vanilla revive with Medikits
  A3-Antistasi/functions/Revive/fn_actionRevive.sqf
Labels: Bug-fix, change
