Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2019-09, with the labels that each got.

#214 fix invalid _baseSide variable check in undercover.sqf
  A3-Antistasi/undercover.sqf
Labels: enhancement

#224 Fix Barbolani's momentary lapse of sanity (swoopShutUp)
  A3-Antistasi/CREATE/createAIOutposts.sqf
  A3-Antistasi/initVar.sqf
Labels: change

#213 fix invalid initializeGroup parameter function bis_dyna…
  A3-Antistasi/initPlayerLocal.sqf
Labels: enhancement

#237 Russian language for multilaguage system
  A3-Antistasi/Stringtable.xml
Labels: localisation

#231 Add debugging for init Garrisons / Zones and Remove dedicated startup wait
  A3-Antistasi/initGarrisons.sqf
  A3-Antistasi/initServer.sqf
  A3-Antistasi/initZones.sqf
Labels: Logging Enhancement, enhancement

#234 FIX _leader error
  A3-Antistasi/Templates/A3-AA-BLUFORTemplate.Altis/mission.sqm
  A3-Antistasi/Templates/A3-AATemplate.Altis/mission.sqm
  A3-Antistasi/Templates/A3-Livonia-Template.Enoch/mission.sqm
  A3-Antistasi/Templates/A3-Malden-Template.Malden/mission.sqm
  A3-Antistasi/Templates/A3-WotPTemplate.Tanoa/mission.sqm
Labels: Needs Testing, Needs review, change

#243 Fixes russian translate
  A3-Antistasi/Stringtable.xml
Labels: Change Requested, change, localisation

#252 Re-Add GPS
  A3-Antistasi/initVar.sqf
Labels: change

#266 initVar RHS Altis Blufor Fix
  A3-Antistasi/initVar.sqf
Labels: Bug-fix

#338 Template naming convention
  A3-Antistasi/Templates/3CB_Inv_TKM_Arid.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Temp.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Trop.sqf
  A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
  A3-Antistasi/Templates/3CB_Occ_UKN-G_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_UKN-G_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_CCM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_CCM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CCM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_UN_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_UN_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_UN_Trop.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Temp.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Trop.sqf
  A3-Antistasi/Templates/FFAA_Occ_FFAA_Arid.sqf
  A3-Antistasi/Templates/FFAA_Occ_FFAA_Temp.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Arct.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Arid.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Temp.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Arct.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Arid.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Temp.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf
  A3-Antistasi/Templates/Invaders3CBAFRFT.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf
  A3-Antistasi/Templates/RHS_Occ_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_CDF_Wdl.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
  A3-Antistasi/Templates/Template Manual.txt
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Occ_AAF_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/initVar.sqf
Labels: change
