Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2019-10, with the labels that each got.

#360 Update rhs_usaf_machineGunner.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_machineGunner.sqf
Labels: change

#361 Update rhs_usaf_grenadier.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_grenadier.sqf
Labels: change

#363 Update rhs_usaf_rifleman.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_rifleman.sqf
Labels: change

#365 Update rhs_usaf_medic.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_medic.sqf
Labels: change

#362 Update rhs_usaf_marksman.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_marksman.sqf
Labels: change

#356 Punishment Debug return override value removed ("da!";)
  A3-Antistasi/functions/Punishment/fn_punishment.sqf
Labels: Fixed, Logging Enhancement, low priority

#399 Fixed heli mission bug
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
Labels: Bug-fix

#396 Unlocked at least one AA vehicle per airfield
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/init/fn_initSpawnPlaces.sqf
Labels: Bob likes that, change

#382 Rebel grenades and vests
  A3-Antistasi/Scripts/UPSMON/COMMON/unit/fnc/UPSMON_throw_stone.sqf
  A3-Antistasi/Templates/3CB_Occ_UKN-G_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_UKN-G_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_UN_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_UN_Trop.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Temp.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Arid.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Temp.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Arid.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Temp.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/initVar.sqf
Labels: Not now, Won't merge, change

#403 Add Antistasi Dev Deploy to Tools Folder
  .gitignore
  Tools/Antistasi Dev Deploy.exe
Labels: Bob likes that

#413 Changed a notification line that only referenced Roadblocks
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
Labels: change

#417 PR to fix multiple smaller issues
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_WPCreate.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/init/fn_getArrayMrks.sqf
  A3-Antistasi/functions/init/fn_prepareMarkerArrays.sqf
  A3-Antistasi/initVar.sqf
  A3-Antistasi/initZones.sqf
Labels: Bug-fix, Needs Testing

#422 Fixed a undefined case when spawning planes
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
Labels: Bug-fix

#423 Removed the "Too much units on one point" block
  A3-Antistasi/functions/Base/fn_splitVehicleCrewIntoOwnGroups.sqf
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
  A3-Antistasi/functions/Convoy/fn_createAIAction.sqf
  A3-Antistasi/functions/Convoy/fn_onConvoyArrival.sqf
  A3-Antistasi/functions/Convoy/fn_onSpawnedArrival.sqf
  A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf
Labels: Bug-fix

#424 Fixes error thrown because Ammo Trucks never got updated with new types
  A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf
  A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
Labels: Bug-fix

#434 Protects maxTypes parameter value in loot crates scripts
  A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf
  A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
Labels: Bug-fix

#435 added missing check for globmob DLC
  A3-Antistasi/functions/init/fn_initDisabledMods.sqf
Labels: Bug-fix

#431 changed `pushBack` to `pushBackUnique` in configSort
  A3-Antistasi/functions/Ammunition/fn_configSort.sqf
Labels: Bug-fix

#440 Remove Deadman Switch from ACE items
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
Labels: change

#419 Fixed flag exploit by adding safety check
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_mrkWIN.sqf
Labels: Bug-fix

#429 FIAinit Fixes round 1
  A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/functions/Ammunition/fn_dress.sqf
  A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf
  A3-Antistasi/functions/CREATE/fn_FIAinitBASES.sqf
  A3-Antistasi/functions/REINF/fn_FIAinit.sqf
Labels: change

#414 Auto rearm fix
  A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/functions/AI/fn_autoRearm.sqf
  A3-Antistasi/initVar.sqf
Labels: change
