Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-05, with the labels that each got.

#993 CSATRepairTruck fix
  A3-Antistasi/Templates/3CB_Inv_TKM_Arid.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Temp.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Trop.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Arct.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Arid.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Merge pending

#1014 Wurzel deactivate ifa
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: change

#996 Fix boss loss on respawn and clean up logging
  A3-Antistasi/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3-Antistasi/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf
  A3-Antistasi/functions/OrgPlayers/fn_theBossTransfer.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix, Priority

#1003 EndMission messages refactor and fixes
  A3-Antistasi/MissionDescription/endMission.hpp
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/description.ext
  Map-Templates/Antistasi-Altis.Altis/description.ext
  Map-Templates/Antistasi-Anizay.tem_anizay/description.ext
  Map-Templates/Antistasi-Chernarus.chernarus_summer/description.ext
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext
  Map-Templates/Antistasi-Kunduz.Kunduz/description.ext
  Map-Templates/Antistasi-Livonia.Enoch/description.ext
  Map-Templates/Antistasi-Malden.Malden/description.ext
  Map-Templates/Antistasi-Stratis.Stratis/description.ext
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/description.ext
  Map-Templates/Antistasi-WotP.Tanoa/description.ext
Labels: Bug-fix, Refactor

#1007 Remove Ace Interaction on VehicleBox
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: change, enhancement

#1008 SideMission breaking bugfix, Salvage mission
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
Labels: Bug-fix

#1022 Update start money
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: Bug-fix

#984 Wurzel large attack refactor
  A3-Antistasi/functions/Base/fn_mrkUpdate.sqf
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
Labels: Refactor, enhancement, performance

#1019 Add ifa to mod not allowed description
  A3-Antistasi/MissionDescription/endMission.hpp
Labels: enhancement

#998 Adding the effects of low and high aggro values for attacks and QRFs
  A3-Antistasi/REINF/addToGarrison.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_captureX.sqf
  A3-Antistasi/functions/AI/fn_occupantInvaderUnitKilledEH.sqf
  A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf
  A3-Antistasi/functions/Base/fn_getVehiclePoolForAttacks.sqf
  A3-Antistasi/functions/Base/fn_getVehiclePoolForQRFs.sqf
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
  A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
  A3-Antistasi/functions/Base/fn_timingCA.sqf
  A3-Antistasi/functions/Base/fn_translateVariable.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/CREATE/fn_CIVinit.sqf
  A3-Antistasi/functions/CREATE/fn_FIAinitBASES.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Intel/fn_selectIntel.sqf
  A3-Antistasi/functions/Missions/fn_AS_Official.sqf
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
  A3-Antistasi/functions/Missions/fn_AS_specOP.sqf
  A3-Antistasi/functions/Missions/fn_CON_Outpost.sqf
  A3-Antistasi/functions/Missions/fn_DES_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
  A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Ammo.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Bank.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_RES_Prisoners.sqf
  A3-Antistasi/functions/Missions/fn_attackHQ.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/REINF/fn_FIAinit.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: enhancement

#997 Fix outpost and airport markers initializing with wrong side name
  A3-Antistasi/functions/init/fn_initGarrisons.sqf
Labels: Bug-fix

#992 Stratis RoadDB
  Map-Templates/Antistasi-Stratis.Stratis/Navigation/RoadsDBstratis.sqf
Labels: enhancement

#1006 "SDKMortarSmokeMag" Fix for Reb_CDF
  A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
Labels: Bug-fix, enhancement

#1015 Fix savegame player money exploits and profilenamespace spam
  A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf
  A3-Antistasi/functions/OrgPlayers/fn_donateMoney.sqf
  A3-Antistasi/functions/OrgPlayers/fn_playerScoreAdd.sqf
  A3-Antistasi/functions/OrgPlayers/fn_resourcesPlayer.sqf
  A3-Antistasi/functions/OrgPlayers/fn_theBossSteal.sqf
  A3-Antistasi/functions/REINF/fn_buildCreateVehicleCallback.sqf
  A3-Antistasi/functions/REINF/fn_reinfPlayer.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/Save/fn_savePlayer.sqf
  A3-Antistasi/functions/Save/fn_setStatVariable.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix

#1028 Description.ext Fixes
  Map-Templates/Antistasi-Anizay.tem_anizay/description.ext
  Map-Templates/Antistasi-Chernarus.chernarus_summer/ak.jpg
  Map-Templates/Antistasi-Chernarus.chernarus_summer/description.ext
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext
  Map-Templates/Antistasi-Kunduz.Kunduz/description.ext
  Map-Templates/Antistasi-Livonia.Enoch/description.ext
  Map-Templates/Antistasi-Stratis.Stratis/description.ext
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/description.ext
  Map-Templates/Antistasi-Virolahti.vt7/description.ext
  Map-Templates/Antistasi-WotP.Tanoa/description.ext
Labels: enhancement

#1041 Document Antenna Switch in fn_initZones
  A3-Antistasi/functions/init/fn_initZones.sqf
Labels: Merge pending, Refactor, enhancement

#1058 Get rid of forced default TFAR radio volume
  A3-Antistasi/cba_settings.sqf
Labels: change

#1068 Overhaul of every map
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Stratis.Stratis/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
  Map-Templates/Antistasi-Virolahti.vt7/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: enhancement

#1069 Implemented proper Virolahti blurp text.
  A3-Antistasi/Stringtable.xml
Labels: change

#1012 Fix some marker changing issues
  A3-Antistasi/functions/Base/fn_mrkUpdate.sqf
Labels: Bug-fix

#1016 Fix orphaned and inaccessible saves
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Save/fn_deleteSave.sqf
  A3-Antistasi/functions/Save/fn_loadPlayer.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/Save/fn_savePlayer.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: enhancement

#1029 3CB BAF Additions
  A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Trop.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: enhancement

#1034 Starting Gear for Night/Removed ADV
  A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
  A3-Antistasi/functions/Templates/fn_getLoadout.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: change, enhancement

#1042 Added a warning for SP modus
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_singlePlayerBlackScreenWarning.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: enhancement
