Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-12, with the labels that each got.

#1484 Commanders purchase all vehicles with faction resources
  A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf
  A3-Antistasi/functions/REINF/fn_addFIAveh.sqf
Labels: Ready for merge, change

#1526 Handle a couple of roadblock direction problems
  A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf
Labels: Bug-fix, Ready for merge

#1566 Fix some arsenal magazine bugs
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
  A3-Antistasi/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
Labels: Bug-fix, Ready for merge

#1569 Fix captive state being stripped from handcuffed units waking from unconscious
  A3-Antistasi/functions/init/fn_initACEUnconsciousHandler.sqf
Labels: Bug-fix, Ready for merge

#1587 Add Small Tree to ClearForest
  A3-Antistasi/functions/Dialogs/fn_clearForest.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1591 issue 1590 fix - delete prop from vehicle arrays
  A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf
Labels: Bug-fix, Ready for merge

#1610 All hints are customHint, navGrid can run without customHint.
  A3-Antistasi/NavGridTools/createNavGrid.sqf
  A3-Antistasi/NavGridTools/extractRoadTypeData.sqf
  A3-Antistasi/NavGridTools/findOffset.sqf
  A3-Antistasi/functions/Base/fn_createOutpostsFIA.sqf
  A3-Antistasi/functions/Garage/fn_attemptPlaceVehicle.sqf
Labels: Ready for merge, Refactor

#1621 Added Vanilla_AI_NATO_Temperate
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
Labels: Project, Ready for merge, enhancement

#1481 Fix cargo/passenger truck problems
  A3-Antistasi/JeroenArsenal/JNL/Functions/fn_logistics_classHasCargo.sqf
  A3-Antistasi/JeroenArsenal/functions.hpp
  A3-Antistasi/Templates/3CB_Inv_Sov_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/CREATE/fn_createAIResources.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge

#1583 Fixed duplication of single mags
  A3-Antistasi/functions/LTC/fn_carryCrate.sqf
  A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
  A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
Labels: Bug-fix, Exploit, Ready for merge

#1589 Added Russian translation
  A3-Antistasi/Stringtable.xml
Labels: Ready for merge, localisation

#1600 Multilanguage support in Dialog Menu
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/dialogs.hpp
Labels: Ready for merge, localisation

#1603 Improve "Explosive Experts"/ Improve Minesweep
  A3-Antistasi/functions/AI/fn_mineSweep.sqf
  A3-Antistasi/functions/REINF/fn_equipRebel.sqf
Labels: Ready for merge, change, enhancement

#1614 Use Icon space to display previous hint titles.
  A3-Antistasi/functions/UI/fn_customHint.sqf
  A3-Antistasi/functions/UI/fn_customHintDismiss.sqf
  A3-Antistasi/functions/UI/fn_customHintInit.sqf
  A3-Antistasi/functions/UI/fn_customHintRender.sqf
Labels: Ready for merge, enhancement

#1615 Fix spam sell vehicle exploit
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions/Base/fn_sellVehicle.sqf
Labels: Bug-fix, Exploit, Ready for merge

#1625 AILoadInfo now has a title.
  A3-Antistasi/functions/Base/fn_AILoadInfo.sqf
Labels: Bug-fix, Ready for merge
