Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-10, with the labels that each got.

#1519 Tab to space conversion
  A3-Antistasi/Stringtable.xml
Labels: change

#1517 added an exit case if arty piece spawned badly and was destroyed
  A3-Antistasi/functions/AI/fn_artillery.sqf
Labels: Bug-fix, Ready for merge

#1515 failed findEmptyPosition attempts retry with massively expanded area
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
Labels: Bug-fix, Ready for merge

#1486 CS-1468-Chop-Long-Hints
  A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf
  A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
  A3-Antistasi/functions/Dialogs/fn_mineDialog.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Ready for merge, change

#1505 CS-1504-PurgeBSLoop
  A3-Antistasi/functions/UI/fn_customHint.sqf
  A3-Antistasi/functions/UI/fn_customHintInit.sqf
  A3-Antistasi/functions/UI/fn_customHintRender.sqf
Labels: Bug-fix, Ready for merge, performance

#1518 CS-1516-HintQueueToStack
  A3-Antistasi/functions/UI/fn_customHint.sqf
  A3-Antistasi/functions/UI/fn_customHintDismiss.sqf
  A3-Antistasi/functions/UI/fn_customHintInit.sqf
  A3-Antistasi/functions/UI/fn_customHintRender.sqf
Labels: Ready for merge, Refactor, change, enhancement

#1525 CS-1520-FFChecksLocalPvp
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
Labels: Bug-fix, Ready for merge

#1531 CS-1530 Persistent Save message is broadcast to clients.
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Bug-fix, Merge pending

#1535 CS-1534-JoinHint-AutoSaveTime
  A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf
  A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
Labels: Bug-fix, Ready for merge

#1539 CS-1536-AllDamageLog
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
  A3-Antistasi/functions/Revive/fn_handleDamage.sqf
Labels: Bug-fix, Priority, enhancement

#1544 blocked players in vehicles to load loadouts in the vehicle arsenal
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
Labels: Bug-fix

#1565 Add Takistan
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/functions/init/fn_initGarrisons.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  A3-Antistasi/functions/init/fn_initZones.sqf
  Map-Templates/Antistasi-Takistan.takistan/Navigation/navGridtakistan.sqf
  Map-Templates/Antistasi-Takistan.takistan/Navigation/roadsDBtakistan.sqf
  Map-Templates/Antistasi-Takistan.takistan/Pictures/Mission/pic.jpg
  Map-Templates/Antistasi-Takistan.takistan/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Takistan.takistan/description.ext
  Map-Templates/Antistasi-Takistan.takistan/mission.sqm
Labels: enhancement

#1483 Fix garrison spawning on destroyed buildings and windowless building
  A3-Antistasi/Scripts/UPSMON/COMMON/buildings/fnc/UPSMON_filterbuilding.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Bug-fix, Ready for merge

#1343 Loot to crate
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_load.sqf
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_unLoad.sqf
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_surrenderAction.sqf
  A3-Antistasi/functions/Base/fn_flagaction.sqf
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
  A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
  A3-Antistasi/functions/LTC/fn_canLoot.sqf
  A3-Antistasi/functions/LTC/fn_canTransfer.sqf
  A3-Antistasi/functions/LTC/fn_carryCrate.sqf
  A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
  A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
  A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
  A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
  A3-Antistasi/functions/REINF/fn_postmortem.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Ready for merge, change

#1494 Restrict loot crate respawns
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Ready for merge, enhancement

#1497 Expand vehicle selling and fix related static weapon unlock exploit
  A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf
  A3-Antistasi/functions/Base/fn_sellVehicle.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge, change

#1500 Added logging for unlocks
  A3-Antistasi/functions/Ammunition/fn_unlockEquipment.sqf
Labels: Ready for merge, change

#1502 fixed fast reverse towing exploit
  A3-Antistasi/Scripts/fn_advancedTowingInit.sqf
Labels: Bug-fix, Ready for merge

#1513 block adding of action to pvp
  A3-Antistasi/JeroenArsenal/JNL/Actions/fn_logistics_addActionLoad.sqf
Labels: Bug-fix, Ready for merge, low priority

#1523 Prevent saveplayer reporting an error for PvP players
  A3-Antistasi/functions/Save/fn_savePlayer.sqf
Labels: Bug-fix, Ready for merge

#1527 Prevent occupants launching airstrikes instead of QRFs on cities
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
Labels: Ready for merge, change

#1538 Remove CDF-PVP-Brdms
  A3-Antistasi/Templates/RHS_Occ_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_CDF_Temp.sqf
Labels: Ready for merge, change

#1549 Limit radio propaganda and tweak city supplies to compensate
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions/Base/fn_citySupportChange.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
  A3-Antistasi/functions/init/fn_cityinfo.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: Ready for merge, change

#1529 Virolahti Remove 2 Towns Markers
  A3-Antistasi/functions/init/fn_initZones.sqf
Labels: Ready for merge, change

#1562 City supplies - Blacklist update
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Ready for merge

#1564 made crash pos origin respect map boundaries
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
Labels: Bug-fix, Ready for merge

#1117 Update Stringtable.xml
  A3-Antistasi/Stringtable.xml
Labels: Ready for merge
