Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-04, with the labels that each got.

#940 [2.2.2] German localization
  A3-Antistasi/Stringtable.xml
Labels: localisation

#937 Fix AI Load Info remoteExec targeted on wrong machine
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: Bug-fix

#921 Airstrike sanity
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions/AI/fn_airbomb.sqf
  A3-Antistasi/functions/REINF/fn_NATObomb.sqf
Labels: Needs Testing, change

#952 RHS Mines and Breaching Charges fixes
  A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
Labels: Bug-fix

#953 Csatplane AFRF Fix
  A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf
Labels: Bug-fix

#942 disabled snow Script
  A3-Antistasi/functions/init/fn_initSnowFall.sqf
Labels: bug

#930 New war level calculation
  A3-Antistasi/functions/OrgPlayers/fn_tierCheck.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
Labels: change

#929 3CB Classname Fixes/Civcar changes
  A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
Labels: change, enhancement

#955 Remove LAT from RHS AFRF TL
  A3-Antistasi/Templates/Loadouts/rhs_afrf_teamLeader.sqf
Labels: change

#961 Fix marker colour-setting typo in mrkUpdate
  A3-Antistasi/functions/Base/fn_mrkUpdate.sqf
Labels: Bug-fix

#962 Prevent backpack drones from being used to farm airstrike points
  A3-Antistasi/functions/REINF/fn_addBombRun.sqf
Labels: Bug-fix

#964 Merge loot crate functions + minor fixes
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf
  A3-Antistasi/functions/Ammunition/fn_fillLootCrate.sqf
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/CREATE/fn_createAISite.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Ammo.sqf
Labels: Bug-fix, Refactor

#965 Prevent bogus JNL load action being added to surrender crates
  A3-Antistasi/functions/AI/fn_surrenderAction.sqf
Labels: Bug-fix

#966 Change logging function to default to logging to server
  A3-Antistasi/functions/Utility/fn_log.sqf
Labels: enhancement

#968 Port patrolReinf and patrolCA logging to A3A_fnc_log
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf
Labels: enhancement

#969 Fix various cases where repositioning HQ objects could injure players:
  A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf
Labels: Bug-fix

#970 Work around probable Arma bug causing mortar unpack/repack loop
  A3-Antistasi/functions/AI/fn_mortyAI.sqf
Labels: Bug-fix

#974 Fix exploit where crates could be loaded into a vehicle while undercover
  A3-Antistasi/JeroenArsenal/JNL/Actions/fn_logistics_addActionLoad.sqf
Labels: Bug-fix

#985 Change descriptive text for mRadius parameter
  A3-Antistasi/MissionDescription/params.hpp
Labels: change

#950 Weighted civilian vehicle templates
  A3-Antistasi/Templates/3CB_Civ.sqf
  A3-Antistasi/Templates/Auto_Civ.sqf
  A3-Antistasi/Templates/IFA_Civ.sqf
  A3-Antistasi/Templates/RHS_Civ.sqf
  A3-Antistasi/Templates/Vanilla_Civ.sqf
  A3-Antistasi/functions/Ammunition/fn_vehicleSort.sqf
  A3-Antistasi/functions/CREATE/fn_createCIV.sqf
  A3-Antistasi/functions/Templates/fn_ifaModCompat.sqf
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: enhancement

#960 Fixed various commander transfer and disconnection issues
  A3-Antistasi/REINF/controlunit.sqf
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_onPlayerDisconnect.sqf
  A3-Antistasi/functions/Base/fn_statistics.sqf
  A3-Antistasi/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3-Antistasi/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf
  A3-Antistasi/functions/OrgPlayers/fn_theBossInit.sqf
  A3-Antistasi/functions/OrgPlayers/fn_theBossToggleEligibility.sqf
  A3-Antistasi/functions/OrgPlayers/fn_theBossTransfer.sqf
  A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix

#975 Wurzel aggro rework
  A3-Antistasi/REINF/addToGarrison.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_captureX.sqf
  A3-Antistasi/functions/AI/fn_interrogate.sqf
  A3-Antistasi/functions/AI/fn_occupantInvaderUnitKilledEH.sqf
  A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf
  A3-Antistasi/functions/Base/fn_calculateAggression.sqf
  A3-Antistasi/functions/Base/fn_getAggroLevelString.sqf
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_powerReorg.sqf
  A3-Antistasi/functions/Base/fn_prestige.sqf
  A3-Antistasi/functions/Base/fn_rebuildAssets.sqf
  A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
  A3-Antistasi/functions/Base/fn_statistics.sqf
  A3-Antistasi/functions/CREATE/fn_AAFroadPatrol.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/CREATE/fn_CIVinit.sqf
  A3-Antistasi/functions/CREATE/fn_FIAinitBASES.sqf
  A3-Antistasi/functions/CREATE/fn_createCIV.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Convoy/fn_createAIAction.sqf
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
  A3-Antistasi/functions/Missions/fn_AS_specOP.sqf
  A3-Antistasi/functions/Missions/fn_DES_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
  A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Bank.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_RES_Prisoners.sqf
  A3-Antistasi/functions/Missions/fn_RES_Refugees.sqf
  A3-Antistasi/functions/Missions/fn_attackHQ.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/REINF/fn_FIAinit.sqf
  A3-Antistasi/functions/Revive/fn_unconsciousAAF.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: change, enhancement

#982 SalvageRope improvements and bug fix
  A3-Antistasi/functions/Missions/fn_LOG_Salvage.sqf
  A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
Labels: Bug-fix, enhancement

#986 Various Petros & moveHQObject fixes
  A3-Antistasi/functions/Base/fn_buildHQ.sqf
  A3-Antistasi/functions/Base/fn_createPetros.sqf
  A3-Antistasi/functions/Base/fn_moveHQ.sqf
  A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf
Labels: Bug-fix, enhancement

#988 Tag remote logs with player/HC name
  A3-Antistasi/functions/Utility/fn_log.sqf
Labels: enhancement
