Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-11, with the labels that each got.

#1441 CS-Collections: NestedObject: Wrapping for createNamespace
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Collections/doc_benchmarksGetSetRem.sqf
  A3-Antistasi/functions/Collections/fn_getNestedObject.sqf
  A3-Antistasi/functions/Collections/fn_remNestedObject.sqf
  A3-Antistasi/functions/Collections/fn_setNestedObject.sqf
Labels: Project, Ready for merge, enhancement, performance

#1445 Add more Item sorting | Add Radiobackpack Category
  A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
  A3-Antistasi/functions/Ammunition/fn_loot.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Ready for merge, change, enhancement

#1498 Delay autosave after manual save
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
Labels: Ready for merge, change

#1570 fixed broken salvage rope, improved functionality
  A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
Labels: Bug-fix, Priority, Ready for merge

#1581 Added list of global UI vars and UI processes.
  A3-Antistasi/functions/UI/fn_customHintInit.sqf
Labels: Ready for merge, Refactor, enhancement

#1595 3CB TPGM fix staticCrewTeamPlayer. 👀
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
Labels: Bug-fix, Ready for merge, change

#1584 Add Remove Rain to "Tent"
  A3-Antistasi/functions/Base/fn_flagaction.sqf
Labels: enhancement
