Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-01, with the labels that each got.

#632 Fixed a bad parameter name and made the system a bit more failsafe
  A3-Antistasi/functions/Garrison/fn_getVehicleCrew.sqf
  A3-Antistasi/functions/Garrison/fn_selectVehicleType.sqf
  A3-Antistasi/functions/Garrison/fn_updatePreference.sqf
Labels: Bug-fix

#623 Reducing price of helicopters to 500, replaced vehPlanes by isKindOf
  A3-Antistasi/functions/Base/fn_sellVehicle.sqf
Labels: bug

#595 Updated CSAT locations for new maps
  A3-Antistasi/functions/init/fn_initGarrisons.sqf
Labels: Bug-fix, Change Requested, Needs Testing

#642 Add a check to prevent breaching an empty or teamPlayer vehicle
  A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
Labels: Bug-fix, Needs Testing

#648 Add ACE spare barrel
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
Labels: enhancement

#654 roadsDB rename for Tanoa
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  Map-Templates/Antistasi-WotP.Tanoa/roadsDBTanoa.sqf
Labels: Bug-fix

#660 mission.sqm overhaul
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: Bug-fix

#666 D-insertion
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: Bug-fix

#668 mission.sqm update
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: change

#662 Enables unit traits
  A3-Antistasi/orgPlayers/unitTraits.sqf
Labels: enhancement

#672 2.2.1 unit traits
  A3-Antistasi/orgPlayers/unitTraits.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
Labels: enhancement

#655 Show injured marker for ACE Unconsciousness & AI Driver bug fix
  A3-Antistasi/functions/init/fn_playerMarkers.sqf
Labels: Bug-fix

#677 IEDs removed from vanilla starting gear.
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
Labels: change

#682 Unit update
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: change

#686 Cover update
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/PIC.jpg
  Map-Templates/Antistasi-Altis.Altis/PIC.jpg
  Map-Templates/Antistasi-WotP.Tanoa/PIC.jpg
Labels: change

#688 deactivate _ambient_sound_al
  A3-Antistasi/functions/init/fn_initSnowFall.sqf
Labels: Bug-fix

#693 Fices damn evil typo that breaks nato crates
  A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
Labels: Bug-fix

#620 Replaced all fnc_mp with RemoteExec(Call).
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_addAction.sqf
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_load.sqf
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_removeAction.sqf
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_unLoad.sqf
  A3-Antistasi/Scripts/UPSMON/COMMON/Core/fnc/UPSMON_SN_EHKILLEDCIV.sqf
  A3-Antistasi/Scripts/UPSMON/MODULES/UPSMON_CLONES.sqf
  A3-Antistasi/Scripts/UPSMON/MODULES/UPSMON_RESPAWN.sqf
  A3-Antistasi/Scripts/UPSMON/MODULES/UPSMON_spawn.sqf
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
  A3-Antistasi/functions/Base/fn_outpostDialog.sqf
  A3-Antistasi/functions/CREATE/fn_createFIAOutposts2.sqf
  A3-Antistasi/functions/Dialogs/fn_skiptime.sqf
  A3-Antistasi/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3-Antistasi/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVar.sqf
  A3-Antistasi/statSave/saveLoop.sqf
Labels: Bug-fix, Needs Testing, Refactor, enhancement, performance

#622 Added default variables for all getVariable to avoid null errors
  A3-Antistasi/functions/CREATE/fn_createFIAOutposts2.sqf
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Convoy/fn_createAIAction.sqf
  A3-Antistasi/functions/Convoy/fn_roadblockFight.sqf
  A3-Antistasi/functions/Garrison/fn_updateGarrison.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/REINF/fn_garrisonAdd.sqf
  A3-Antistasi/functions/init/fn_cityinfo.sqf
Labels: bug

#675 Meer jnl polishing
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf
Labels: enhancement

#684 Move radio tower repair to server side, fix bugs
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_rebuildAssets.sqf
  A3-Antistasi/functions/Base/fn_rebuildRadioTower.sqf
  A3-Antistasi/functions/Base/fn_repairRuinedBuilding.sqf
  A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
Labels: Bug-fix

#696 Fix typo in initZones
  A3-Antistasi/functions/init/fn_initZones.sqf
Labels: Bug-fix

#702 Livonia mission update
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
Labels: change

#705 Flag exchange to FIA
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
Labels: enhancement

#707 milBuildings update
  A3-Antistasi/functions/CREATE/fn_milBuildings.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: enhancement

#709 Altis Airfield Flag adjustment
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
Labels: enhancement

#716 Updates mission.sqm of chernarus winter
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
Labels: enhancement

#711 Change bogus remoteExecCalls to remoteExec
  A3-Antistasi/Scripts/UPSMON/MODULES/UPSMON_RESPAWN.sqf
  A3-Antistasi/Scripts/UPSMON/MODULES/UPSMON_spawn.sqf
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
  A3-Antistasi/functions/Base/fn_outpostDialog.sqf
  A3-Antistasi/functions/CREATE/fn_createFIAOutposts2.sqf
  A3-Antistasi/functions/Dialogs/fn_skiptime.sqf
  A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf
  A3-Antistasi/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3-Antistasi/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf
  A3-Antistasi/functions/REINF/fn_buildMinefield.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/statSave/saveLoop.sqf
Labels: Bug-fix

#703 Fix towed vehicles left with null attached objects
  A3-Antistasi/Scripts/fn_advancedTowingInit.sqf
Labels: Bug-fix

#712 Fix some SP bugs
  A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf
  A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: Bug-fix

#713 Prevent hardcoded city pop data from overwriting processed data
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  A3-Antistasi/functions/init/fn_initZones.sqf
Labels: Bug-fix

#694 Fix updateReinfState to no longer have cross reinforcements
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Garrison/fn_addRequested.sqf
  A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf
  A3-Antistasi/functions/Garrison/fn_updateReinfState.sqf
Labels: Bug-fix, Priority

#723 Create new category for cargo backpacks, use it for rebel AIs
  A3-Antistasi/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3-Antistasi/functions/REINF/fn_equipRebel.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix

#726 Fix arsenal loadouts
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_init.sqf
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
Labels: Bug-fix

#734 PVP Loadout assignment fix
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
Labels: Bug-fix

#730 Fix case where an airstrike targets an airport with no runway
  A3-Antistasi/functions/AI/fn_airstrike.sqf
Labels: Bug-fix

#728 3CB Fixes
  A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Trop.sqf
Labels: Bug-fix, enhancement

#742 Separate release & recruit actions on surrendered enemies
  A3-Antistasi/functions/AI/fn_captureX.sqf
  A3-Antistasi/functions/AI/fn_interrogate.sqf
  A3-Antistasi/functions/AI/fn_surrenderAction.sqf
  A3-Antistasi/functions/Base/fn_flagaction.sqf
Labels: Bug-fix

#749 Fix loadout item scrambling
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
Labels: Bug-fix
