Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-09, with the labels that each got.

#1438 Slingloadable supplies & working non-member countdown
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/orgPlayers/nonMemberDistance.sqf
Labels: Ready for merge

#1412 Fix Tanoa attack bugs
  A3-Antistasi/functions/CREATE/fn_WPCreate.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
Labels: Bug-fix, Ready for merge

#1386 Fix remaining setWaypointStatements
  A3-Antistasi/FSMs/ConvoyTravel.fsm
  A3-Antistasi/FSMs/ConvoyTravelAir.fsm
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_createQRF.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Convoy/fn_onSpawnedArrival.sqf
  A3-Antistasi/functions/REINF/fn_NATObomb.sqf
Labels: Bug-fix, Ready for merge

#1357 Replace CDF Rebells / Add Rebell Uniforms / Correct Typos
  A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_CDF_Temp.sqf
  A3-Antistasi/Templates/RHS_Reb_HIDF_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_HIDF_Temp.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS_Reb_NAPA_Temp.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
Labels: Bug-fix, Ready for merge, change, enhancement

#1420 Vanilla Cleanup
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Occ_AAF_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Temp.sqf
Labels: Bug-fix, enhancement

#1432 Replace 3CB BAF Statics | Classname corrections
  A3-Antistasi/Templates/3CB_Civ.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf
  A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
Labels: Bug-fix, change, enhancement

#1426 removed the param for gamemode "Reb vs Inv"
  A3-Antistasi/MissionDescription/params.hpp
Labels: Bug-fix

#1444 Fix remaining setWaypointStatements (bugfix PR)
  A3-Antistasi/FSMs/ConvoyTravel.fsm
  A3-Antistasi/FSMs/ConvoyTravelAir.fsm
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_createQRF.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Convoy/fn_onSpawnedArrival.sqf
  A3-Antistasi/functions/REINF/fn_NATObomb.sqf
Labels: Bug-fix

#1382 Fix some road search bugs
  A3-Antistasi/functions/Base/fn_findNearestGoodRoad.sqf
  A3-Antistasi/functions/Utility/fn_getRoadDirection.sqf
  A3-Antistasi/functions/init/fn_initZones.sqf
Labels: Bug-fix, Ready for merge

#1387 Changes to rebel attack
  A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
  A3-Antistasi/functions/CREATE/fn_createQRF.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
Labels: Bug-fix, change, enhancement

#1450 Get killzones into working condition
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/CREATE/fn_createQRF.sqf
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
  A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf
  A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf
Labels: Bug-fix, Priority, change

#1287 Adds JNL load action to quads spawned through placeEmptyVeh
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/Garage/fn_placeEmptyVehicle.sqf
Labels: Review pending, enhancement

#1440 Classify ace gadgets and add them to loot crates
  A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
  A3-Antistasi/functions/Ammunition/fn_loot.sqf
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: enhancement

#1452 Jeroen compatibility for supply crate
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf
Labels: Bug-fix

#1453 Scale killzone removal by active killzones
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
Labels: change

#1449 BUG-FIX 3CB Factions Radio
  A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
Labels: Bug-fix, change

#1389 Fix several issues with surrender/release code
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_captureX.sqf
  A3-Antistasi/functions/AI/fn_fleeToSide.sqf
  A3-Antistasi/functions/AI/fn_surrenderAction.sqf
  A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
  A3-Antistasi/functions/Revive/fn_actionRevive.sqf
  A3-Antistasi/functions/Revive/fn_unconsciousAAF.sqf
  A3-Antistasi/functions/init/fn_initACEUnconsciousHandler.sqf
Labels: Bug-fix, Ready for merge

#1435 Prevent equipping zero-count items from the arsenal
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
Labels: Bug-fix

#1472 fixed bad hint with supplies mission
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
Labels: Bug-fix, Ready for merge

#1469 Map Update: Move HQ, Helipads, Small changes
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
Labels: Ready for merge, change, enhancement

#1467 CS-1465-Hint-Refinement
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Revive/fn_initRevive.sqf
  A3-Antistasi/functions/UI/fn_customHint.sqf
  A3-Antistasi/functions/UI/fn_customHintDismiss.sqf
  A3-Antistasi/functions/UI/fn_customHintInit.sqf
  A3-Antistasi/functions/UI/fn_customHintRender.sqf
  A3-Antistasi/functions/UI/fn_dismissHint.sqf
  A3-Antistasi/functions/UI/fn_renderHint.sqf
  A3-Antistasi/functions/UI/fn_shader_ratioToHex.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Bug-fix, Ready for merge, enhancement, performance

#1461 Fix arsenal empty-slot selection
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
Labels: Bug-fix, Ready for merge

#1424 Added Korean Translation
  A3-Antistasi/Stringtable.xml
Labels: Ready for merge, enhancement

#1463 Swap flatbed trucks for transports in 3CB template transport slots
  A3-Antistasi/Templates/3CB_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
Labels: Bug-fix

#1456 fixed two errors with mission request
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
  A3-Antistasi/functions/Missions/fn_missionRequestAUTO.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
Labels: Bug-fix, Ready for merge

#1415 Updated README
  README.md
Labels: Ready for merge, change

#1485 Fix some minor undercover bugs
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
  A3-Antistasi/functions/init/fn_initACEUnconsciousHandler.sqf
Labels: Bug-fix, Ready for merge

#1482 Fix typo in deleteSave, add new saved vars
  A3-Antistasi/functions/Save/fn_deleteSave.sqf
Labels: Bug-fix, Ready for merge

#1493 Add seaports to secure bases for undercover
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
Labels: Bug-fix, Ready for merge, change
