Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-08, with the labels that each got.

#1020 Des heli fix
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
Labels: Bug-fix, Ready for merge, change

#1083 Added tool to log testing time
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_startTestingTimer.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, enhancement

#1339 patrolReinf termination overhaul
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_airdrop.sqf
  A3-Antistasi/functions/AI/fn_fastrope.sqf
  A3-Antistasi/functions/Base/fn_remUnitCount.sqf
  A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge

#1345 Fix unintentional use of Arma 1.95+ SQF feature
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge

#1353 Add 3CB BAF Arctic Template.
  A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/selector.sqf
Labels: Ready for merge, enhancement

#1101 missionRequest refactor
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: Bug-fix, Ready for merge, Refactor, enhancement

#1363 Remove Jackals and Coyotes from BAF templates
  A3-Antistasi/Templates/3CB_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf
Labels: Bug-fix, Ready for merge

#1376 CS 1374 Punishment teleport dangerous
  A3-Antistasi/functions/Punishment/fn_punishment_addActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_removeActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_client.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
Labels: Bug-fix, Project, Ready for merge

#1377 Fix non-hosted rebel airstrikes
  A3-Antistasi/functions/AI/fn_airbomb.sqf
Labels: Bug-fix, Ready for merge

#1379 Fix JNL Modelpath Typo
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf
Labels: Bug-fix, Ready for merge

#1381 added a helper and adjusted the attachment point
  A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
Labels: Bug-fix, Ready for merge

#1383 Fix initClient unintentionally running everything on headless clients
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: Bug-fix, Ready for merge

#1384 Fix loading of outpost & seaport markers from original save games
  A3-Antistasi/functions/Save/fn_loadStat.sqf
Labels: Bug-fix, Ready for merge

#1397 CS Dismissible Hints
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Revive/fn_initRevive.sqf
  A3-Antistasi/functions/UI/fn_customHint.sqf
  A3-Antistasi/functions/UI/fn_dismissHint.sqf
  A3-Antistasi/functions/UI/fn_renderHint.sqf
  A3-Antistasi/functions/UI/images/img_line_ca.paa
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Ready for merge, enhancement

#1399 Fixed the check boxes on bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Bug-fix, Ready for merge

#1402 garageVehicle spelling fix "engaging".
  A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
Labels: Bug-fix, Ready for merge

#1403 CS-1366-Vanilla-Ice-Revive
  A3-Antistasi/functions/Revive/fn_actionRevive.sqf
Labels: Ready for merge, change

#1408 _FF checks victim side and logs accordingly.
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
Labels: Bug-fix, Priority, Ready for merge

#1396 CUP/Enoch AA tower + intel support & trap defusing
  A3-Antistasi/functions/CREATE/fn_milBuildings.sqf
  A3-Antistasi/functions/Intel/fn_placeIntel.sqf
  A3-Antistasi/functions/Intel/fn_searchIntelOnLaptop.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1410 added out of bounds kill zone
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_placementselection.sqf
  A3-Antistasi/functions/Punishment/fn_outOfBounds.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix, Ready for merge, change
