Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-03, with the labels that each got.

#837 Fix HQ objects becoming lethal if dropped while moving
  A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf
Labels: Bug-fix

#791 Minor Loadout Overhaul (Bluefor, PVP Redress, GetLoadout)
  A3-Antistasi/Templates/Loadouts/rhs_usaf_AT.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_grenadier.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_teamLeader.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_AT.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_grenadier.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_machineGunner.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_marksman.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_medic.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_rifleman.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_rifleman_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_rifleman_tanoa.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_teamLeader.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_teamLeader_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_teamLeader_tanoa.sqf
  A3-Antistasi/functions/Ammunition/fn_ACEpvpReDress.sqf
  A3-Antistasi/functions/Templates/fn_getLoadout.sqf
Labels: change, enhancement

#795 Vanilla Nato Woodland
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_AT_WDL.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_machineGunner_WDL.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_marksman_WDL.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_medic_WDL.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_rifleman_WDL.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_blufor_teamLeader_WDL.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_WDL.sqf
Labels: change, enhancement

#796 Vanilla Csat Loadouts
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT2_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT2_enoch.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT2_tanoa.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT_enoch.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT_tanoa.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_enoch.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_tanoa.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_marksman_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_marksman_enoch.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_marksman_tanoa.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_medic_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_medic_enoch.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_medic_tanoa.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_teamLeader_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_teamLeader_enoch.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_teamLeader_tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf
Labels: change, enhancement

#798 AFRF Loadout Overhaul
  A3-Antistasi/Templates/Loadouts/rhs_afrf_AT.sqf
  A3-Antistasi/Templates/Loadouts/rhs_afrf_AT2.sqf
  A3-Antistasi/Templates/Loadouts/rhs_afrf_machineGunner.sqf
  A3-Antistasi/Templates/Loadouts/rhs_afrf_marksman.sqf
  A3-Antistasi/Templates/Loadouts/rhs_afrf_medic.sqf
  A3-Antistasi/Templates/Loadouts/rhs_afrf_teamLeader.sqf
Labels: Bug-fix, change, enhancement

#813 3CB Loadouts + small PVP Fixes.
  A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/BAF_Occ_BAF_Trop.sqf
  A3-Antistasi/Templates/Loadouts/3CB_BAF_AT2_MTP.sqf
  A3-Antistasi/Templates/Loadouts/3CB_BAF_AT_MTP.sqf
  A3-Antistasi/Templates/Loadouts/3CB_BAF_MachineGunner_MTP.sqf
  A3-Antistasi/Templates/Loadouts/3CB_BAF_Marksman_MTP.sqf
  A3-Antistasi/Templates/Loadouts/3CB_BAF_Medic_MTP.sqf
  A3-Antistasi/Templates/Loadouts/3CB_BAF_Teamleader_MTP.sqf
Labels: Bug-fix, enhancement

#841 Workaround for Zeus link lost when old corpse is deleted
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix

#847 Fix bogus classname for 3CB invader flagpole
  A3-Antistasi/Templates/3CB_Inv_TKM_Arid.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Temp.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Trop.sqf
Labels: Bug-fix

#853 Fixes Vanilla Csat Machinegunners
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_altis.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_enoch.sqf
  A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_tanoa.sqf
Labels: Bug-fix

#855 Jeroen Nots Debug-stuff
  A3-Antistasi/JeroenArsenal/JND/fn_debugv2.sqf
  A3-Antistasi/JeroenArsenal/functions.hpp
Labels: enhancement

#866 Takistan Militia PvP Loadouts
  A3-Antistasi/Templates/3CB_Inv_TKM_Arid.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Temp.sqf
  A3-Antistasi/Templates/3CB_Inv_UKN_Trop.sqf
  A3-Antistasi/Templates/Loadouts/3CB_TKM_AT.sqf
  A3-Antistasi/Templates/Loadouts/3CB_TKM_AT2.sqf
  A3-Antistasi/Templates/Loadouts/3CB_TKM_MachineGunner.sqf
  A3-Antistasi/Templates/Loadouts/3CB_TKM_Marksman.sqf
  A3-Antistasi/Templates/Loadouts/3CB_TKM_Medic.sqf
  A3-Antistasi/Templates/Loadouts/3CB_TKM_Teamleader.sqf
Labels: enhancement

#868 Whiteboard update
  A3-Antistasi/init.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/whiteboard.jpg
  Map-Templates/Antistasi-Altis.Altis/whiteboard.jpg
  Map-Templates/Antistasi-Anizay.tem_anizay/whiteboard.jpg
  Map-Templates/Antistasi-Chernarus.chernarus_summer/whiteboard.jpg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/whiteboard.jpg
  Map-Templates/Antistasi-Kunduz.Kunduz/whiteboard.jpg
  Map-Templates/Antistasi-Livonia.Enoch/whiteboard.jpg
  Map-Templates/Antistasi-Malden.Malden/whiteboard.jpg
  Map-Templates/Antistasi-Stratis.Stratis/whiteboard.jpg
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/whiteboard.jpg
  Map-Templates/Antistasi-WotP.Tanoa/whiteboard.jpg
Labels: enhancement

#851 Fixed missing startWithLongRangeRadio parameter
  A3-Antistasi/functions/init/fn_initServer.sqf
Labels: Bug-fix

#861 Restrict vehicle box repair to unoccupied and rebel vehicles
  A3-Antistasi/functions/Base/fn_healAndRepair.sqf
Labels: Bug-fix

#859 Fix reversed winner/loser params in markerChange
  A3-Antistasi/functions/Base/fn_markerChange.sqf
Labels: Bug-fix

#880 Picture folder adaptation for mission related files
  A3-Antistasi/init.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/description.ext
  Map-Templates/Antistasi-Altis.Altis/Pictures/Mission/pic.jpg
  Map-Templates/Antistasi-Altis.Altis/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Altis.Altis/description.ext
  Map-Templates/Antistasi-Anizay.tem_anizay/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Anizay.tem_anizay/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Anizay.tem_anizay/description.ext
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Chernarus.chernarus_summer/description.ext
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext
  Map-Templates/Antistasi-Kunduz.Kunduz/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Kunduz.Kunduz/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Kunduz.Kunduz/description.ext
  Map-Templates/Antistasi-Livonia.Enoch/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Livonia.Enoch/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Livonia.Enoch/description.ext
  Map-Templates/Antistasi-Malden.Malden/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Malden.Malden/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Malden.Malden/description.ext
  Map-Templates/Antistasi-Stratis.Stratis/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Stratis.Stratis/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Stratis.Stratis/description.ext
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/description.ext
  Map-Templates/Antistasi-WotP.Tanoa/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-WotP.Tanoa/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-WotP.Tanoa/description.ext
Labels: change

#881 adaptation of pictures for Intel system
  A3-Antistasi/Pictures/Intel/laptop_complete.paa
  A3-Antistasi/Pictures/Intel/laptop_die.paa
  A3-Antistasi/Pictures/Intel/laptop_downloading.paa
  A3-Antistasi/Pictures/Intel/laptop_error.paa
  A3-Antistasi/Pictures/Intel/laptop_error1.paa
  A3-Antistasi/Pictures/Intel/laptop_error2.paa
  A3-Antistasi/Pictures/Intel/laptop_error3.paa
  A3-Antistasi/Pictures/Intel/laptop_error4.paa
  A3-Antistasi/Pictures/Intel/laptop_error5.paa
  A3-Antistasi/Pictures/Intel/laptop_error6.paa
  A3-Antistasi/functions/Intel/fn_searchIntelOnLaptop.sqf
Labels: change

#883 Navigation file adaptation
  A3-Antistasi/NavGrids/navGridBornholm.sqf
  A3-Antistasi/NavGrids/navGridisladuala3.sqf
  A3-Antistasi/NavGrids/navGridlingor3.sqf
  A3-Antistasi/NavGrids/navGridnapf.sqf
  A3-Antistasi/NavGrids/navGridtakistan.sqf
  A3-Antistasi/NavGrids/navGridtem_kujari.sqf
  A3-Antistasi/NavGrids/navGridvt7.sqf
  A3-Antistasi/functions/Pathfinding/fn_loadNavGrid.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Navigation/navGridAltis.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Navigation/roadsDBAltis.sqf
  Map-Templates/Antistasi-Altis.Altis/Navigation/navGridAltis.sqf
  Map-Templates/Antistasi-Altis.Altis/Navigation/roadsDBAltis.sqf
  Map-Templates/Antistasi-Anizay.tem_anizay/Navigation/navGridtem_anizay.sqf
  Map-Templates/Antistasi-Anizay.tem_anizay/Navigation/roadsDBAnizay.sqf
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Navigation/navGridchernarus_summer.sqf
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Navigation/roadsDBcherna.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/Navigation/navGridchernarus_winter.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/Navigation/roadsDBcherna.sqf
  Map-Templates/Antistasi-Kunduz.Kunduz/Navigation/navGridKunduz.sqf
  Map-Templates/Antistasi-Kunduz.Kunduz/Navigation/roadsDBKunduz.sqf
  Map-Templates/Antistasi-Livonia.Enoch/Navigation/navGridenoch.sqf
  Map-Templates/Antistasi-Livonia.Enoch/Navigation/roadsDBLivonia.sqf
  Map-Templates/Antistasi-Malden.Malden/Navigation/navGridMalden.sqf
  Map-Templates/Antistasi-Malden.Malden/Navigation/roadsDBmalden.sqf
  Map-Templates/Antistasi-Stratis.Stratis/Navigation/navGridStratis.sqf
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Navigation/navGridTembelan.sqf
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Navigation/roadsDBTembelan.sqf
  Map-Templates/Antistasi-WotP.Tanoa/Navigation/navGridTanoa.sqf
  Map-Templates/Antistasi-WotP.Tanoa/Navigation/roadsDBTanoa.sqf
Labels: enhancement

#890 Remove TK uniform check due to uniform inconsistency
  A3-Antistasi/functions/Revive/fn_handleDamage.sqf
Labels: change

#860 Make helmet popping a chance rather than automatic
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions/Revive/fn_handleDamage.sqf
  A3-Antistasi/functions/Revive/fn_handleDamageAAF.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
Labels: change

#895 Added verb log level for those that need it
  A3-Antistasi/functions/Utility/fn_log.sqf
Labels: enhancement

#898 Removed `#` Validation which is used for array selection
  Tools/sqf_validate.py
Labels: Bug-fix

#857 JND implementation the second
  A3-Antistasi/JeroenArsenal/JND/fn_debugv2.sqf
  A3-Antistasi/JeroenArsenal/functions.hpp
Labels: Priority, enhancement

#897 Updated Logging for Verbose layer
  A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf
  A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
  A3-Antistasi/functions/Base/fn_logPerformance.sqf
  A3-Antistasi/functions/REINF/fn_equipRebel.sqf
  A3-Antistasi/functions/Utility/fn_log.sqf
Labels: enhancement

#887 Fix bug in spawn distance reduction button
  A3-Antistasi/dialogs.hpp
Labels: Bug-fix

#888 Change TIME_LEFT intel option to return approx time until next attack
  A3-Antistasi/functions/Intel/fn_selectIntel.sqf
Labels: Bug-fix, change

#902 Flags + Textures, Small fixes
  A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf
  A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
Labels: enhancement

#915 Fix error when rebels equip a grenade launcher that's not a rifle
  A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf
Labels: Bug-fix

#916 Fix savePlayer error caused by group member without a value
  A3-Antistasi/functions/Save/fn_savePlayer.sqf
Labels: Bug-fix

#917 Remove patrol heli from attack heli array in 3CB TKA template
  A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
Labels: Bug-fix

#918 Fix traitor mission despawn and surrender bugs
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
Labels: Bug-fix
