Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2020-06, with the labels that each got.

#1049 Remove more junk in the garbage cleaner
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
Labels: enhancement

#1050 Civilian Uniform removal
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
Labels: enhancement

#1053 JNL USAF Truck adjustment/Additions
  A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf
Labels: enhancement

#1054 updated dialog_load_previous_session
  A3-Antistasi/Stringtable.xml
Labels: change

#1062 Change JNA to accept all magazine types
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_itemType.sqf
Labels: Bug-fix

#1067 Enable cargo-to-arsenal transfer for planes and helis
  A3-Antistasi/functions/Ammunition/fn_ammunitionTransfer.sqf
  A3-Antistasi/functions/Ammunition/fn_empty.sqf
Labels: enhancement

#1043 AIVEHinit and despawn rework
  A3-Antistasi/FSMs/ConvoyTravel.fsm
  A3-Antistasi/FSMs/ConvoyTravelAir.fsm
  A3-Antistasi/Scripts/fn_advancedTowingInit.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_artillery.sqf
  A3-Antistasi/functions/AI/fn_mineSweep.sqf
  A3-Antistasi/functions/AI/fn_mortarDrill.sqf
  A3-Antistasi/functions/AI/fn_mortyAI.sqf
  A3-Antistasi/functions/AI/fn_staticMGDrill.sqf
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/CREATE/fn_AAFroadPatrol.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/CREATE/fn_VEHdespawner.sqf
  A3-Antistasi/functions/CREATE/fn_cleanserVeh.sqf
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/CREATE/fn_createAIResources.sqf
  A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf
  A3-Antistasi/functions/CREATE/fn_createCIV.sqf
  A3-Antistasi/functions/CREATE/fn_createFIAOutposts2.sqf
  A3-Antistasi/functions/CREATE/fn_createSDKgarrisons.sqf
  A3-Antistasi/functions/CREATE/fn_createSDKgarrisonsTemp.sqf
  A3-Antistasi/functions/CREATE/fn_groupDespawner.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf
  A3-Antistasi/functions/CREATE/fn_vehKilledOrCaptured.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf
  A3-Antistasi/functions/Convoy/fn_spawnConvoyLine.sqf
  A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
  A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Ammo.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Bank.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Salvage.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_RES_Refugees.sqf
  A3-Antistasi/functions/Missions/fn_attackHQ.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/REINF/fn_NATOQuadbike.sqf
  A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf
  A3-Antistasi/functions/REINF/fn_buildMinefield.sqf
  A3-Antistasi/functions/REINF/fn_stealStatic.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix

#1052 Road requirement removed from outpost trucks.
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
Labels: Bug-fix

#1061 Caleb s punishment patch
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_initPetros.sqf
  A3-Antistasi/functions/Dialogs/fn_fastTravelRadio.sqf
  A3-Antistasi/functions/Punishment/fn_punishment.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_addActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_checkStatus.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataGet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataNamespace.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataRem.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataSet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_notifyAdmin.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_notifyAllAdmins.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_release.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_removeActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_client.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_warden.sqf
  A3-Antistasi/functions/Revive/fn_handleDamage.sqf
  A3-Antistasi/functions/Revive/fn_initRevive.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix, Needs Testing, enhancement

#1072 Fix non-private vars in addGarrison
  A3-Antistasi/functions/Garrison/fn_addGarrison.sqf
Labels: Bug-fix, Priority

#1076 Add Flight Suit to Airport Crates
  A3-Antistasi/functions/Ammunition/fn_itemSort.sqf
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: enhancement

#1078 Fixed Variable Name
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
Labels: Bug-fix

#1082 Caleb s punish rpt spam
  A3-Antistasi/functions/Punishment/fn_punishment.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_addActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_checkStatus.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataGet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataRem.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataSet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_notifyAdmin.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_release.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_removeActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_client.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
Labels: enhancement

#1085 No longer logs when checkStatus on AI.
  A3-Antistasi/functions/Punishment/fn_punishment_checkStatus.sqf
Labels: Bug-fix

#1105 Adds Czech translation and fixes small typos
  A3-Antistasi/Stringtable.xml
Labels: enhancement

#1108 fn_artySupport spelling error
  A3-Antistasi/functions/AI/fn_artySupport.sqf
Labels: Ready for merge

#1103 Remove MG optic from USAF PvP TL
  A3-Antistasi/Templates/Loadouts/rhs_usaf_teamLeader.sqf
Labels: Ready for merge, change

#1094 Remove rhs bangs
  A3-Antistasi/Templates/Loadouts/rhs_afrf_marksman.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_AT.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_machineGunner.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_marksman.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_medic.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_rifleman.sqf
  A3-Antistasi/Templates/Loadouts/rhs_usaf_teamLeader.sqf
Labels: Ready for merge, change

#1109 French translation
  A3-Antistasi/Stringtable.xml
Labels: Ready for merge, enhancement

#1096 Fix broken halfing for rebel case of airbomb
  A3-Antistasi/functions/AI/fn_airbomb.sqf
Labels: Bug-fix, Ready for merge, low priority

#1099 Refactor and fixes to get the convoy mission approximately working:
  A3-Antistasi/FSMs/DriveAlongPath.fsm
  A3-Antistasi/functions/AI/fn_vehicleMarkers.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
Labels: Bug-fix, Refactor

#1137 RHS-USAF-Template Update Full Camo.
  A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
Labels: Bug-fix, Ready for merge, change, enhancement

#1132 added a log for JIP, fixed bad respawn eh and spawn loop
  A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
Labels: Bug-fix, Priority

#1140 Fixed edge case when vehicle array is empty
  A3-Antistasi/functions/Base/fn_getVehiclePoolForAttacks.sqf
  A3-Antistasi/functions/Base/fn_getVehiclePoolForQRFs.sqf
Labels: Bug-fix

#1149 Sonorous meerkat remove vtol
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_WDL.sqf
Labels: change

#1143 Fix arsenal item removal exploit
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
Labels: Bug-fix, Ready for merge

#1147 Fixed HUD not getting updated on mission load with aggression
  A3-Antistasi/functions/Save/fn_loadStat.sqf
Labels: Bug-fix, Ready for merge

#1133 publicVariableClient version of destroyedBuildings fix, works on HCs
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_requestDataFromServer.sqf
  A3-Antistasi/functions/Base/fn_setDataOnClient.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: Bug-fix, Ready for merge, Refactor

#1161 Altis map updates
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
Labels: Ready for merge, change, enhancement

#1155 Improve diveGear spawning.
  A3-Antistasi/functions/Ammunition/fn_itemSort.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/CREATE/fn_createAISite.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1160 Improved the text for reinforcements convoys, so they are less confusing
  A3-Antistasi/functions/Convoy/fn_createConvoy.sqf
  A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf
Labels: Added to changelog, Ready for merge, enhancement

#1131 navGrid loading fixes and cleanup
  A3-Antistasi/functions/Pathfinding/fn_loadNavGrid.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initZones.sqf
Labels: Added to changelog, Bug-fix, Ready for merge

#1124 Various fixes for building-placed static weapons
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/CREATE/fn_milBuildings.sqf
Labels: Bug-fix, Refactor, Review pending

#1175 Map updates
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Virolahti.vt7/mission.sqm
Labels: Bug-fix, Ready for merge

#1167 Hangar Update/Enhancement
  A3-Antistasi/functions/init/fn_initSpawnPlaces.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1170 Make AA vehicles breachable plus fixes
  A3-Antistasi/functions/Base/fn_addActionBreachVehicle.sqf
  A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1171 Fix incorrect uses of local-only inventory modification functions
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
  A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf
  A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
  A3-Antistasi/functions/CREATE/fn_NATOinit.sqf
Labels: Bug-fix, Ready for merge

#1172 Fix edge cases for attacks
  A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
Labels: Bug-fix, Ready for merge

#1178 added block if units are already in a garrison
  A3-Antistasi/REINF/addToGarrison.sqf
Labels: Bug-fix, Ready for merge

#1182 Make airstrikes despawn correctly after reaching their final waypoint
  A3-Antistasi/functions/AI/fn_airstrike.sqf
Labels: Bug-fix, Ready for merge

#1098 Caleb s punish rpt spam
  .gitignore
  A3-Antistasi/REINF/controlHCsquad.sqf
  A3-Antistasi/REINF/controlunit.sqf
  A3-Antistasi/functions/Punishment/fn_punishment.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_addActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_checkStatus.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataGet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataRem.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataSet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_notifyAdmin.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_release.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_removeActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_client.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
  A3-Antistasi/functions/Revive/fn_initRevive.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix, Ready for merge

#1186 Added how to build with ADD
  README.md
Labels: enhancement

#1184 Anti dev deploy xml parse
  Tools/Antistasi Dev Deploy.exe
Labels: enhancement

#1156 Updated readme
  README.md
Labels: enhancement

#1188 Update PR template
  .github/pull_request_template.md
Labels: enhancement
