Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-08, with the labels that each got.

#2009 3CB Factions, Add more Templates, New Vehicles, Nodes.
  A3-Antistasi/Templates/NewTemplates/3CB/3CBFactions_Logistics_Nodes.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_AAF.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_ADA.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_ANA.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_HIDF.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_MDF.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Logistics_Nodes.sqf
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions/Base/fn_setPlaneLoadout.sqf
Labels: Ready for merge, Review pending, change, enhancement

#1989 AI Minefield stuff
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_MACV.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf
  A3-Antistasi/functions/CREATE/fn_minefieldAAF.sqf
Labels: Ready for merge, Review pending, change, enhancement

#2028 patched fake lanucher magazines being added to loadouts
  A3-Antistasi/functions/Templates/Loadouts/fn_loadout_builder.sqf
  A3-Antistasi/functions/Templates/Loadouts/fn_loadout_defaultWeaponMag.sqf
Labels: Bug-fix, Ready for merge

#2031 License change from SSL -> APL-ND for the garage
  A3-Antistasi/Garage/APL-ND.pdf
  A3-Antistasi/Garage/Core/fn_addUser.sqf
  A3-Antistasi/Garage/Core/fn_broadcast.sqf
  A3-Antistasi/Garage/Core/fn_confirm.sqf
  A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
  A3-Antistasi/Garage/Core/fn_declairSources.sqf
  A3-Antistasi/Garage/Core/fn_genVehUID.sqf
  A3-Antistasi/Garage/Core/fn_getCatIndex.sqf
  A3-Antistasi/Garage/Core/fn_onLoad.sqf
  A3-Antistasi/Garage/Core/fn_onUnload.sqf
  A3-Antistasi/Garage/Core/fn_reciveBroadcast.sqf
  A3-Antistasi/Garage/Core/fn_releaseAllVehicles.sqf
  A3-Antistasi/Garage/Core/fn_reloadCategory.sqf
  A3-Antistasi/Garage/Core/fn_reloadPreview.sqf
  A3-Antistasi/Garage/Core/fn_removeFromPool.sqf
  A3-Antistasi/Garage/Core/fn_removeUser.sqf
  A3-Antistasi/Garage/Core/fn_requestSelectionChange.sqf
  A3-Antistasi/Garage/Core/fn_requestVehicle.sqf
  A3-Antistasi/Garage/Core/fn_selectionChange.sqf
  A3-Antistasi/Garage/Core/fn_switchCategory.sqf
  A3-Antistasi/Garage/Core/fn_toggleConfirmBttn.sqf
  A3-Antistasi/Garage/Core/fn_toggleLock.sqf
  A3-Antistasi/Garage/Core/fn_updateCamPos.sqf
  A3-Antistasi/Garage/Core/fn_validateGarage.sqf
  A3-Antistasi/Garage/Dialogs.hpp
  A3-Antistasi/Garage/Extras/fn_findMount.sqf
  A3-Antistasi/Garage/Extras/fn_isAmmoSource.sqf
  A3-Antistasi/Garage/Extras/fn_isFuelSource.sqf
  A3-Antistasi/Garage/Extras/fn_isRepairSource.sqf
  A3-Antistasi/Garage/Extras/fn_reloadExtras.sqf
  A3-Antistasi/Garage/Extras/fn_reloadMounts.sqf
  A3-Antistasi/Garage/Extras/fn_requestMount.sqf
  A3-Antistasi/Garage/Extras/fn_switchExtrasMenu.sqf
  A3-Antistasi/Garage/Extras/fn_switchTexture.sqf
  A3-Antistasi/Garage/Extras/fn_toggleAnim.sqf
  A3-Antistasi/Garage/LICENSE
  A3-Antistasi/Garage/Pylons/fn_pylonsPresetChanged.sqf
  A3-Antistasi/Garage/Pylons/fn_reloadPylons.sqf
  A3-Antistasi/Garage/Pylons/fn_updatePylons.sqf
  A3-Antistasi/Garage/StatePreservation/fn_getAmmoData.sqf
  A3-Antistasi/Garage/StatePreservation/fn_getDamage.sqf
  A3-Antistasi/Garage/StatePreservation/fn_getFuel.sqf
  A3-Antistasi/Garage/StatePreservation/fn_getState.sqf
  A3-Antistasi/Garage/StatePreservation/fn_prepPylons.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setAmmoData.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setDamage.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setFuel.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setState.sqf
  A3-Antistasi/Garage/config.inc
  A3-Antistasi/Garage/defines.hpp
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/Garage/fn_addVehiclesByClass.sqf
  A3-Antistasi/Garage/fn_callbackHandler.sqf
  A3-Antistasi/Garage/fn_getSaveData.sqf
  A3-Antistasi/Garage/fn_initGarage.sqf
  A3-Antistasi/Garage/fn_initServer.sqf
  A3-Antistasi/Garage/fn_loadSaveData.sqf
Labels: Ready for merge, enhancement

#2032 Updated StreetArtist LICENSE.txt
  Tools/StreetArtist/LICENSE.txt
Labels: Ready for merge, Refactor

#2033 Cln updates (hanoi2 civ count & factory_1 placements)
  A3-Antistasi/functions/init/fn_initZones.sqf
  Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/mission.sqm
Labels: Bug-fix, Ready for merge

#2035 Replace Militia Mraps
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_LDF_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
Labels: change, enhancement, Balance

#2039 Temporarily Remove Tunguska
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_AAF.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_SOV.sqf
Labels: Ready for merge, Balance

#2044 corrected intel search on large and encrypted intel not using chached…
  A3-Antistasi/functions/Intel/fn_searchEncryptedIntel.sqf
  A3-Antistasi/functions/Intel/fn_searchIntelOnLaptop.sqf
Labels: Bug-fix, Ready for merge

#2040 Testing light
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/Templates/NewTemplates/FactionDefaults/RebelDefaults.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/UtilityItems/fn_initUtilityItems.sqf
  A3-Antistasi/functions/UtilityItems/fn_rotateItem.sqf
  A3-Antistasi/functions/UtilityItems/fn_spawnLight.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: enhancement, Ready for merge

#2041 Toggle top information bar visibility while opening/closing garage, ability to toggle info bar visibility via hotkeys
  A3-Antistasi/Garage/Core/fn_onUnload.sqf
  A3-Antistasi/Garage/config.inc
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/briefing.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_keys.sqf
  A3-Antistasi/functions/UI/fn_disableInfoBar.sqf
  A3-Antistasi/functions/UI/fn_updateInfoBarShown.sqf
Labels: enhancement, good first issue, Ready for merge

#2045 Fix missing remoteExec target causing RPT spam in task delete
  A3-Antistasi/functions/Missions/fn_taskDelete.sqf
Labels: Bug-fix, Ready for merge

#2052 updated feedback for vehicleBoxHeal
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/functions/Base/fn_vehicleBoxHeal.sqf
Labels: Bug-fix, Ready for merge

#2053 fix addVehicleByClass lacking source detection
  A3-Antistasi/Garage/Extras/fn_isAmmoSource.sqf
  A3-Antistasi/Garage/Extras/fn_isFuelSource.sqf
  A3-Antistasi/Garage/Extras/fn_isRepairSource.sqf
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/Garage/fn_addVehiclesByClass.sqf
Labels: Bug-fix, Ready for merge

#2055 blocked rebel auto capture
  A3-Antistasi/functions/Base/fn_zoneCheck.sqf
Labels: change

#2056 Punishment bug fix
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
Labels: Bug-fix, Ready for merge

#2059 Fix 2.4 -> 2.5 rebel garrison compatibility
  A3-Antistasi/functions/Save/fn_loadStat.sqf
Labels: Bug-fix, Ready for merge

#2061 Protect players from themselves with fog params sanitization
  A3-Antistasi/functions/Base/fn_flagaction.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
Labels: change, Ready for merge

#2062 Fix attackHQ transport planes
  A3-Antistasi/functions/CREATE/fn_spawnVehicle.sqf
  A3-Antistasi/functions/Missions/fn_attackHQ.sqf
Labels: Bug-fix, Ready for merge

#2067 Prevent bad unit types being added to garrisons, repair saves
  A3-Antistasi/REINF/addToGarrison.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
Labels: Bug-fix, Ready for merge

#2078 made custom JIP keys for Logistics system
  A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
Labels: Bug-fix, Ready for merge

#2077 Change zoneCheck to use marker-size based capture radius
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_mrkWIN.sqf
  A3-Antistasi/functions/Base/fn_zoneCheck.sqf
Labels: Bug-fix, change, Ready for merge, Balance

#2057 functions.hpp tabs to spaces
  A3-Antistasi/functions.hpp
Labels: change, Ready for merge
