Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-05, with the labels that each got.

#1818 Doom go undercover split
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
Labels: Project, Ready for merge, Refactor

#1866 Doom move hq split
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_canMoveHQ.sqf
  A3-Antistasi/functions/Base/fn_moveHQ.sqf
Labels: Project, Ready for merge, Refactor, enhancement

#1897 TFAR BETA settings update
  A3-Antistasi/cba_settings.sqf
Labels: Ready for merge

#1910 VN, Fix Missing Item / Expand Item Filtering
  A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
  A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf
  A3-Antistasi/functions/ModsAndDLC/fn_isModNameVanilla.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Bug-fix, enhancement

#1911 fix error from equipmentIsValidForCurrentmodset
  A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf
  A3-Antistasi/functions/ModsAndDLC/fn_isModNameVanilla.sqf
Labels: Ready for merge, VN-development

#1913 Fix references to FlagCarrier so that they work for VN flagpoles
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
Labels: Bug-fix, Ready for merge, VN-development

#1916 VN Change Loot boxes due to Infinite Load
  A3-Antistasi/Templates/NewTemplates/VN/VN_MACV.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_PAVN.sqf
Labels: Bug-fix, Ready for merge, VN-development

#1920 Vanilla medical fixes + VN AI compatibility
  A3-Antistasi/functions/AI/fn_askHelp.sqf
  A3-Antistasi/functions/AI/fn_chargeWithSmoke.sqf
  A3-Antistasi/functions/AI/fn_help.sqf
  A3-Antistasi/functions/REINF/fn_equipRebel.sqf
Labels: Bug-fix, Ready for merge, VN-development

#1922 Vn Expand Starting Gear
  A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf
Labels: Ready for merge, VN-development, enhancement

#1923 VN Weapon Category Filtering
  A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
Labels: Ready for merge, VN-development, enhancement

#1931 Vn map update
  A3-Antistasi/functions/init/fn_initZones.sqf
  Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/mission.sqm
Labels: Bug-fix, Ready for merge, VN-development, enhancement

#1934 Enable faster vanilla revive cancels
  A3-Antistasi/functions/Revive/fn_actionRevive.sqf
Labels: Review pending, VN-development, enhancement

#1935 Logistics fixes for vn
  A3-Antistasi/Templates/NewTemplates/3CB/3CBBAF_Logistics_Nodes.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CBFactions_Logistics_Nodes.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Logistics_Nodes.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_canLoad.sqf
Labels: Ready for merge, VN-development

#1937 deletes bak files
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf.bak
  A3-Antistasi/Templates/detector.sqf.bak
  A3-Antistasi/Templates/selector.sqf.bak
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf.bak
  A3-Antistasi/functions/Ammunition/fn_unlockEquipment.sqf.bak
  A3-Antistasi/functions/Base/fn_keys.sqf.bak
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf.bak
  A3-Antistasi/functions/Intel/fn_placeIntel.sqf.bak
  A3-Antistasi/functions/Supports/fn_SUP_gunshipAvailable.sqf.bak
  A3-Antistasi/functions/init/fn_initVarCommon.sqf.bak
Labels: VN-development, change

#1939 Multilingual Support: Completely refactored previous Simplified Chinese translation for vn-development branch
  A3-Antistasi/Stringtable.xml
Labels: Ready for merge, VN-development

#1948 Update fn_SUP_CASRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_CASRoutine.sqf
Labels: Bug-fix, Ready for merge

#1950 Add ACRE Items to Loot, Fix ACRE items unlocking/Stacking
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_addItem.sqf
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
  A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1947 Implement type-dependent classes for rebel AIs
  A3-Antistasi/functions/CREATE/fn_createUnit.sqf
  A3-Antistasi/functions/CREATE/fn_registerUnitType.sqf
  A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf
Labels: Review pending, VN-development, enhancement

#1953 Generalisation of hasVN to template variables.
  A3-Antistasi/Templates/NewTemplates/#Examples/CivilianExample.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TKM_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/FactionDefaults/CivilianDefaults.sqf
  A3-Antistasi/Templates/NewTemplates/FactionDefaults/EnemyDefaults.sqf
  A3-Antistasi/Templates/NewTemplates/FactionDefaults/RebelDefaults.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Civ.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_CIV.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_MACV.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_PAVN.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Civ.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions/AI/fn_askHelp.sqf
  A3-Antistasi/functions/AI/fn_undercoverAI.sqf
  A3-Antistasi/functions/Ammunition/fn_configSort.sqf
  A3-Antistasi/functions/Ammunition/fn_dress.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
  A3-Antistasi/functions/Ammunition/fn_itemSort.sqf
  A3-Antistasi/functions/Ammunition/fn_loot.sqf
  A3-Antistasi/functions/CREATE/fn_CIVinit.sqf
  A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf
  A3-Antistasi/functions/CREATE/fn_createUnit.sqf
  A3-Antistasi/functions/CREATE/fn_registerUnitType.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Intel/fn_getVehicleIntel.sqf
  A3-Antistasi/functions/Intel/fn_placeIntel.sqf
  A3-Antistasi/functions/REINF/fn_equipRebel.sqf
  A3-Antistasi/functions/REINF/fn_reDress.sqf
  A3-Antistasi/functions/Revive/fn_actionRevive.sqf
  A3-Antistasi/functions/Templates/Itemsets/fn_itemset_medicalSupplies.sqf
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
  A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf
  A3-Antistasi/functions/Templates/fn_loadFaction.sqf
  A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Ready for merge, Refactor, Review pending, VN-development, enhancement

#1955 Fix Other Support HandleDamage EHs
  A3-Antistasi/functions/Supports/fn_SUP_ASFRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_gunshipSpawn.sqf
Labels: Bug-fix, Ready for merge, VN-development

#1954 rename fn_compatabilityLoadFaction.sqf and update all references
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions/Templates/fn_compatibilityLoadFaction.sqf
Labels: Ready for merge, VN-development, change

#1826 WIP: Add ACRE2 items
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, enhancement

#1882 Update RHS_AI_AFRF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Temperate.sqf
Labels: Ready for merge

#1942 ↕ Moved the sale block checks lower.
  A3-Antistasi/functions/Base/fn_sellVehicle.sqf
Labels: Bug-fix, Ready for merge

#1951 set max civ amount for punishment-mission
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
Labels: Ready for merge, change

#1957 Fix refactor bug that caused vehicles to incorrectly lose undercover
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
Labels: Bug-fix, Ready for merge

#1865 Adjust spawn vehicle velocity for spawnVehicle
  A3-Antistasi/functions/CREATE/fn_spawnVehicle.sqf
Labels: Ready for merge, enhancement

#1881 Dynamic crewing for rebel garrison statics
  A3-Antistasi/REINF/addToGarrison.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_flagaction.sqf
  A3-Antistasi/functions/Base/fn_lockStatic.sqf
  A3-Antistasi/functions/Base/fn_unlockStatic.sqf
  A3-Antistasi/functions/Base/fn_updateRebelStatics.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/CREATE/fn_createSDKgarrisons.sqf
  A3-Antistasi/functions/CREATE/fn_createSDKgarrisonsTemp.sqf
  A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf
Labels: Ready for merge, enhancement

#1959 added a isLoadable check and implemented it in AIVehInit
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/Logistics/fn_logistics_isLoadable.sqf
Labels: Bug-fix, Ready for merge

#1966 Dressup simulator
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TKM_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Civ.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_CIV.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Civ.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
  A3-Antistasi/functions/Ammunition/fn_loot.sqf
  A3-Antistasi/functions/REINF/fn_equipRebel.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Ready for merge, change, enhancement

#1968 Improve logging on Bad spawns.
  A3-Antistasi/functions/CREATE/fn_cleanserVeh.sqf
Labels: Ready for merge, change, enhancement
