Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-07, with the labels that each got.

#1995 New issue forms
  .github/ISSUE_TEMPLATE/BugReportForm.yml
  .github/ISSUE_TEMPLATE/ChangeRequestForm.yml
  .github/ISSUE_TEMPLATE/FeatureRequestForm.yml
  .github/ISSUE_TEMPLATE/GameBalanceForm.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/change-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/game-balance.md
Labels: Ready for merge

#1987 Patch for bugs in unstable found during Testing Tuesday 29.jun
  A3-Antistasi/Garage/Core/fn_confirm.sqf
  A3-Antistasi/Garage/Core/fn_getCatIndex.sqf
  A3-Antistasi/Garage/Core/fn_onLoad.sqf
  A3-Antistasi/Garage/Core/fn_onUnload.sqf
  A3-Antistasi/Garage/Core/fn_reciveBroadcast.sqf
  A3-Antistasi/Garage/Core/fn_releaseAllVehicles.sqf
  A3-Antistasi/Garage/Core/fn_reloadCategory.sqf
  A3-Antistasi/Garage/Core/fn_reloadPreview.sqf
  A3-Antistasi/Garage/Core/fn_requestSelectionChange.sqf
  A3-Antistasi/Garage/Core/fn_toggleLock.sqf
  A3-Antistasi/Garage/Core/fn_validateGarage.sqf
  A3-Antistasi/Garage/Extras/fn_findMount.sqf
  A3-Antistasi/Garage/Extras/fn_isAmmoSource.sqf
  A3-Antistasi/Garage/Extras/fn_isFuelSource.sqf
  A3-Antistasi/Garage/Extras/fn_isRepairSource.sqf
  A3-Antistasi/Garage/Extras/fn_reloadExtras.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setAmmoData.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setDamage.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setFuel.sqf
  A3-Antistasi/Garage/config.inc
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/Garage/fn_addVehiclesByClass.sqf
  A3-Antistasi/Garage/fn_getSaveData.sqf
  A3-Antistasi/Garage/fn_initServer.sqf
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Logistics_Nodes.sqf
  A3-Antistasi/functions/AI/fn_chooseSupport.sqf
Labels: Bug-fix, Ready for merge

#1994 Vanilla Revive TFAR Mute Fix
  A3-Antistasi/functions/Revive/fn_unconscious.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1982 NVG Cleanup
  A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
Labels: Ready for merge, change, enhancement

#1999 [Garage] Add Static Weapons to staticsToSave
  A3-Antistasi/Garage/config.inc
Labels: Bug-fix, Ready for merge

#2000 Fix damage preservation and ltc refund
  A3-Antistasi/Garage/StatePreservation/fn_getDamage.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setDamage.sqf
  A3-Antistasi/Garage/fn_addVehicle.sqf
Labels: Bug-fix, Ready for merge

#2001 added null checks for logi unload
  A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
Labels: Bug-fix, Ready for merge

#2002 fixed wrong var name being used as target
  A3-Antistasi/functions/Supports/fn_SUP_CASRoutine.sqf
Labels: Bug-fix, Ready for merge

#2004 fix incorrect remoteExec target in AILoadInfo
  A3-Antistasi/functions/Base/fn_AILoadInfo.sqf
Labels: Bug-fix, Ready for merge

#2005 Member leash FF exemption and many improvements!
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Dialogs/fn_fastTravelRadio.sqf
  A3-Antistasi/functions/OrgPlayers/fn_playerLeash.sqf
  A3-Antistasi/functions/OrgPlayers/fn_playerLeashCheckPosition.sqf
  A3-Antistasi/functions/OrgPlayers/fn_playerLeashRefresh.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/orgPlayers/nonMemberDistance.sqf
Labels: Bug-fix, Ready for merge

#2007 🔧🛠 equipRebell give back their Tools 🛠🔧
  A3-Antistasi/functions/REINF/fn_equipRebel.sqf
Labels: Bug-fix, Ready for merge

#2008 🔫 ADR DLC Funnies 🔫
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf
  A3-Antistasi/functions/ModsAndDLC/fn_isModNameVanilla.sqf
  A3-Antistasi/functions/init/fn_initParams.sqf
Labels: Bug-fix, Ready for merge

#2010 Time Span Type
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/String/fn_pad_2Digits.sqf
  A3-Antistasi/functions/String/fn_pad_3Digits.sqf
  A3-Antistasi/functions/Time/fn_dateToTimeString.sqf
  A3-Antistasi/functions/Time/fn_secondsToTimeSpan.sqf
  A3-Antistasi/functions/Time/fn_systemTime_format_S.sqf
  A3-Antistasi/functions/Time/fn_timeSpan_format.sqf
  A3-Antistasi/functions/Utility/fn_systemTime_format_S.sqf
Labels: Ready for merge, enhancement

#2011 Added Time Span Since Last GC
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, enhancement

#2012 Fix Typo in MG Array (Nato_Temperate)
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
Labels: Bug-fix, Ready for merge

#2014 block garage access while in vehicle
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/Garage/fn_initGarage.sqf
  A3-Antistasi/Stringtable.xml
Labels: Bug-fix, Ready for merge

#2015 Fast Travel checks membership before leashCheck.
  A3-Antistasi/functions/Dialogs/fn_fastTravelRadio.sqf
Labels: Bug-fix, Ready for merge

#2017 [Garage] Blacklist ADE Camos
  A3-Antistasi/Garage/config.inc
Labels: Ready for merge, change

#2016 removed the middle man, made the refund synchronous
  A3-Antistasi/Garage/fn_addVehicle.sqf
Labels: Bug-fix, Ready for merge, enhancement

#2019 true localised garage hints
  A3-Antistasi/Garage/Core/fn_confirm.sqf
  A3-Antistasi/Garage/Extras/fn_findMount.sqf
  A3-Antistasi/Garage/Extras/fn_requestMount.sqf
  A3-Antistasi/Garage/config.inc
  A3-Antistasi/Garage/fn_addVehicle.sqf
Labels: Ready for merge, enhancement

#2020 added extra safety checks to prevent dupe
  A3-Antistasi/Garage/fn_addVehicle.sqf
Labels: Bug-fix, Ready for merge

#2022 unify persistent save hint title
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Ready for merge, change

#2023 Disable Problematic Ace Settings
  A3-Antistasi/cba_settings.sqf
Labels: Ready for merge, enhancement

#2024 Prevent converted Explosives from Unlocking
  A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
Labels: Bug-fix, Ready for merge

#2025 fixed a return case with nil
  A3-Antistasi/functions/Ammunition/fn_configSort.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3-Antistasi/functions/Ammunition/fn_launcherInfo.sqf
Labels: Bug-fix, Ready for merge
