Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-03, with the labels that each got.

#1732 Revert aggro improvements
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
Labels: Ready for merge

#1757 fix accumulating mass with deleted cargo
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf
Labels: Bug-fix, Ready for merge

#1759 Fix ace stamina disabling force walk while carrying LTC crate
  A3-Antistasi/functions/LTC/fn_carryCrate.sqf
Labels: Ready for merge, bug

#1762 Fix parameters not saving
  A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/init/fn_initParams.sqf
Labels: Bug-fix, Ready for merge

#1776 CS-1774-OneMillionGuns
  A3-Antistasi/MissionDescription/params.hpp
Labels: Ready for merge, change

#1775 CS-1773-NoEscapedLogStrings
  A3-Antistasi/functions/Utility/fn_log.sqf
Labels: Ready for merge, enhancement

#1780 CS-1772-log-AI-limit-spawn-distance
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Dialogs/fn_HQGameOptions.sqf
Labels: Ready for merge, enhancement

#1783 Allow commanders and admins to edit game options.
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions/Dialogs/fn_HQGameOptions.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: Ready for merge

#1784 Update all Current Templates
  A3-Antistasi/Templates/NewTemplates/#Examples/FactionExample.sqf
  A3-Antistasi/Templates/NewTemplates/#Examples/RebelExample.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arctic.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_SOV_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_Mix.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_West.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_POL_Arctic.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_POL_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_POL_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_SOV_Arctic.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_SOV_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_SOV_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_WEH_Arctic.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_WEH_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/IFA/IFA_AI_WEH_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/UNSUNG/Unsung_AI_NVA_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/UNSUNG/Unsung_AI_US_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_LDF_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
Labels: Project, Ready for merge

#1777 Log macros
  A3-Antistasi/Includes/LogMacros.inc
  A3-Antistasi/Includes/common.inc
  A3-Antistasi/Includes/includesBasics.txt
  A3-Antistasi/init.sqf
Labels: Ready for merge, change

#1785 Log macros LogLevel integration
  A3-Antistasi/Includes/LogMacros.inc
Labels: Ready for merge, enhancement

#1496 CS-1489-Pun_FFServerSide
  A3-Antistasi/REINF/controlHCsquad.sqf
  A3-Antistasi/REINF/controlunit.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Dialogs/fn_fastTravelRadio.sqf
  A3-Antistasi/functions/Punishment/fn_punishment.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_addActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_checkStatus.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataGet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataNamespace.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataRem.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_dataSet.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_notPlayer.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_notifyAdmin.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_release.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_removeActionForgive.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_client.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
  A3-Antistasi/functions/Utility/fn_getAdmin.sqf
Labels: Project, Review pending

#1781 Fixed paradrops, distances and unit counts
  A3-Antistasi/functions/AI/fn_airdrop.sqf
  A3-Antistasi/functions/CREATE/fn_createAttackVehicle.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
Labels: Review pending

#1631 Vehicle spawn and fill with template crew functions .
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_spawnVehiclePrecise.sqf
  A3-Antistasi/functions/Utility/fn_setPos.sqf
Labels: Ready for merge, enhancement

#1787 CS-NapalmReduceDetail
  A3-Antistasi/functions/AI/fn_napalmDamage.sqf
Labels: Ready for merge, performance

#1789 Reordered logs to main function
  A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf
  A3-Antistasi/functions/Base/fn_logPerformance.sqf
Labels: Ready for merge, Refactor

#1786 Damage does not log AI or Null
  A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
Labels: Ready for merge, change, enhancement

#1790 CS-spawnVehiclePresice-FixedAircraftDetection
  A3-Antistasi/functions/CREATE/fn_spawnVehiclePrecise.sqf
Labels: Bug-fix, Ready for merge

#1797 Fix Crew Selection for UAVsmall
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge

#1798 Rework paradrop function to work better
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_airdrop.sqf
  A3-Antistasi/functions/AI/fn_paradrop.sqf
  A3-Antistasi/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Missions/fn_attackHQ.sqf
Labels: Bug-fix, Ready for merge, Refactor, change, enhancement

#1800 Prevent arsenalManage errors on zero-cap or broken magazine configs
  A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf
Labels: Bug-fix, Ready for merge

#1801 Fix occasional divide-by-zero in AIReactOnKill
  A3-Antistasi/functions/AI/fn_AIreactOnKill.sqf
Labels: Bug-fix, Ready for merge

#1805 Fix-LTC-nonLocalBodiesDupe
  A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
Labels: Bug-fix

#1806 Wurzel template support fixes - side dependency
  A3-Antistasi/functions/Supports/fn_SUP_mortar.sqf
Labels: Bug-fix

#1810 Update System Mod detection to A3A Preset / TFAR Beta detection
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
  A3-Antistasi/Templates/NewTemplates/#Examples/RebelExample.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TKM_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/Templates/detector.sqf
  A3-Antistasi/functions/AI/fn_napalmDamage.sqf
  A3-Antistasi/functions/AI/fn_occupantInvaderUnitKilledEH.sqf
  A3-Antistasi/functions/Ammunition/fn_ACEpvpReDress.sqf
  A3-Antistasi/functions/Ammunition/fn_checkRadiosUnlocked.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
  A3-Antistasi/functions/Ammunition/fn_launcherInfo.sqf
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
  A3-Antistasi/functions/Base/fn_healAndRepair.sqf
  A3-Antistasi/functions/Base/fn_initPetros.sqf
  A3-Antistasi/functions/Base/fn_keys.sqf
  A3-Antistasi/functions/Base/fn_stripGearFromLoadout.sqf
  A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3-Antistasi/functions/Revive/fn_handleDamage.sqf
  A3-Antistasi/functions/Revive/fn_handleDamageAAF.sqf
  A3-Antistasi/functions/Revive/fn_unconscious.sqf
  A3-Antistasi/functions/Templates/Itemsets/fn_itemset_medicalSupplies.sqf
  A3-Antistasi/functions/Templates/Itemsets/fn_itemset_miscEssentials.sqf
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
  A3-Antistasi/functions/Templates/fn_getLoadout.sqf
  A3-Antistasi/functions/Templates/fn_ifaModCompat.sqf
  A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
  A3-Antistasi/functions/Undercover/fn_initUndercover.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix, Ready for merge, change

#1809 Prevent Petros from being added to Garrisons
  A3-Antistasi/REINF/addToGarrison.sqf
Labels: Bug-fix, Ready for merge
