Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-02, with the labels that each got.

#1684 Implementation of Sahrani as a new map
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/functions/init/fn_initGarrisons.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  A3-Antistasi/functions/init/fn_initZones.sqf
  Map-Templates/Antistasi-Sahrani.sara/Navigation/navgridsara.sqf
  Map-Templates/Antistasi-Sahrani.sara/Navigation/roadsDBsara.sqf
  Map-Templates/Antistasi-Sahrani.sara/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Sahrani.sara/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Sahrani.sara/description.ext
  Map-Templates/Antistasi-Sahrani.sara/mission.sqm
Labels: enhancement

#1669 MIE Phase 8.5.1 D3S Logistics Implementation
  A3-Antistasi/Templates/AddonVics/d3s_Civ.sqf
  A3-Antistasi/Templates/AddonVics/d3s_Logi_Nodes.sqf
  A3-Antistasi/Templates/selector.sqf
Labels: Project, Ready for merge, enhancement

#1687 Fixed typos in Stringtables & dialogs
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/dialogs.hpp
Labels: Bug-fix, Ready for merge

#1688 Gave default commander medic and engi, updated calls, added header
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/onPlayerRespawn.sqf
  A3-Antistasi/orgPlayers/unitTraits.sqf
Labels: Ready for merge, enhancement

#1683 Add Towing check for Garaging Vehicles
  A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
Labels: Bug-fix, Ready for merge

#1700 RDS Integration
  A3-Antistasi/Templates/AddonVics/rds_Civ.sqf
  A3-Antistasi/Templates/AddonVics/rds_Logi_Nodes.sqf
  A3-Antistasi/Templates/detector.sqf
  A3-Antistasi/Templates/selector.sqf
Labels: Ready for merge, enhancement

#1701 halfed recoil force for all static mounts
  A3-Antistasi/Templates/RHS/RHS_Logistics_Nodes.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Logistics_Nodes.sqf
Labels: Bug-fix, Ready for merge

#1681 added templated surrender crates and salvageCrate
  A3-Antistasi/Templates/3CB_Inv_Sov_Temp.sqf
  A3-Antistasi/Templates/3CB_Inv_TKM_Arid.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Arid.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf
  A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Arct.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Arid.sqf
  A3-Antistasi/Templates/IFA_Inv_SOV_Temp.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Arct.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Arid.sqf
  A3-Antistasi/Templates/IFA_Occ_WEH_Temp.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_FIA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_FIA_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_LDF_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_SDK_Tropical.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf
  A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf
  A3-Antistasi/Templates/RHS_Occ_USAF_Temp.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf
  A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf
  A3-Antistasi/Templates/Vanilla_Occ_NATO_Temp.sqf
  A3-Antistasi/functions/AI/fn_surrenderAction.sqf
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
  A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
  A3-Antistasi/functions/LTC/fn_carryCrate.sqf
  A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
  A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Salvage.sqf
  A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Review pending, change

#1689 Fixed Malden outpost_12 (Bad mission spawner)
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
Labels: Bug-fix, Ready for merge, change

#1702 Spring cleaning - remove snow script
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initSnowFall.sqf
  LICENSE
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/al_blow_objects.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/al_breath.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/al_check_pos.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/al_snow.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/al_trembling.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/al_unit_seeze.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/alias_hunt.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/alias_snowfall_SFX.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/cloud_drop.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/intens_sound.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/medium_fog.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/rem_breath.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/rotocol_client.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/rotocol_drop.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/rotocol_server.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/snow_breath.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/snow_drop.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/umblator.sqf
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/bcg_wind.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/lup_01.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/lup_02.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/lup_03.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/rafala_1.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/rafala_2.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/rafala_3.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/rafala_5.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/rafala_6.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/rafala_7.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/rafala_8.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tremurat_1.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tremurat_2.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tremurat_3.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tremurat_4.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tuse_1.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tuse_2.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tuse_3.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tuse_4.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tuse_5.ogg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/sound/tuse_6.ogg
Labels: change

#1707 Fix logi Mount Block
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
Labels: Bug-fix, Ready for merge

#1714 BLUFOR IS DEAD - LONG LIVE GREENFOR!!!!!
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Navigation/navGridAltis.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Navigation/roadsDBAltis.sqf
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Pictures/Mission/PIC.jpg
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/description.ext
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
Labels: change

#1711 Hr fix block towing off logistics cargo
  A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_toggleLock.sqf
Labels: Bug-fix, Ready for merge

#1710 Add 3CB Factions to 3CB Detection to Prevent Petros gone.
  A3-Antistasi/Templates/detector.sqf
Labels: Bug-fix

#1717 replaced heightmap with satellite
  Map-Templates/Antistasi-Altis.Altis/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Anizay.tem_anizay/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Kunduz.Kunduz/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Malden.Malden/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Sahrani.sara/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Stratis.Stratis/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-Virolahti.vt7/Pictures/Mission/whiteboard.jpg
  Map-Templates/Antistasi-WotP.Tanoa/Pictures/Mission/whiteboard.jpg
Labels: Ready for merge, change

#1722 Cs nav grid pp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Utility/fn_systemTime_format_G.sqf
  Tools/NavGridPP/Collections/Array/fn_array_deleteAts.sqf
  Tools/NavGridPP/Collections/Array/fn_array_displace.sqf
  Tools/NavGridPP/Collections/Array/fn_array_remIndices.sqf
  Tools/NavGridPP/Collections/Array/fn_array_toChunks.sqf
  Tools/NavGridPP/Collections/ID/ID_defines.hpp
  Tools/NavGridPP/Collections/ID/fn_ID_LArray.sqf
  Tools/NavGridPP/Collections/ID/fn_ID_LArray_isEqualTo.sqf
  Tools/NavGridPP/Collections/ID/fn_ID_init.sqf
  Tools/NavGridPP/Collections/Location/fn_location_init.sqf
  Tools/NavGridPP/Collections/Location/fn_location_new.sqf
  Tools/NavGridPP/Collections/Location/fn_location_serialiseAddress.sqf
  Tools/NavGridPP/Collections/NestLoc/doc_benchmarksGetSetRem.sqf
  Tools/NavGridPP/Collections/NestLoc/fn_nestLoc_get.sqf
  Tools/NavGridPP/Collections/NestLoc/fn_nestLoc_rem.sqf
  Tools/NavGridPP/Collections/NestLoc/fn_nestLoc_set.sqf
  Tools/NavGridPP/Collections/Serialisation/Primitives/fn_serialise_namespace.sqf
  Tools/NavGridPP/NG_importGUI.hpp
  Tools/NavGridPP/Please Read Me.md
  Tools/NavGridPP/description.ext
  Tools/NavGridPP/functions.hpp
  Tools/NavGridPP/functions/NavGridPP/fn_NG_check_conExists.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_check_oneWays.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_DBPosName_road.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_DBStruct_road.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navGridDB_navIslands.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navGrid_navIslands.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navIslands_navGrid.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navIslands_navGridDB.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_road_DBPosName.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_deleteAll.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_distanceBetweenTwoRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_dotOnRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_lineBetweenTwoRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_linesBetweenRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_fix_deadEnds.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_fix_oneWays.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_format_navGridDB.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_import.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_main.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_main_draw.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_simplify_conDupe.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_simplify_flat.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_simplify_junc.sqf
  Tools/NavGridPP/functions/UI/fn_customHint.sqf
  Tools/NavGridPP/functions/UI/fn_customHintDismiss.sqf
  Tools/NavGridPP/functions/UI/fn_customHintInit.sqf
  Tools/NavGridPP/functions/UI/fn_customHintRender.sqf
  Tools/NavGridPP/functions/UI/fn_shader_ratioToHex.sqf
  Tools/NavGridPP/functions/Utility/fn_log.sqf
  Tools/NavGridPP/functions/Utility/fn_systemTime_format_G.sqf
Labels: Ready for merge, enhancement, performance

#1697 🧭 Navigation Grid Node&Time Reduction
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Utility/fn_systemTime_format_G.sqf
  Tools/NavGridPP/Collections/Array/fn_array_deleteAts.sqf
  Tools/NavGridPP/Collections/Array/fn_array_displace.sqf
  Tools/NavGridPP/Collections/Array/fn_array_remIndices.sqf
  Tools/NavGridPP/Collections/Array/fn_array_toChunks.sqf
  Tools/NavGridPP/Collections/ID/ID_defines.hpp
  Tools/NavGridPP/Collections/ID/fn_ID_LArray.sqf
  Tools/NavGridPP/Collections/ID/fn_ID_LArray_isEqualTo.sqf
  Tools/NavGridPP/Collections/ID/fn_ID_init.sqf
  Tools/NavGridPP/Collections/Location/fn_location_init.sqf
  Tools/NavGridPP/Collections/Location/fn_location_new.sqf
  Tools/NavGridPP/Collections/Location/fn_location_serialiseAddress.sqf
  Tools/NavGridPP/Collections/NestLoc/doc_benchmarksGetSetRem.sqf
  Tools/NavGridPP/Collections/NestLoc/fn_nestLoc_get.sqf
  Tools/NavGridPP/Collections/NestLoc/fn_nestLoc_rem.sqf
  Tools/NavGridPP/Collections/NestLoc/fn_nestLoc_set.sqf
  Tools/NavGridPP/Collections/Serialisation/Primitives/fn_serialise_namespace.sqf
  Tools/NavGridPP/NG_importGUI.hpp
  Tools/NavGridPP/Please Read Me.md
  Tools/NavGridPP/description.ext
  Tools/NavGridPP/functions.hpp
  Tools/NavGridPP/functions/NavGridPP/fn_NG_check_conExists.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_check_oneWays.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_DBPosName_road.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_DBStruct_road.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navGridDB_navIslands.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navGrid_navIslands.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navIslands_navGrid.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_navIslands_navGridDB.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_convert_road_DBPosName.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_deleteAll.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_distanceBetweenTwoRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_dotOnRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_lineBetweenTwoRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_draw_linesBetweenRoads.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_fix_deadEnds.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_fix_oneWays.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_format_navGridDB.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_import.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_main.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_main_draw.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_simplify_conDupe.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_simplify_flat.sqf
  Tools/NavGridPP/functions/NavGridPP/fn_NG_simplify_junc.sqf
  Tools/NavGridPP/functions/UI/fn_customHint.sqf
  Tools/NavGridPP/functions/UI/fn_customHintDismiss.sqf
  Tools/NavGridPP/functions/UI/fn_customHintInit.sqf
  Tools/NavGridPP/functions/UI/fn_customHintRender.sqf
  Tools/NavGridPP/functions/UI/fn_shader_ratioToHex.sqf
  Tools/NavGridPP/functions/Utility/fn_log.sqf
  Tools/NavGridPP/functions/Utility/fn_systemTime_format_G.sqf
Labels: Ready for merge, enhancement, performance

#1726 Cs 1724 napalm player no UI d
  A3-Antistasi/functions/AI/fn_napalm.sqf
  A3-Antistasi/functions/AI/fn_napalmDamage.sqf
Labels: Bug-fix, enhancement

#1716 updated mission.sqm's
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Sahrani.sara/mission.sqm
  Map-Templates/Antistasi-Stratis.Stratis/mission.sqm
  Map-Templates/Antistasi-Takistan.takistan/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
  Map-Templates/Antistasi-Virolahti.vt7/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: Ready for merge, change

#1734 CrewTypes are now pulled from a lookup table.
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_crewTypeForVehicle.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/functions/init/fn_initVehClassToCrew.sqf
Labels: enhancement, performance

#1429 General parameter saving with individual overrides
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Ammunition/fn_crateLootParams.sqf
  A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf
  A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initParams.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, enhancement

#1736 Disabled SQF Validate, always returns valid.
  Tools/sqf_validate.py
Labels: Ready for merge, change

#1749 fix #1739 - default guard to treating the heli as there vehicle
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
Labels: Bug-fix, Ready for merge

#1748 fix - #1742 - added exit case for updateList
  A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
Labels: Bug-fix, Ready for merge

#1725 🔥 Napalm Checks that Player has UID
  A3-Antistasi/functions/AI/fn_napalm.sqf
  A3-Antistasi/functions/AI/fn_napalmDamage.sqf
Labels: Bug-fix, Ready for merge, enhancement
