Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-06, with the labels that each got.

#1969 Add Signal Smoke Grenades / FlagMarkers / Update Equipment
  A3-Antistasi/Templates/NewTemplates/#Examples/FactionExample.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arctic.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_SOV.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_US.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_Mix.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_West.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TKM_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_MACV.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_LDF_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/Templates/selector.sqf
Labels: Ready for merge, Review pending, change, enhancement

#1975 Restore missing aggro penalty for killing surrendered enemies
  A3-Antistasi/functions/AI/fn_occupantInvaderUnitKilledEH.sqf
Labels: Bug-fix, Ready for merge

#1977 fix perma lockout in resourceFIA
  A3-Antistasi/functions/Base/fn_resourcesFIA.sqf
Labels: Bug-fix, Ready for merge

#1971 Improve performance of distanceUnits
  A3-Antistasi/functions/Base/fn_distanceUnits.sqf
Labels: Ready for merge, performance

#1980 NavGrid update
  Map-Templates/Antistasi-Altis.Altis/Navigation/altisNavGrid.sqf
  Map-Templates/Antistasi-Anizay.tem_anizay/Navigation/tem_anizayNavGrid.sqf
  Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/Navigation/cam_lao_namNavGrid.sqf
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Navigation/chernarus_summerNavGrid.sqf
  Map-Templates/Antistasi-ChernarusWinter.Chernarus_Winter/Navigation/chernarus_winterNavGrid.sqf
  Map-Templates/Antistasi-Kunduz.Kunduz/Navigation/kunduzNavGrid.sqf
  Map-Templates/Antistasi-Livonia.Enoch/Navigation/enochNavGrid.sqf
  Map-Templates/Antistasi-Malden.Malden/Navigation/maldenNavGrid.sqf
  Map-Templates/Antistasi-Sahrani.sara/Navigation/saraNavGrid.sqf
  Map-Templates/Antistasi-Stratis.Stratis/Navigation/stratisNavGrid.sqf
  Map-Templates/Antistasi-Takistan.takistan/Navigation/takistanNavGrid.sqf
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Navigation/tembelanNavGrid.sqf
  Map-Templates/Antistasi-Virolahti.vt7/Navigation/vt7NavGrid.sqf
  Map-Templates/Antistasi-WotP.Tanoa/Navigation/tanoaNavGrid.sqf
Labels: Ready for merge, change

#1985 🩹fix a few errors that slipped in during garage review changes.
  A3-Antistasi/Garage/Core/fn_getCatIndex.sqf
  A3-Antistasi/Garage/Core/fn_onUnload.sqf
  A3-Antistasi/Garage/config.inc
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/functions/init/fn_initParams.sqf
Labels: Ready for merge

#1917 Convoy mission rework
  A3-Antistasi/FSMs/ConvoyTravel.fsm
  A3-Antistasi/FSMs/DriveAlongPath.fsm
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_canFight.sqf
  A3-Antistasi/functions/AI/fn_inmuneConvoy.sqf
  A3-Antistasi/functions/AI/fn_vehicleConvoyTravel.sqf
  A3-Antistasi/functions/Base/fn_findBasesForConvoy.sqf
  A3-Antistasi/functions/CREATE/fn_cargoSeats.sqf
  A3-Antistasi/functions/CREATE/fn_groupDespawner.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
  A3-Antistasi/functions/Pathfinding/fn_findPath.sqf
  A3-Antistasi/functions/Pathfinding/fn_findPosOnRoute.sqf
  A3-Antistasi/functions/Pathfinding/fn_getMarkerNavPoint.sqf
  A3-Antistasi/functions/Pathfinding/fn_loadNavGrid.sqf
  A3-Antistasi/functions/Pathfinding/fn_roadAStar.sqf
  A3-Antistasi/functions/Pathfinding/fn_roadConnPoint.sqf
Labels: Bug-fix, Ready for merge, change

#1962 Mitigate some issues with the airstrike supports
  A3-Antistasi/functions/AI/fn_chooseSupport.sqf
  A3-Antistasi/functions/Supports/fn_SUP_airstrike.sqf
  A3-Antistasi/functions/Supports/fn_SUP_airstrikeAvailable.sqf
  A3-Antistasi/functions/Supports/fn_SUP_airstrikeRoutine.sqf
  A3-Antistasi/functions/Supports/fn_showInterceptedSetupCall.sqf
  A3-Antistasi/functions/Supports/fn_showInterceptedSupportCall.sqf
Labels: Balance, Bug-fix, Ready for merge, change

#1973 Spawn-related optimization and bugfixes
  A3-Antistasi/functions/Base/fn_distance.sqf
  A3-Antistasi/functions/CREATE/fn_createAICities.sqf
  A3-Antistasi/functions/CREATE/fn_createCIV.sqf
  A3-Antistasi/functions/Revive/fn_actionRevive.sqf
Labels: Bug-fix, Ready for merge, change, performance

#1963 Fix partial distribution of controlsX
  A3-Antistasi/functions/init/fn_initGarrisons.sqf
Labels: Bug-fix, Ready for merge
