Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-10, with the labels that each got.

#2144 Quick fixes for degenerate behaviour in rebelAttack
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
Labels: change, Ready for merge

#2147 Reduce capture response delay time
  A3-Antistasi/functions/Base/fn_markerChange.sqf
Labels: change, Ready for merge

#2148 Prevent airborne troops from counting towards zoneCheck captures
  A3-Antistasi/functions/Base/fn_zoneCheck.sqf
Labels: Bug-fix, Ready for merge

#2149 Block exploit where commander could become permanently undercover
  A3-Antistasi/REINF/controlHCsquad.sqf
  A3-Antistasi/REINF/controlunit.sqf
Labels: Bug-fix, Ready for merge, Exploit

#2151 Fix multiple rebel squad/vehicle price bugs
  A3-Antistasi/REINF/dismissSquad.sqf
  A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf
  A3-Antistasi/functions/REINF/fn_spawnHCGroup.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge, Exploit

#2156 added clientid to remoteExec
  A3-Antistasi/Garage/fn_addVehicle.sqf
Labels: Bug-fix, Ready for merge

#2157 Fix lamp drop action after respawn and some related things
  A3-Antistasi/functions/Base/fn_flagaction.sqf
  A3-Antistasi/onPlayerRespawn.sqf
Labels: Bug-fix, change, Ready for merge

#2126 VN Template Update
  A3-Antistasi/Templates/NewTemplates/FactionDefaults/RebelDefaults.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_CIV.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_Logistics_Nodes.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_MACV.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_PAVN.sqf
  A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf
  A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
  A3-Antistasi/functions/Ammunition/fn_itemSort.sqf
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: change, Ready for merge, VN-development

#2158 Remove undercover on setup of ACE explosives
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: change, Ready for merge
