Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-04, with the labels that each got.

#1815 performance_logging_macros
  A3-Antistasi/Includes/performance.inc
Labels: Ready for merge, enhancement

#1788 Wurzel change prestige name and parameters
  A3-Antistasi/REINF/addToGarrison.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_captureX.sqf
  A3-Antistasi/functions/AI/fn_occupantInvaderUnitKilledEH.sqf
  A3-Antistasi/functions/Base/fn_addAggression.sqf
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_powerReorg.sqf
  A3-Antistasi/functions/Base/fn_prestige.sqf
  A3-Antistasi/functions/Base/fn_rebuildAssets.sqf
  A3-Antistasi/functions/CREATE/fn_CIVinit.sqf
  A3-Antistasi/functions/CREATE/fn_FIAinitBASES.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_vehKilledOrCaptured.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
  A3-Antistasi/functions/Missions/fn_AS_specOP.sqf
  A3-Antistasi/functions/Missions/fn_DES_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Bank.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_RES_Prisoners.sqf
  A3-Antistasi/functions/Missions/fn_RES_Refugees.sqf
  A3-Antistasi/functions/Missions/fn_attackHQ.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/REINF/fn_FIAinit.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Supports/fn_SUP_ASFRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_CASRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_QRFRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_airstrikeRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_mortarRoutine.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: Ready for merge

#1846 Update debug.hpp
  A3-Antistasi/MissionDescription/debug.hpp
Labels: change

#1832 Fix town markers not being placed on roads
  A3-Antistasi/functions/init/fn_initZones.sqf
Labels: Bug-fix, Ready for merge

#1833 Minor improvements to mission request
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
Labels: Bug-fix, Ready for merge, change

#1835 Fix adding rebel units to unspawned garrisons
  A3-Antistasi/REINF/addToGarrison.sqf
Labels: Bug-fix, Ready for merge

#1837 Fix rebel city garrisons not spawning
  A3-Antistasi/functions/Base/fn_distance.sqf
Labels: Bug-fix

#1849 Add 3CB Factions Boat nodes.
  A3-Antistasi/Templates/NewTemplates/3CB/3CBFactions_Logistics_Nodes.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_Logistics_Nodes.sqf
Labels: Bug-fix, Ready for merge

#1847 Add Factions Mortar HE ammo / BAF Template remove Cargo Trucks
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arctic.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Temperate.sqf
  A3-Antistasi/functions/Supports/fn_SUP_mortar.sqf
  A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Review pending

#1802 Fix incorrect variable name in unlockEquipment logging
  A3-Antistasi/functions/Ammunition/fn_unlockEquipment.sqf
Labels: Bug-fix, Ready for merge

#1850 Logging serialisation warning hotfix. Format unified with macro.
  A3-Antistasi/functions/Utility/fn_log.sqf
Labels: Bug-fix, Ready for merge, enhancement

#1820 Disable incorrect icon-colouring code in vehicle arsenal
  A3-Antistasi/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
Labels: Bug-fix, Ready for merge

#1851 Fix NatoUnarmed Loadout
  A3-Antistasi/Templates/NewTemplates/#Examples/FactionExample.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arctic.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_SOV.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_US.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_West.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_LDF_Enoch.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix

#1853 Remove Vanilla Weapons from Punishment/Change weapon selection on INV Punishment
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
Labels: Ready for merge, change, enhancement

#1856 Disable Gunship on everything exept vanilla
  A3-Antistasi/functions/Supports/fn_SUP_gunshipAvailable.sqf
Labels: Bug-fix, Ready for merge

#1857 should exitWith if it found an outpost
  A3-Antistasi/functions/Supports/fn_SUP_QRFAvailable.sqf
Labels: Bug-fix, Ready for merge

#1858 Fixed orbital strikes deleting HQ assets
  A3-Antistasi/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
Labels: Bug-fix

#1860 Switch to using setPosWorld/getPosWorld for saved vehicle positions
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Bug-fix, Ready for merge, change

#1862 Fix createVehicleCrew leader selection
  A3-Antistasi/functions/CREATE/fn_createVehicleCrew.sqf
Labels: Bug-fix

#1870 Set initial airstrike aircraft velocity to reasonable value
  A3-Antistasi/functions/Supports/fn_SUP_airstrikeRoutine.sqf
Labels: Bug-fix, Ready for merge, change

#1871 Fix setWaypointStatements calls from support system
  A3-Antistasi/functions/AI/fn_combatLanding.sqf
  A3-Antistasi/functions/AI/fn_fastrope.sqf
  A3-Antistasi/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3-Antistasi/functions/Supports/fn_SUP_ASFRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_CASRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_airstrikeRoutine.sqf
  A3-Antistasi/functions/Supports/fn_SUP_gunshipRoutineCSAT.sqf
  A3-Antistasi/functions/Supports/fn_SUP_gunshipRoutineNATO.sqf
Labels: Bug-fix, Ready for merge

#1872 Separate task types from IDs to fix multiple task bugs
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Ammunition/fn_transfer.sqf
  A3-Antistasi/functions/Base/fn_createOutpostsFIA.sqf
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_outpostDialog.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Convoy/fn_createAIAction.sqf
  A3-Antistasi/functions/Dialogs/fn_mineDialog.sqf
  A3-Antistasi/functions/Dialogs/fn_skiptime.sqf
  A3-Antistasi/functions/Intel/fn_selectIntel.sqf
  A3-Antistasi/functions/Missions/fn_AS_Official.sqf
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
  A3-Antistasi/functions/Missions/fn_AS_specOP.sqf
  A3-Antistasi/functions/Missions/fn_CON_Outpost.sqf
  A3-Antistasi/functions/Missions/fn_DES_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
  A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Ammo.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Bank.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Salvage.sqf
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf
  A3-Antistasi/functions/Missions/fn_RES_Prisoners.sqf
  A3-Antistasi/functions/Missions/fn_RES_Refugees.sqf
  A3-Antistasi/functions/Missions/fn_attackHQ.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/Missions/fn_deleteTask.sqf
  A3-Antistasi/functions/Missions/fn_missionRequest.sqf
  A3-Antistasi/functions/Missions/fn_taskDelete.sqf
  A3-Antistasi/functions/Missions/fn_taskSetState.sqf
  A3-Antistasi/functions/Missions/fn_taskUpdate.sqf
  A3-Antistasi/functions/REINF/fn_buildMinefield.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: Bug-fix, Ready for merge

#1874 Remove Ace interaction from Arsenal (BoxX)
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: Bug-fix, Ready for merge, Review pending

#1878 Fix description.ext for Sahrani, Takistan and Chernarus Winter
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext
  Map-Templates/Antistasi-Sahrani.sara/description.ext
  Map-Templates/Antistasi-Takistan.takistan/description.ext
Labels: Bug-fix, Ready for merge

#1880 Fix Ace without Medical for Ai (Equipment)
  A3-Antistasi/functions/Templates/Itemsets/fn_itemset_medicalSupplies.sqf
Labels: Bug-fix, Ready for merge

#1883 Fix various locality and JIP problems with prisoner and refugee missions
  A3-Antistasi/functions/AI/fn_liberatePOW.sqf
  A3-Antistasi/functions/AI/fn_liberaterefugee.sqf
  A3-Antistasi/functions/Missions/fn_RES_Prisoners.sqf
  A3-Antistasi/functions/Missions/fn_RES_Refugees.sqf
Labels: Bug-fix, Ready for merge

#1875 Log improvements
  A3-Antistasi/Includes/LogMacros.inc
Labels: Ready for merge, enhancement

#1884 Getting rid of / deactivating PvP
  A3-Antistasi/MissionDescription/gameSettings.hpp
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions/init/fn_initParams.sqf
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
  Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm
  Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
  Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
  Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
  Map-Templates/Antistasi-Malden.Malden/mission.sqm
  Map-Templates/Antistasi-Sahrani.sara/mission.sqm
  Map-Templates/Antistasi-Stratis.Stratis/mission.sqm
  Map-Templates/Antistasi-Takistan.takistan/mission.sqm
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
  Map-Templates/Antistasi-Virolahti.vt7/mission.sqm
  Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Labels: Ready for merge, change

#1839 CfgRemoteExec Allow All for BE.
  A3-Antistasi/MissionDescription/CfgRemoteExec.hpp
  A3-Antistasi/MissionDescription/master.hpp
Labels: Ready for merge, enhancement

#1886 Fix not Matching Attachment
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_SOV.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf
  A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_Mix.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
Labels: Bug-fix, Ready for merge

#1887 Synchronize vehicle textures so that everyone sees the same colour
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/Utility/fn_vehicleTextureSync.sqf
Labels: Bug-fix, Ready for merge

#1888 Silence Sanity checks RPT spam
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix

#1890 fixed arty trail eh missing _fn, breaking it from being picked up by …
  A3-Antistasi/functions/EventHandler/fn_addArtilleryTrailEH.sqf
Labels: Bug-fix, Priority, Ready for merge

#1892 Fix safeVehicleSpawn to spawn air vehicles in the air
  A3-Antistasi/functions/CREATE/fn_safeVehicleSpawn.sqf
Labels: Bug-fix, Ready for merge

#1893 Fix QRF APCs and transport aircraft using the wrong behaviour
  A3-Antistasi/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
Labels: Bug-fix, Ready for merge
