Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-09, with the labels that each got.

#2081 Log improvements
  A3-Antistasi/Includes/LogMacros.inc
  A3-Antistasi/functions/AI/fn_vehicleConvoyTravel.sqf
  A3-Antistasi/functions/CREATE/fn_cycleSpawn.sqf
  A3-Antistasi/functions/CREATE/fn_freeSpawnPositions.sqf
  A3-Antistasi/functions/CREATE/fn_milBuildings.sqf
  A3-Antistasi/functions/Convoy/fn_createAIAction.sqf
  A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf
  A3-Antistasi/functions/Garrison/fn_createGarrison.sqf
  A3-Antistasi/functions/Intel/fn_placeIntel.sqf
  A3-Antistasi/functions/Utility/fn_localLog.sqf
  A3-Antistasi/functions/init/fn_prepareMarkerArrays.sqf
Labels: Bug-fix, enhancement, Ready for merge

#2100 Fixed inability to put vehicles into garage when player host of listen server is inside vehicle
  A3-Antistasi/Garage/fn_addVehicle.sqf
Labels: Bug-fix, Ready for merge

#2102 Make singleAttack and patrolReinf log to server
  A3-Antistasi/functions/CREATE/fn_createAttackVehicle.sqf
  A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf
  A3-Antistasi/functions/CREATE/fn_singleAttack.sqf
Labels: Bug-fix, Ready for merge

#2103 Fix fastrope spawning corpses underground after heli crash
  A3-Antistasi/functions/AI/fn_fastrope.sqf
Labels: Bug-fix, Ready for merge

#2105 Fix allowCrewInImmobile not being applied correctly to convoy vehicles
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/functions/init/fn_initVehClassToCrew.sqf
Labels: Bug-fix, Ready for merge

#2106 Save all vehicle pool entries that are incremented by economicsAI
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Bug-fix, Ready for merge

#2107 Garage limit garaging and state preservation at hq
  A3-Antistasi/Garage/StatePreservation/fn_setAmmoData.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setFuel.sqf
  A3-Antistasi/Garage/StatePreservation/fn_setState.sqf
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: change, Ready for merge, Balance, Exploit

#2108 Made HC squads vehicle placement use the garage placement
  A3-Antistasi/Garage/Core/fn_confirm.sqf
  A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
  A3-Antistasi/Garage/fn_callbackHandler.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf
  A3-Antistasi/functions/REINF/fn_addFIAveh.sqf
  A3-Antistasi/functions/REINF/fn_build.sqf
  A3-Antistasi/functions/REINF/fn_spawnHCGroup.sqf
  Map-Templates/Antistasi-Altis.Altis/mission.sqm
Labels: change, enhancement, Ready for merge

#2109 Fixed carry object carrying an object that is not the object you want to carry.
  A3-Antistasi/functions/UtilityItems/fn_carryItem.sqf
  A3-Antistasi/functions/UtilityItems/fn_initMovableObject.sqf
  A3-Antistasi/functions/UtilityItems/fn_rotateItem.sqf
Labels: Bug-fix, Ready for merge

#2111 Give Petros a Vest
  A3-Antistasi/functions/Base/fn_initPetros.sqf
Labels: change, Ready for merge

#2119 Quick rework of punishment attacks
  A3-Antistasi/functions/Base/fn_distance.sqf
  A3-Antistasi/functions/Base/fn_mrkUpdate.sqf
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: Bug-fix, change, enhancement, Ready for merge, Balance

#2120 More parameters explanation
  A3-Antistasi/MissionDescription/params.hpp
Labels: change, Ready for merge

#2125 Minor mortar fixes
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/CREATE/fn_createSDKgarrisons.sqf
  A3-Antistasi/functions/EventHandler/fn_addArtilleryDetectionEH.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge, Merge conflicts

#2127 Fix zero-divisor bug in minefield saving
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
Labels: Bug-fix, Ready for merge

#2110 Improve scaling, fix bugs and add logging in economicsAI
  A3-Antistasi/functions/Base/fn_economicsAI.sqf
  A3-Antistasi/functions/CREATE/fn_vehKilledOrCaptured.sqf
Labels: Bug-fix, Ready for merge, Balance

#2112 Change civ detection to city+house detection
  A3-Antistasi/functions/AI/fn_chooseSupport.sqf
Labels: change, Ready for merge, Balance

#2116 Prevent simulated attacks from massively overfilling garrisons
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
Labels: change, performance, Ready for merge, Balance

#2124 Quick player-count balance for QRF/singleAttack/wavedCA
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Base/fn_economicsAI.sqf
  A3-Antistasi/functions/Base/fn_getPlayerScale.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/CREATE/fn_singleAttack.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
  A3-Antistasi/functions/Supports/fn_SUP_QRF.sqf
Labels: Ready for merge, Balance

#2121 Rebalance reinforcements, plus related tweaks
  A3-Antistasi/functions/Base/fn_markerChange.sqf
  A3-Antistasi/functions/CREATE/fn_garrisonSize.sqf
  A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
  A3-Antistasi/functions/Templates/fn_compatibilityLoadFaction.sqf
  A3-Antistasi/functions/init/fn_initGarrisons.sqf
Labels: Bug-fix, change, Review pending, Balance

#2135 Fix incorrect attack countdown incrementing + extras
  A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf
  A3-Antistasi/functions/Base/fn_rebelAttack.sqf
  A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
Labels: Bug-fix, change, Ready for merge, Balance

#2136 Make hard/easy difficulty changes less extreme for some cases
  A3-Antistasi/functions/CREATE/fn_NATOinit.sqf
Labels: change, Ready for merge, Balance

#2137 fixed white space issue with log processing
  A3-Antistasi/Includes/LogMacros.inc
Labels: Bug-fix, Ready for merge

#2141 Fix bad exitWith in resourceCheck causing incorrect losses
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: Bug-fix, Ready for merge

#2143 Fix singleAttack early-exit logging
  A3-Antistasi/functions/CREATE/fn_singleAttack.sqf
Labels: Bug-fix, Ready for merge
