Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-01, with the labels that each got.

#1634 Updated discord link as old one was deleted.
  README.md
Labels: Bug-fix

#1404 MIE Phase 8 Add ADV Support (Again)
  A3-Antistasi/Templates/detector.sqf
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
Labels: enhancement

#1638 Meer MIE phase 6.5 - SDKAA (Moved from Phase 8)
  A3-Antistasi/Templates/3CB/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/AddonVics/tcgm_Civ.sqf
  A3-Antistasi/Templates/Example/Example_Reb.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_HIDF_Arid.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_HIDF_Temp.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_NAPA_Temp.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/Templates/detector.sqf
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Change Requested, Project, change

#1630 Fix dupe with LTC leftovers
  A3-Antistasi/functions/LTC/fn_canLoot.sqf
  A3-Antistasi/functions/LTC/fn_canTransfer.sqf
  A3-Antistasi/functions/LTC/fn_carryCrate.sqf
  A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
  A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
  A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
  A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
Labels: Bug-fix, Ready for merge

#1649 Bug-fix #97
  A3-Antistasi/functions/AI/fn_canConquer.sqf
  A3-Antistasi/functions/AI/fn_canFight.sqf
Labels: Bug-fix, Ready for merge

#1637 Common Description.ext contents moved to MissionDescription
  A3-Antistasi/MissionDescription/CfgDebriefingContents.hpp
  A3-Antistasi/MissionDescription/CfgFunctionsContents.hpp
  A3-Antistasi/MissionDescription/CfgSoundsContents.hpp
  A3-Antistasi/MissionDescription/master.hpp
  Map-Templates/Antistasi-Altis-BLUFOR.Altis/description.ext
  Map-Templates/Antistasi-Altis.Altis/description.ext
  Map-Templates/Antistasi-Anizay.tem_anizay/description.ext
  Map-Templates/Antistasi-Chernarus.chernarus_summer/description.ext
  Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext
  Map-Templates/Antistasi-Kunduz.Kunduz/description.ext
  Map-Templates/Antistasi-Livonia.Enoch/description.ext
  Map-Templates/Antistasi-Malden.Malden/description.ext
  Map-Templates/Antistasi-Stratis.Stratis/description.ext
  Map-Templates/Antistasi-Takistan.takistan/description.ext
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/description.ext
  Map-Templates/Antistasi-Virolahti.vt7/description.ext
  Map-Templates/Antistasi-WotP.Tanoa/description.ext
Labels: Ready for merge, Refactor, enhancement

#1643 distance refactoring and fix
  A3-Antistasi/functions/Base/fn_distance.sqf
Labels: Bug-fix, Ready for merge

#1588 New jnl
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_surrenderAction.sqf
  A3-Antistasi/functions/Base/fn_flagaction.sqf
  A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
  A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
  A3-Antistasi/functions/CREATE/fn_createAISite.sqf
  A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
  A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
  A3-Antistasi/functions/Logistics/fn_logistics_getVehCapacity.sqf
  A3-Antistasi/functions/Logistics/fn_logistics_initNodes.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_canLoad.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_generateHardPoints.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_getCargoNodeType.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_getCargoOffsetAndDir.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_getVehicleNodes.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_initMountedWeapon.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_refreshVehicleLoad.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_toggleAceActions.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_toggleLock.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_tryLoad.sqf
  A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
  A3-Antistasi/functions/Logistics/howToAddStuffToLogistics.txt
  A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
  A3-Antistasi/functions/Revive/fn_unconscious.sqf
  A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initFuncs.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, change, enhancement

#1663 newJNL - MIE integration
  A3-Antistasi/Templates/3CB/3CB_JNL_Nodes.sqf
  A3-Antistasi/Templates/3CB/3CB_Logistics_Nodes.sqf
  A3-Antistasi/Templates/Example/Example_Logistics_Nodes.sqf
  A3-Antistasi/Templates/FFAA/FFAA_JNL_Nodes.sqf
  A3-Antistasi/Templates/FFAA/FFAA_Logistics_Nodes.sqf
  A3-Antistasi/Templates/IFA/IFA_JNL_Nodes.sqf
  A3-Antistasi/Templates/IFA/IFA_Logistics_Nodes.sqf
  A3-Antistasi/Templates/RHS/RHS_JNL_Nodes.sqf
  A3-Antistasi/Templates/RHS/RHS_Logistics_Nodes.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_JNL_Nodes.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Logistics_Nodes.sqf
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Logistics/fn_logistics_initNodes.sqf
  A3-Antistasi/functions/Utility/fn_classNameToModel.sqf
  A3-Antistasi/functions/init/fn_initFuncs.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
Labels: Ready for merge, change

#1639 Meer MIE phase 8.5 D3S
  A3-Antistasi/Templates/AddonVics/d3s_Civ.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_HIDF_Temp.sqf
  A3-Antistasi/Templates/detector.sqf
  A3-Antistasi/Templates/selector.sqf
Labels: Project, Ready for merge, enhancement

#1653 Meer MIE phase 6.5 - SDKAA (Moved from Phase 8) ((Re:#1638))
  A3-Antistasi/Templates/3CB/3CB_JNL_Nodes.sqf
  A3-Antistasi/Templates/3CB/3CB_Logistics_Nodes.sqf
  A3-Antistasi/Templates/3CB/3CB_Reb_CNM_Temp.sqf
  A3-Antistasi/Templates/3CB/3CB_Reb_CNM_Trop.sqf
  A3-Antistasi/Templates/3CB/3CB_Reb_TPGM_Arid.sqf
  A3-Antistasi/Templates/3CB/3CB_Reb_TTF_Arid.sqf
  A3-Antistasi/Templates/AddonVics/d3s_Civ.sqf
  A3-Antistasi/Templates/AddonVics/tcgm_Civ.sqf
  A3-Antistasi/Templates/Example/Example_Logistics_Nodes.sqf
  A3-Antistasi/Templates/Example/Example_Reb.sqf
  A3-Antistasi/Templates/FFAA/FFAA_JNL_Nodes.sqf
  A3-Antistasi/Templates/FFAA/FFAA_Logistics_Nodes.sqf
  A3-Antistasi/Templates/IFA/IFA_JNL_Nodes.sqf
  A3-Antistasi/Templates/IFA/IFA_Logistics_Nodes.sqf
  A3-Antistasi/Templates/RHS/RHS_JNL_Nodes.sqf
  A3-Antistasi/Templates/RHS/RHS_Logistics_Nodes.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_HIDF_Arid.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_HIDF_Temp.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/RHS/RHS_Reb_NAPA_Temp.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_JNL_Nodes.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Logistics_Nodes.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_FIA_Altis.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_FIA_B_Altis.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/Templates/detector.sqf
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Logistics/fn_logistics_initNodes.sqf
  A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
  A3-Antistasi/functions/Utility/fn_classNameToModel.sqf
  A3-Antistasi/functions/init/fn_initFuncs.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Project, Ready for merge, change

#1642 overhauled napalm, particle animation by ArtemisGodfrey, backend by CalebSerafin
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_airbomb.sqf
  A3-Antistasi/functions/AI/fn_airstrike.sqf
  A3-Antistasi/functions/AI/fn_napalm.sqf
  A3-Antistasi/functions/AI/fn_napalmDamage.sqf
  A3-Antistasi/functions/AI/fn_napalmParticles.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, change, enhancement

#1664 Napalm overhaul 1641 Minor bug fixes
  A3-Antistasi/functions/AI/fn_napalm.sqf
  A3-Antistasi/functions/AI/fn_napalmDamage.sqf
Labels: Bug-fix, Ready for merge

#1646 Bug-fix #1648 Script error in the function A3A_fnc_createCIV
  A3-Antistasi/functions/CREATE/fn_createCIV.sqf
Labels: Bug-fix, Ready for merge

#1662 Bug-fix Issue #1567 HQ can sell Petros
  A3-Antistasi/REINF/dismissPlayerGroup.sqf
  A3-Antistasi/REINF/dismissSquad.sqf
Labels: Bug-fix, Ready for merge

#1668 Disable ability to select and play from SP scenario menu
  A3-Antistasi/MissionDescription/master.hpp
Labels: Ready for merge, Singleplayer, change

#1671 Removed Start-up Shenanigans
  A3-Antistasi/dialogs.hpp
  A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
  A3-Antistasi/functions/UI/fn_customHintRender.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Ready for merge, change, enhancement

#1673 Optimised mission root path parsing
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/AI/fn_guardDog.sqf
  A3-Antistasi/functions/init/fn_initGetMissionPath.sqf
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: Ready for merge, Refactor, performance

#1622 Enable Airstrike conversion for Airfields / Update a few Hints
  A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
  A3-Antistasi/functions/REINF/fn_addBombRun.sqf
Labels: Ready for merge, change, enhancement

#1661 refactoring fn_typeOfSoldier.sqf
  A3-Antistasi/functions/AI/fn_typeOfSoldier.sqf
Labels: Ready for merge, Refactor

#1666 Fixed multiple Arsenal duplication exploits
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
  A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_cargoToArsenal.sqf
  A3-Antistasi/functions/Ammunition/fn_ammunitionTransfer.sqf
Labels: Bug-fix, Exploit, Ready for merge

#1674 block attempt to transfer to loot to destroyed vehicle
  A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
Labels: Bug-fix, Ready for merge

#1680 Added ACE turret wrecks to garbage clean
  A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
Labels: Ready for merge, good first issue

#1682 Removed old RoadsX vars
  A3-Antistasi/functions/init/fn_initVarCommon.sqf
Labels: change
