Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2021-11, with the labels that each got.

#2178 Add Ace Food and Drink Items + Parameter
  A3-Antistasi/MissionDescription/params.hpp
  A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
  A3-Antistasi/functions/init/fn_initParams.sqf
Labels: enhancement, Ready for merge

#2185 fix incorrectly using mixed pool of occ and inv for AI arport creatio…
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
Labels: Ready for merge

#2188 Fixed script errors in 3CB and #Example templates
  A3-Antistasi/Templates/Templates/#Examples/Example_Logistics_Nodes.sqf
  A3-Antistasi/Templates/Templates/3CB/3CB_AI_BAF_Arid.sqf
  A3-Antistasi/Templates/Templates/3CB/3CB_AI_BAF_Temperate.sqf
Labels: Bug-fix, Ready for merge

#2186 ♻ KeyCache-Garbage Collector
  A3-Antistasi/MissionDescription/CfgRemoteExec.hpp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Utility/KeyCache/Tests/readme.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTestUtility_revertInit.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTestUtility_revertStartGarbageCollectors.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_basicDeletion.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_basicPromotion.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_longFpsStressTest.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_shortFpsStressTest.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_timedPromotion.sqf
  A3-Antistasi/functions/Utility/KeyCache/config.hpp
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_delete.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_garbageCollector.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_has.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_init.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_lookup.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_registerForGC.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_set.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_startGarbageCollectors.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_translate.sqf
Labels: performance, Ready for merge

#2182 initZones Refactor
  A3-Antistasi/Templates/selector.sqf
  A3-Antistasi/functions/AI/fn_combatLanding.sqf
  A3-Antistasi/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
  A3-Antistasi/functions/init/fn_initGarrisons.sqf
  A3-Antistasi/functions/init/fn_initZones.sqf
  Map-Templates/Antistasi-Altis.Altis/Map/altisInfo.sqf
  Map-Templates/Antistasi-Anizay.tem_anizay/Map/tem_anizayInfo.sqf
  Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/Map/cam_lao_namInfo.sqf
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Map/chernarus_summerInfo.sqf
  Map-Templates/Antistasi-ChernarusWinter.Chernarus_Winter/Map/chernarus_winterInfo.sqf
  Map-Templates/Antistasi-Kunduz.Kunduz/Map/kunduzInfo.sqf
  Map-Templates/Antistasi-Livonia.Enoch/Map/enochInfo.sqf
  Map-Templates/Antistasi-Malden.Malden/Map/maldenInfo.sqf
  Map-Templates/Antistasi-Sahrani.sara/Map/saraInfo.sqf
  Map-Templates/Antistasi-Stratis.Stratis/Map/stratisInfo.sqf
  Map-Templates/Antistasi-Takistan.takistan/Map/takistanInfo.sqf
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Map/tembelanInfo.sqf
  Map-Templates/Antistasi-Virolahti.vt7/Map/vt7Info.sqf
  Map-Templates/Antistasi-WotP.Tanoa/Map/tanoaInfo.sqf
Labels: Ready for merge

#2194 Fix leftover bugs from #2047
  A3-Antistasi/Templates/Templates/VN/VN_MACV.sqf
  A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
Labels: Bug-fix, Ready for merge
