Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-12, with the labels that each got.

#2564 Fix darkMapFix whiteout after alt-tab
  A3A/addons/core/functions/ModsAndDLC/fn_darkMapFix.sqf
Labels: Bug-fix, Ready for merge

#2570 Added version number to the bikey generation
  Tools/Builder/buildAddons.ps1
Labels: Ready for merge, CI\CD

#2571 Texture path fix for setObjectTextureGlobal
  A3A/addons/core/functions/Intel/fn_searchIntelOnLaptop.sqf
Labels: Bug-fix, Ready for merge

#2576 Polish translation update
  A3A/addons/GUI/Stringtable.xml
  A3A/addons/Garage/Stringtable.xml
  A3A/addons/core/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
Labels: localisation

#2573 Fix CUP police weapons
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_SLA_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf
Labels: Bug-fix, Ready for merge

#2569 Make garaged utility items refund to faction money
  A3A/addons/Garage/Public/fn_addVehicle.sqf
Labels: bug, Ready for merge, Exploit

#2505 Vehicle Box restoration
  A3A/addons/Events/Events.hpp
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_vehicleBoxHeal.sqf
  A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Ready for merge

#2578 createVehicle fix for REP_Antenna
  A3A/addons/core/functions/Missions/fn_REP_Antenna.sqf
Labels: Bug-fix, Ready for merge

#2577 Fix bug where guests could take limited magazines by loading a loadout
  A3A/addons/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
Labels: Bug-fix, Ready for merge

#2580 Move buy GUI out of dev state
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Dialogs/fn_buyVehicle.sqf
  A3A/addons/core/functions/Dialogs/fn_buyVehicleCiv.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: change, Review pending

#2581 Fix guest commander leash issues
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/core/functions/OrgPlayers/fn_playerLeash.sqf
  A3A/addons/core/functions/OrgPlayers/fn_playerLeashCheckPosition.sqf
Labels: Bug-fix, Ready for merge

#2582 Campaign ID check and logging
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug-fix, enhancement, Ready for merge

#2583 Remove UAVs from garbage collection
  A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
Labels: change, Ready for merge

#2584 moves assets further from road on vt7_outpost_10
  A3A/addons/maps/Antistasi_vt7.vt7/mission.sqm
Labels: change, Map Issue

#2567 version update and preliminary changelog for 3.0.0
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/Params.hpp
  changelog.rst
Labels: Review pending

#2591 Fix Face-Voice Typo in CUP Templates
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
Labels: Bug-fix, Review pending

#2592 Force Ace Captives settings to prevent silly Exploits
  A3A/addons/core/Includes/cba_settings.sqf
Labels: change, enhancement, Exploit

#2594 Fix intel desks hanging in air after building destruction
  A3A/addons/core/functions/Intel/fn_placeIntel.sqf
Labels: Bug-fix

#2597 lazy evaluation for LTC
  A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
Labels: enhancement

#2599 KAT medical update
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
Labels: enhancement
