Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-03, with the labels that each got.

#2270 moved garage initServer to postInit
  A3A/addons/Garage/CfgFunctions.hpp
  A3A/addons/core/functions/init/fn_initPreJIP.sqf
Labels: Bug-fix, Ready for merge

#2267 Refactor vehicle arsenal magazine selection, fix case sensitivity issue
  A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
Labels: Bug-fix, Refactor, Ready for merge

#2273 Switch back to moving recruited rebel squads into their vehicles
  A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
Labels: change, Ready for merge

#2276 Remove Ravenbackpack from Loot
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
Labels: change, Ready for merge

#2277 Templates - Added check for Ace Extra Gear
  A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ADA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ANA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_SOV.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_US.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_HIDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_MDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_East.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_Mix.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_West.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
Labels: Bug-fix, change, Ready for merge

#2280 Vehicle Arsenal - Ability to take more at once
  A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf
  A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
Labels: change, enhancement, Ready for merge

#2283 Fix Carrier Markertype after loading a Save
  A3A/addons/core/functions/init/fn_initGarrisons.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge

#2278 Update BAF Templates
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arctic.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Tropical.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_POL_Arctic.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_POL_Arid.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_POL_Temperate.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV_Arctic.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV_Arid.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV_Temperate.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Arctic.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Arid.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Temperate.sqf
  A3A/addons/core/Templates/Templates/VN/VN_MACV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_PAVN.sqf
Labels: Bug-fix, change, Ready for merge

#2239 ☕ New cup templates
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_SLA_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Civ.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NPC_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKL_Arid.sqf
  A3A/addons/core/Templates/fn_detector.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyLoadout.sqf
Labels: enhancement, Ready for merge, Templates

#2294 Fix typo in how to build.md guide
  How to build.md
Labels: Ready for merge

#2296 Fix Townnames in Tasks and City Info.
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_localizar.sqf
  A3A/addons/core/functions/Base/fn_location.sqf
  A3A/addons/core/functions/CREATE/fn_wavedCA.sqf
  A3A/addons/core/functions/Missions/fn_AS_Official.sqf
  A3A/addons/core/functions/init/fn_cityinfo.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
Labels: Bug-fix, change, Ready for merge

#2297 Set Temperate as Default for Auto Selction.
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/3CB/3CB_Civ_CHC.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Civ_TKC.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
Labels: change, Ready for merge

#2281 Add Possible Solutions for RHS frontgrip weapons and RHS optics
  A3A/addons/JeroenArsenal/JNA/fn_arsenal_addItem.sqf
  A3A/addons/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
Labels: change, enhancement, Ready for merge

#2292 Fix cargo trucks not being sellable
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
Labels: Bug-fix, Ready for merge

#2299 Updated AntistasiBulder to release build
  AntistasiBuilder.exe
  AntistasiBulder.exe
Labels: Ready for merge, Review pending

#2284 UtilityItems - Prevent players from carrying objects into vehicles and fix order precedence
  A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
  A3A/addons/core/functions/UtilityItems/fn_remainingFuel.sqf
Labels: Bug-fix, Ready for merge

#2290 Fix roadblock vehicles being despawned after stealing
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
Labels: Bug-fix, Ready for merge
