Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-01, with the labels that each got.

#2206 CS-RemoveLegacyKeyCache
  A3-Antistasi/MissionDescription/CfgRemoteExec.hpp
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Utility/KeyCache/Tests/readme.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTestUtility_revertInit.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTestUtility_revertStartGarbageCollectors.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_basicDeletion.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_basicPromotion.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_longFpsStressTest.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_shortFpsStressTest.sqf
  A3-Antistasi/functions/Utility/KeyCache/Tests/unitTest_garbageCollector_timedPromotion.sqf
  A3-Antistasi/functions/Utility/KeyCache/config.hpp
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_delete.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_garbageCollector.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_has.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_init.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_lookup.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_registerForGC.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_set.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_startGarbageCollectors.sqf
  A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_translate.sqf
Labels: Ready for merge

#2174 Tools - 👷‍♂️ Fixed data corruption caused by simplifyJunctions.
  Tools/StreetArtist/NG_importGUI.hpp
  Tools/StreetArtist/Please Read Me.md
  Tools/StreetArtist/functions.hpp
  Tools/StreetArtist/functions/Model/fn_NG_navRoadHM_assert.sqf
  Tools/StreetArtist/functions/Model/fn_NG_navRoadHM_remove.sqf
  Tools/StreetArtist/functions/Model/fn_NG_navRoad_assert.sqf
  Tools/StreetArtist/functions/Model/fn_NG_navRoad_connect.sqf
  Tools/StreetArtist/functions/Model/fn_NG_navRoad_disconnect.sqf
  Tools/StreetArtist/functions/Model/fn_NG_navRoad_getPeers.sqf
  Tools/StreetArtist/functions/Model/fn_NG_navRoad_isConnected.sqf
  Tools/StreetArtist/functions/NavGridGen/fn_NG_convert_navGridHM_navGridDB.sqf
  Tools/StreetArtist/functions/NavGridGen/fn_NG_convert_navRoadHM_navGridHM.sqf
  Tools/StreetArtist/functions/NavGridGen/fn_NG_init.sqf
  Tools/StreetArtist/functions/NavGridGen/fn_NG_main.sqf
  Tools/StreetArtist/functions/NavGridGen/fn_NG_simplify_junc.sqf
  Tools/StreetArtist/functions/StreetArtist/fn_NGSA_import.sqf
  Tools/StreetArtist/functions/StreetArtist/fn_NGSA_main.sqf
  Tools/StreetArtist/functions/StreetArtist/fn_NGSA_mainDialog.sqf
  Tools/StreetArtist/init.sqf
Labels: Bug-fix, enhancement, Refactor, Ready for merge, Review pending

#2187 Projects - Fuel Part 1
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/Garage/fn_callbackHandler.sqf
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_Logistics_Nodes.sqf
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/CREATE/fn_createCIV.sqf
  A3-Antistasi/functions/UtilityItems/fn_buyItem.sqf
  A3-Antistasi/functions/UtilityItems/fn_spawnLight.sqf
  A3-Antistasi/functions/init/fn_initClient.sqf
Labels: enhancement, Ready for merge

#2181 Templates - Add Civ Loadout Creation, Update Reb/Civ Templates, Update Examples.
  A3-Antistasi/REINF/addToGarrison.sqf
  A3-Antistasi/Templates/Templates/#Examples/CivilianExample.sqf
  A3-Antistasi/Templates/Templates/#Examples/FactionExample.sqf
  A3-Antistasi/Templates/Templates/#Examples/RebelExample.sqf
  A3-Antistasi/Templates/Templates/3CB/3CB_Civ_Arid.sqf
  A3-Antistasi/Templates/Templates/3CB/3CB_Civ_Temperate.sqf
  A3-Antistasi/Templates/Templates/3CB/3CB_Reb_CNM_Temperate.sqf
  A3-Antistasi/Templates/Templates/3CB/3CB_Reb_TKM_Arid.sqf
  A3-Antistasi/Templates/Templates/RHS/RHS_Civ.sqf
  A3-Antistasi/Templates/Templates/RHS/RHS_Reb_NAPA_Arid.sqf
  A3-Antistasi/Templates/Templates/RHS/RHS_Reb_NAPA_Temperate.sqf
  A3-Antistasi/Templates/Templates/VN/VN_CIV.sqf
  A3-Antistasi/Templates/Templates/VN/VN_Reb_POF.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_AAF_Arid.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_LDF_Enoch.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_Reb_FIA_Arid.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf
  A3-Antistasi/Templates/Templates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
  A3-Antistasi/functions/CREATE/fn_CIVinit.sqf
  A3-Antistasi/functions/CREATE/fn_ambientCivs.sqf
  A3-Antistasi/functions/CREATE/fn_createAIResources.sqf
  A3-Antistasi/functions/CREATE/fn_createCIV.sqf
  A3-Antistasi/functions/CREATE/fn_createSDKgarrisons.sqf
  A3-Antistasi/functions/Templates/fn_compileGroups.sqf
  A3-Antistasi/functions/init/fn_initVarServer.sqf
  A3-Antistasi/functions/init/fn_resourcecheck.sqf
Labels: change, enhancement, Ready for merge

#2207 Fuel part2
  A3-Antistasi/Garage/fn_addVehicle.sqf
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/functions.hpp
  A3-Antistasi/functions/Save/fn_loadServer.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Save/fn_saveLoop.sqf
  A3-Antistasi/functions/UtilityItems/fn_remainingFuel.sqf
  A3-Antistasi/functions/init/fn_initZones.sqf
  Map-Templates/Antistasi-Altis.Altis/Map/altisInfo.sqf
  Map-Templates/Antistasi-Anizay.tem_anizay/Map/tem_anizayInfo.sqf
  Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/Map/cam_lao_namInfo.sqf
  Map-Templates/Antistasi-Chernarus.chernarus_summer/Map/chernarus_summerInfo.sqf
  Map-Templates/Antistasi-ChernarusWinter.Chernarus_Winter/Map/chernarus_winterInfo.sqf
  Map-Templates/Antistasi-Kunduz.Kunduz/Map/kunduzInfo.sqf
  Map-Templates/Antistasi-Livonia.Enoch/Map/enochInfo.sqf
  Map-Templates/Antistasi-Malden.Malden/Map/maldenInfo.sqf
  Map-Templates/Antistasi-Sahrani.sara/Map/saraInfo.sqf
  Map-Templates/Antistasi-Stratis.Stratis/Map/stratisInfo.sqf
  Map-Templates/Antistasi-Takistan.takistan/Map/takistanInfo.sqf
  Map-Templates/Antistasi-Tembelan-Island.Tembelan/Map/tembelanInfo.sqf
  Map-Templates/Antistasi-Virolahti.vt7/Map/vt7Info.sqf
  Map-Templates/Antistasi-WotP.Tanoa/Map/tanoaInfo.sqf
Labels: enhancement, Change Requested

#2205 Fixed various incorrect usages of defined macros
  A3-Antistasi/Garage/Core/fn_requestSelectionChange.sqf
  A3-Antistasi/Garage/Core/fn_toggleLock.sqf
  A3-Antistasi/Garage/Pylons/fn_pylonsTurretToggle.sqf
  A3-Antistasi/functions/AI/fn_artySupport.sqf
  A3-Antistasi/functions/Base/fn_mrkWIN.sqf
  A3-Antistasi/functions/Garrison/fn_updatePreference.sqf
  A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
  A3-Antistasi/functions/Missions/fn_convoy.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf
  A3-Antistasi/functions/Punishment/fn_punishment_release.sqf
  A3-Antistasi/functions/REINF/fn_garrisonDialog.sqf
  A3-Antistasi/functions/Save/fn_loadStat.sqf
  A3-Antistasi/functions/Supports/fn_SUP_QRFAvailable.sqf
  A3-Antistasi/functions/Supports/fn_SUP_QRFRoutine.sqf
  A3-Antistasi/functions/init/fn_initServer.sqf
Labels: Bug-fix

#2225 fixed wrong state index being passed to update state
  A3A/addons/Garage/Core/fn_addUser.sqf
  A3A/addons/Garage/Refuel/fn_broadcastStateUpdate.sqf
  A3A/addons/Garage/Refuel/fn_refuelVehicleFromSources.sqf
Labels: Bug-fix

#2220 fix: added missing compile before preprocessFileLineNumbers
  A3A/addons/Garage/Public/fn_addVehiclesByClass.sqf
  A3A/addons/core/Templates/fn_selector.sqf
  A3A/addons/core/functions/Templates/fn_loadAddon.sqf
Labels: Bug-fix

#2238 ⚒ Refactored BattleMenu to Fully Qualified Classes
  A3A/addons/core/defines.hpp
  A3A/addons/core/dialogs.hpp
Labels: Bug-fix, Ready for merge
