Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-07, with the labels that each got.

#2402 Change CUP A10 to A10 with real pylons
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Bug-fix, Ready for merge

#2395 Facewear support for AI loadouts
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
  A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
  A3A/addons/core/functions/Templates/Loadouts/fn_loadout_setFacewear.sqf
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyLoadout.sqf
Labels: enhancement, Ready for merge

#2415 Vn update for Unstable
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentSort.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: enhancement, Ready for merge

#2403 added logging of debug code execution with name and UID
  A3A/addons/JeroenArsenal/JND/fn_debugv2.sqf
  A3A/addons/core/functions/init/fn_initParams.sqf
  A3A/addons/maps/MissionDescription/params.hpp
Labels: enhancement, Ready for merge, Exploit

#2254 Hr events
  A3A/addons/Events/$PBOPREFIX$
  A3A/addons/Events/CfgFunctions.hpp
  A3A/addons/Events/Events.hpp
  A3A/addons/Events/Stringtable.xml
  A3A/addons/Events/config.cpp
  A3A/addons/Events/functions/fn_addEventListener.sqf
  A3A/addons/Events/functions/fn_removeAllEventListeners.sqf
  A3A/addons/Events/functions/fn_removeEventListener.sqf
  A3A/addons/Events/functions/fn_triggerEvent.sqf
  A3A/addons/Events/functions/fn_validateEventArguments.sqf
  A3A/addons/Events/script_component.hpp
  A3A/addons/core/Includes/LogMacros.inc
  A3A/addons/core/Includes/script_macros.hpp
  A3A/addons/core/config.cpp
  A3A/addons/core/functions/Base/fn_buildHQ.sqf
  A3A/addons/core/functions/Base/fn_createOutpostsFIA.sqf
  A3A/addons/core/functions/Base/fn_markerChange.sqf
  A3A/addons/core/functions/Base/fn_vehicleBoxHeal.sqf
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/CREATE/fn_CIVinit.sqf
  A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
  A3A/addons/core/functions/CREATE/fn_civVEHinit.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createAICities.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
  A3A/addons/core/functions/CREATE/fn_createFIAOutposts2.sqf
  A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
Labels: enhancement, Ready for merge

#2423 corrected errors with event triggers
  A3A/addons/core/functions/Base/fn_buildHQ.sqf
  A3A/addons/core/functions/Base/fn_vehicleBoxHeal.sqf
  A3A/addons/core/functions/CREATE/fn_civVEHinit.sqf
Labels: Bug-fix
