Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-08, with the labels that each got.

#2426 Stop god carry
  A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
Labels: Bug-fix, Ready for merge

#2429 solved possible null variable issue with triggerEvent call
  A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
Labels: Bug-fix, Ready for merge

#2418 Quality-of-life looting/logistics tweaks
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/LTC/fn_carryCrate.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_load.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_unload.sqf
Labels: change, Ready for merge

#2381 Enemy near changes
  A3A/addons/Garage/Public/fn_addVehicle.sqf
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/core/functions/REINF/fn_addFIAveh.sqf
  A3A/addons/core/functions/REINF/fn_enemyNearCheck.sqf
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/core/functions/REINF/fn_garrisonDialog.sqf
  A3A/addons/core/functions/REINF/fn_reinfPlayer.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initParams.sqf
  A3A/addons/maps/MissionDescription/params.hpp
Labels: change, enhancement, Ready for merge

#2411 Fix rebel static mounting on DS
  A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
Labels: Bug-fix, Ready for merge

#2436 Fix arsenal weapon switch duping magazines
  A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf
  A3A/addons/JeroenArsenal/JNA/fn_arsenal_addItem.sqf
Labels: Bug-fix, Ready for merge

#2439 Template verification
  A3A/addons/core/functions/Templates/fn_compatibilityLoadFaction.sqf
Labels: change, Ready for merge

#2441 Fix leftover setStartTime from #2439
  A3A/addons/core/functions/Templates/fn_compatibilityLoadFaction.sqf
Labels: Bug-fix, Priority
