Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-11, with the labels that each got.

#2523 KAT Med update
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
Labels: change, Ready for merge

#2520 Western Sahara CDLC detection fix
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
Labels: Bug-fix, Ready for merge

#2524 Fix up GM vehicle categories to work better with attack/support
  A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
  A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Vehicle_Attributes.sqf
Labels: Ready for merge, Balance

#2522 Minor fixes for 3.0
  A3A/addons/core/functions/Base/fn_commsMP.sqf
  A3A/addons/core/functions/Base/fn_markerChange.sqf
  A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug-fix, Ready for merge

#2521 AFK timeout parameter + status bar indicator and logging tweaks
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3A/addons/core/functions/OrgPlayers/fn_theBossTransfer.sqf
  A3A/addons/core/functions/init/fn_clientIdleChecker.sqf
Labels: enhancement, Ready for merge

#2518 Fix GM & Unsung rebel launchers
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
Labels: Bug-fix, change, Ready for merge

#2517 Check autoload factions/addonVics/DLC
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
Labels: Bug-fix, Review pending

#2525 addonVics ref correct config class, and loading is fixed along with a…
  A3A/addons/core/functions/Templates/fn_loadAddon.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Ready for merge

#2527 added python bytecode-cache folder to gitignore
  .gitignore
Labels: Ready for merge

#2528 Fix missing semicolon in cfgfunctions
  A3A/addons/core/CfgFunctions.hpp
Labels: Ready for merge

#2529 Various one-liner fixes
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/Missions/fn_REP_Antenna.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
  A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf
  A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
Labels: Bug-fix, Ready for merge

#2531 add admins as member on check
  A3A/addons/core/functions/OrgPlayers/fn_isMember.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: change

#2532 Balance utility trucks in cases where the civ factions lacks them
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
Labels: change, Ready for merge

#2535 Increase default garage cap to 20 base + 4 per tier
  A3A/addons/Garage/Public/config.inc
Labels: change, Ready for merge

#2537 Fix Antistasi UI layer numbers fighting with other mods
  A3A/addons/core/functions/Base/fn_commsMP.sqf
  A3A/addons/core/functions/Intel/fn_showIntel.sqf
  A3A/addons/core/functions/Revive/fn_respawn.sqf
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
  A3A/addons/core/functions/init/fn_credits.sqf
  A3A/addons/core/functions/init/fn_tags.sqf
Labels: Bug-fix, Ready for merge

#2538 More minor-ish fixes from testing
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
  A3A/addons/core/functions/CREATE/fn_VEHdespawner.sqf
Labels: Bug-fix, Ready for merge

#2539 rem build No from big pop up and altered map names
  A3A/addons/core/Includes/script_mod.hpp
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/init/fn_credits.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/maps/config.cpp
Labels: Ready for merge

#2545 capitalisation fixes
  A3A/addons/GUI/functions/GUI/fn_commanderTab.sqf
  A3A/addons/Garage/Public/fn_addVehicle.sqf
  A3A/addons/core/Includes/includesBasics.txt
  A3A/addons/core/functions/Debug/fn_prepFunctions.sqf
  A3A/addons/core/functions/Punishment/fn_punishment.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_addActionForgive.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_checkStatus.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_oceanGulag.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_release.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_removeActionForgive.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_sentence_client.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_sentence_server.sqf
  A3A/addons/core/functions/UI/fn_customHint.sqf
  A3A/addons/core/functions/UI/fn_customHintDismiss.sqf
  A3A/addons/core/functions/UI/fn_customHintInit.sqf
  A3A/addons/core/functions/UI/fn_customHintRender.sqf
  A3A/addons/core/functions/UI/fn_shader_ratioToHex.sqf
  A3A/addons/core/functions/Utility/fn_getAdmin.sqf
  A3A/addons/core/functions/init/fn_credits.sqf
  LICENSE
  README.md
  Tools/StreetArtist/Collections/Serialisation/Primitives/fn_serialise_namespace.sqf
  Tools/StreetArtist/functions/UI/fn_customHint.sqf
  Tools/StreetArtist/functions/UI/fn_customHintDrop.sqf
  Tools/StreetArtist/functions/UI/fn_customHintInit.sqf
  Tools/StreetArtist/functions/UI/fn_customHintRender.sqf
  Tools/StreetArtist/functions/UI/fn_shader_ratioToHex.sqf
  changelog.rst
Labels: change

#2553 vn_khe_sanh pop update
  A3A/addons/maps/Antistasi_vn_khe_sanh.vn_khe_sanh/mapInfo.hpp
  A3A/addons/maps/Antistasi_vn_khe_sanh.vn_khe_sanh/onPlayerRespawn.sqf
Labels: Bug-fix

#2541 CUP Range Rover nodes
  A3A/addons/Logistics/Nodes/CUP.hpp
Labels: change, Ready for merge

#2557 3CBF-Logo integration for template
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/3CB/logo_small_3cb_ca.paa
Labels: change, Ready for merge

#2554 Show warnings when loading a mismatched or outdated mission
  A3A/addons/core/Includes/script_mod.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Debug/fn_prepFunctions.sqf
  A3A/addons/core/functions/init/fn_initPreJIP.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/maps/MissionDescription/master.hpp
Labels: change

#2555 Minor fixes to game selector UI
  A3A/addons/GUI/functions/SetupGUI/fn_setupDialog.sqf
  A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
Labels: Bug-fix, Ready for merge

#2556 Fix airport mortars
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
Labels: Bug-fix, Ready for merge

#2558 Fix bad cannon classname for ACR CAS plane
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Bug-fix, Ready for merge

#2559 Switch CUP rebel AA vehicle to Ural zu23 because the AIs cannot drive
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb.sqf
Labels: change, Ready for merge

#2534 Move the controls defined in setupDialog.hpp to control.hpp
  A3A/addons/GUI/dialogues/controls.hpp
  A3A/addons/GUI/dialogues/setupDialog.hpp
Labels: Ready for merge

#2560 removed old logistics and accompanying nodes
  A3A/addons/Logistics/Nodes/Vanilla.hpp
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/AddonVics/d3s_Logi_Nodes.sqf
  A3A/addons/core/Templates/AddonVics/rds_Logi_Nodes.sqf
  A3A/addons/core/Templates/Templates/#Examples/Example_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/3CB/3CBBAF_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/3CB/3CBFactions_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Logistics_Nodes.sqf
  A3A/addons/core/functions/Logistics/fn_logistics_addLoadAction.sqf
  A3A/addons/core/functions/Logistics/fn_logistics_getVehCapacity.sqf
  A3A/addons/core/functions/Logistics/fn_logistics_initNodes.sqf
  A3A/addons/core/functions/Logistics/fn_logistics_isLoadable.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_addAction.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_attachCargo.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_canLoad.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_generateHardPoints.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_getCargoNodeType.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_getCargoOffsetAndDir.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_getVehicleNodes.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_initMountedWeapon.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_load.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_refreshVehicleLoad.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_toggleAceActions.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_toggleLock.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_tryLoad.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_unload.sqf
  A3A/addons/core/functions/Logistics/howToAddStuffToLogistics.txt
Labels: change, Ready for merge

#2561 Unarmed key fix in fn_createAction
  A3A/addons/core/functions/Convoy/fn_createAIAction.sqf
Labels: change, Ready for merge

#2551 🗎 Leader Intel Search Fixes
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
Labels: Bug-fix, Ready for merge, Exploit

#2563 Initial HR Parameter
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Save/fn_loadPlayer.sqf
  A3A/addons/core/functions/Save/fn_resetPlayer.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: change, Ready for merge
