Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-06, with the labels that each got.

#2357 Fix suggested Modlists
  README.md
Labels: Ready for merge

#2369 Add ToFixed to the rest of Numbers being Displayed for Consistency
  A3A/addons/core/functions/Base/fn_logPerformance.sqf
  A3A/addons/core/functions/Base/fn_resourcesFIA.sqf
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/Save/fn_savePlayer.sqf
Labels: change, enhancement, Ready for merge

#2380 Templates - CUP Blufor updates for consistency with ACR changes
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
Labels: change, enhancement, Ready for merge, Templates

#2387 added gui helper functions
  A3A/addons/GUI/CfgFunctions.hpp
  A3A/addons/GUI/functions/controlsHelpers/fn_directChildCtrls.sqf
  A3A/addons/GUI/functions/controlsHelpers/fn_emplaceControl.sqf
  A3A/addons/GUI/functions/controlsHelpers/fn_sortCGList.sqf
Labels: enhancement, Ready for merge

#2378 Correct a Typo in CSAT Voices
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
Labels: Bug-fix, Ready for merge

#2393 Disable Arma rating changes for players
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: change, Ready for merge

#2394 Rework garage placement rotation
  A3A/addons/Garage/Core/fn_confirmPlacement.sqf
Labels: change, Ready for merge

#2347 Update french translations
  A3A/addons/GUI/Stringtable.xml
  A3A/addons/Garage/Stringtable.xml
  A3A/addons/core/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
Labels: localisation, Ready for merge

#2396 fixed typo for sara mapname_short
  A3A/addons/maps/Antistasi_sara.sara/description.ext
  A3A/addons/maps/Stringtable.xml
Labels: bug

#2397 Remove Petros's Face from Ai Faces
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
Labels: Ready for merge
