Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-02, with the labels that each got.

#2235 Fix maps stringtable
  A3A/addons/core/Includes/script_macros.hpp
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initParams.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/maps/Antistasi_Altis.Altis/description.ext
  A3A/addons/maps/Antistasi_Altis.Altis/mission.sqm
  A3A/addons/maps/Antistasi_Enoch.Enoch/description.ext
  A3A/addons/maps/Antistasi_Enoch.Enoch/mission.sqm
  A3A/addons/maps/Antistasi_Malden.Malden/description.ext
  A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm
  A3A/addons/maps/Antistasi_Stratis.Stratis/description.ext
  A3A/addons/maps/Antistasi_Stratis.Stratis/mission.sqm
  A3A/addons/maps/Antistasi_Takistan.takistan/mapInfo.sqf
  A3A/addons/maps/Antistasi_Tanoa.Tanoa/description.ext
  A3A/addons/maps/Antistasi_Tanoa.Tanoa/mission.sqm
  A3A/addons/maps/Antistasi_Tembelan.Tembelan/description.ext
  A3A/addons/maps/Antistasi_Tembelan.Tembelan/mission.sqm
  A3A/addons/maps/Antistasi_cam_lao_nam.cam_lao_nam/description.ext
  A3A/addons/maps/Antistasi_cam_lao_nam.cam_lao_nam/mission.sqm
  A3A/addons/maps/Antistasi_chernarus_summer.chernarus_summer/description.ext
  A3A/addons/maps/Antistasi_chernarus_summer.chernarus_summer/mission.sqm
  A3A/addons/maps/Antistasi_chernarus_winter.chernarus_winter/description.ext
  A3A/addons/maps/Antistasi_chernarus_winter.chernarus_winter/mission.sqm
  A3A/addons/maps/Antistasi_sara.sara/description.ext
  A3A/addons/maps/Antistasi_sara.sara/mission.sqm
  A3A/addons/maps/Antistasi_vt7.vt7/description.ext
  A3A/addons/maps/Antistasi_vt7.vt7/mission.sqm
  A3A/addons/maps/MissionDescription/params.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
Labels: Bug-fix, change, Map Issue, Ready for merge

#2241 Fixed hemtt build script
  A3A/addons/maps/MissionDescription/params.hpp
  Tools/Builder/buildAddons.ps1
Labels: Bug-fix

#2247 moved anti keybinds from eh to built in keybind introduced in arma3 v…
  A3A/addons/Garage/Core/fn_confirmPlacement.sqf
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/config.cpp
  A3A/addons/core/functions/Base/fn_keys.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_reinitY.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
  A3A/addons/core/keybinds.hpp
  A3A/addons/core/keybinds/CfgDefaultKeysPresets.hpp
  A3A/addons/core/keybinds/CfgUserActions.hpp
  A3A/addons/core/keybinds/UserActionGroups.hpp
  A3A/addons/core/keybinds/UserActionsConflictGroups.hpp
  A3A/addons/core/keybinds/fn_keyActions.sqf
Labels: change, Ready for merge

#2245 ℹ NavGrid Meta Supports Structued Schema.
  Tools/StreetArtist/functions.hpp
  Tools/StreetArtist/functions/StreetArtist/fn_NGSA_import.sqf
  Tools/StreetArtist/functions/StreetArtist/fn_NGSA_importV2.sqf
  Tools/StreetArtist/functions/StreetArtist/fn_NGSA_main.sqf
Labels: enhancement, Ready for merge

#2249 Add Seaports and Airbases to Jam Script
  A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf
Labels: change, Ready for merge

#2250 🔕 Dismiss hint migrated to modded keybinds.
  A3A/addons/core/functions/UI/fn_customHintInit.sqf
  A3A/addons/core/functions/UI/fn_customHintRender.sqf
  A3A/addons/core/keybinds/CfgDefaultKeysPresets.hpp
  A3A/addons/core/keybinds/CfgUserActions.hpp
  A3A/addons/core/keybinds/UserActionGroups.hpp
  A3A/addons/core/keybinds/UserActionsConflictGroups.hpp
  A3A/addons/core/keybinds/fn_keyActions.sqf
Labels: enhancement, Ready for merge

#2251 ⛽ Fuel Support Rework
  A3A/addons/Garage/Public/fn_addVehicle.sqf
  A3A/addons/Garage/Stringtable.xml
  A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initZones.sqf
  A3A/addons/maps/Antistasi_cam_lao_nam.cam_lao_nam/mapInfo.hpp
Labels: Bug-fix, Ready for merge

#2257 Fix AI/HC dismiss, remote control and garrison commands
  A3A/addons/core/dialogs.hpp
Labels: Bug-fix, Priority, Ready for merge

#2260 Fix patrol dogs not despawning with locations
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createAICities.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
Labels: Bug-fix, Ready for merge

#2263 Improve arsenal and vehicle arsenal compatible-magazine lists
  A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf
  A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
Labels: enhancement, Ready for merge

#2266 Fixed always on debug render for garage
  A3A/addons/Garage/Core/fn_confirmPlacement.sqf
  A3A/addons/Garage/Public/config.inc
Labels: Bug-fix, Review pending

#2259 🛒 Doom UI Buy Vehicle Menu
  A3A/addons/GUI/Stringtable.xml
  A3A/addons/GUI/dialogues/controls.hpp
  A3A/addons/GUI/dialogues/defines.hpp
  A3A/addons/GUI/dialogues/mainDialog.hpp
  A3A/addons/GUI/dialogues/textures.inc
  A3A/addons/GUI/dialogues/textures/placeholder_no_vehicle_preview.paa
  A3A/addons/GUI/functions/GUI/fn_buyVehicleDialog.sqf
  A3A/addons/GUI/functions/GUI/fn_commanderTab.sqf
  A3A/addons/core/Includes/common.inc
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Dialogs/fn_buyVehicle.sqf
  A3A/addons/core/functions/Dialogs/fn_buyVehicleCiv.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initParams.sqf
  A3A/addons/maps/MissionDescription/params.hpp
Labels: enhancement, Ready for merge

#2261 added a check to block setting prioritsed faction if it has no entry
  A3A/addons/core/Templates/fn_selector.sqf
Labels: Bug-fix, Ready for merge

#2265 Garage System - Small stringtable overhaul
  A3A/addons/Garage/Stringtable.xml
Labels: localisation, Ready for merge
