Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-09, with the labels that each got.

#2379 Mod Integration: Unsung
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/UNS/UNS_AI_NVA.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_AI_US.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Civ.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf
  A3A/addons/core/Templates/Templates/UNSUNG/Unsung_AI_NVA_Tropical.sqf
  A3A/addons/core/Templates/Templates/UNSUNG/Unsung_AI_US_Tropical.sqf
  A3A/addons/core/Templates/fn_detector.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentSort.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/Logistics/functions/fn_logistics_tryLoad.sqf
Labels: enhancement, Ready for merge, Testing needed

#2434 Fix high command FT and garrison annoyances
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
Labels: Bug-fix, enhancement, Review pending

#2449 Ace unload on garage
  A3A/addons/Garage/Public/fn_addVehicle.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
Labels: Bug-fix, enhancement, Ready for merge

#2450 Change spawning rules for airborne players and rebel UAVs
  A3A/addons/core/functions/Base/fn_distance.sqf
Labels: change, Ready for merge

#2438 fix Filepath Typo
  A3-Antistasi/Stringtable.xml
  A3-Antistasi/Templates/selector.sqf
  README.md
Labels: Bug-fix, Ready for merge

#2453 Extra message for New Garage
  A3A/addons/Garage/Core/fn_confirmPlacement.sqf
  A3A/addons/core/functions/REINF/fn_addFIAveh.sqf
Labels: enhancement, Ready for merge

#2430 fixed issue with everyone being considered admin on lh (garage)
  A3A/addons/Garage/Core/fn_requestSelectionChange.sqf
  A3A/addons/Garage/Core/fn_toggleLock.sqf
  A3A/addons/Garage/Extras/fn_findMount.sqf
  A3A/addons/Garage/Public/config.inc
Labels: Bug-fix, Ready for merge

#2454 Kill Maru
  A3A/addons/core/Stringtable.xml
  A3A/addons/maps/Antistasi_Enoch.Enoch/description.ext
  A3A/addons/maps/Antistasi_Kunduz.Kunduz/description.ext
  A3A/addons/maps/Antistasi_Malden.Malden/description.ext
  A3A/addons/maps/Antistasi_Stratis.Stratis/description.ext
  A3A/addons/maps/Antistasi_Tanoa.Tanoa/description.ext
  A3A/addons/maps/Antistasi_Tembelan.Tembelan/description.ext
  A3A/addons/maps/Antistasi_tem_anizay.tem_anizay/description.ext
  A3A/addons/maps/Antistasi_vt7.vt7/description.ext
Labels: change, Ready for merge

#2455 add expansion info
  A3A/antistasi_logo.paa
  A3A/antistasi_logo_small.paa
  A3A/antistasi_logo_sw.paa
  A3A/antistasi_overview.paa
  A3A/mod.cpp
Labels: enhancement, Ready for merge

#2428 Allow (limited) guest commanders
  A3A/addons/Garage/Public/config.inc
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3A/addons/core/functions/OrgPlayers/fn_isMember.sqf
  A3A/addons/core/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf
  A3A/addons/core/functions/OrgPlayers/fn_theBossToggleEligibility.sqf
  A3A/addons/core/functions/OrgPlayers/fn_theBossTransfer.sqf
  A3A/addons/core/functions/Save/fn_loadPlayer.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initParams.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/maps/MissionDescription/params.hpp
Labels: enhancement, Ready for merge

#2459 Add game type def
  A3A/addons/core/config.cpp
Labels: enhancement
