Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-04, with the labels that each got.

#2321 Added toFixed to visual money displays
  A3A/addons/core/functions/Base/fn_logPerformance.sqf
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
Labels: enhancement, Ready for merge

#2298 Fixing CUP reb factions
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/CUP/CUP_Civ.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKL_Arid.sqf
Labels: change, Ready for merge

#2307 Fix non-pylons being removed by prepPylons
  A3A/addons/Garage/Extras/fn_reloadExtras.sqf
  A3A/addons/Garage/StatePreservation/fn_getAmmoData.sqf
  A3A/addons/Garage/StatePreservation/fn_prepPylons.sqf
Labels: Bug-fix, Ready for merge

#2309 Fix createVehicleCrew placing turret crew in wrong seats
  A3A/addons/core/functions/CREATE/fn_createVehicleCrew.sqf
Labels: Bug-fix, Ready for merge

#2315 Remove left over setUnitTrait
  A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
Labels: Bug-fix, change, Ready for merge

#2306 Non-member arsenal limits management dialog
  A3A/addons/GUI/CfgFunctions.hpp
  A3A/addons/GUI/Stringtable.xml
  A3A/addons/GUI/dialogues/arsenalLimitsDialog.hpp
  A3A/addons/GUI/dialogues/dialogs.hpp
  A3A/addons/GUI/dialogues/ids.inc
  A3A/addons/GUI/functions/GUI/fn_arsenalLimitsDialog.sqf
  A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf
  A3A/addons/JeroenArsenal/JNA/fn_arsenal_init.sqf
  A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/init/fn_initParams.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/maps/MissionDescription/params.hpp
Labels: enhancement, Ready for merge

#2305 No-unlocks support for rebel AI equipping
  A3A/addons/JeroenArsenal/JNA/fn_arsenal_addItem.sqf
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/functions/Ammunition/fn_arsenalManage.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3A/addons/core/functions/Ammunition/fn_fetchRebelGear.sqf
  A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
  A3A/addons/core/functions/Ammunition/fn_itemSort.sqf
  A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf
  A3A/addons/core/functions/Base/fn_initPetros.sqf
  A3A/addons/core/functions/REINF/fn_dismissPlayerGroup.sqf
  A3A/addons/core/functions/REINF/fn_dismissSquad.sqf
  A3A/addons/core/functions/REINF/fn_equipRebel.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/maps/MissionDescription/params.hpp
Labels: enhancement, Ready for merge

#2322 Cup Cleanup
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_SLA_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: bug, change, Ready for merge

#2323 Fix flag texture on AI resources and factories
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
Labels: Bug-fix, Ready for merge

#2318 Attempt to make Locked Vehicles Opt-In
  A3A/addons/Garage/Public/config.inc
  A3A/addons/core/functions/Base/fn_unlockVehicle.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: change, enhancement, Ready for merge

#2326 Silence Players with Ace / Missed Semicolon
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyAssets.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
Labels: bug, enhancement, Ready for merge

#2312 CUP ACR fixes
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Temperate.sqf
  A3A/addons/core/functions/Templates/fn_compileGroups.sqf
Labels: Ready for merge

#2328 Fix categoryOverrides not being created on clients, and tag with A3A
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Priority, Ready for merge

#2339 Added additional Punishment logging for cheking player's UAV body
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Punishment/fn_punishment.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
Labels: enhancement, Refactor, Ready for merge

#2340 Added a block in confimPlacement if already placing
  A3A/addons/Garage/Core/fn_confirmPlacement.sqf
Labels: Bug-fix, Ready for merge

#2329 Adding more Special Forces Groups
  A3A/addons/core/functions/CREATE/fn_createAICities.sqf
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
  A3A/addons/core/functions/Missions/fn_attackHQ.sqf
  A3A/addons/core/functions/Templates/fn_compileGroups.sqf
Labels: low priority, Ready for merge

#2344 fixed incorrect variable used for flight height restrictions
  A3A/addons/core/functions/REINF/fn_NATObomb.sqf
Labels: Bug-fix
