Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2022-10, with the labels that each got.

#2475 Fix missing IFV array in RHS AFRF
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
Labels: Bug-fix, Ready for merge

#2477 Finite rebel launchers and explosives
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyAssets.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
Labels: enhancement, Ready for merge

#2464 Fix refuel refunding
  A3A/addons/Garage/Public/fn_addVehicle.sqf
Labels: Ready for merge

#2467 Vanilla template fixes
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
Labels: Ready for merge

#2468 Cup template nit pick fixes
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
Labels: Ready for merge

#2469 Skip time behavior check
  A3A/addons/core/functions/Base/fn_distanceUnits.sqf
  A3A/addons/core/functions/Dialogs/fn_skiptime.sqf
Labels: Ready for merge

#2462 Fixes and tweaks related to guest commander functionality
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3A/addons/core/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf
  A3A/addons/core/functions/OrgPlayers/fn_memberAdd.sqf
  A3A/addons/core/functions/OrgPlayers/fn_playerLeashCheckPosition.sqf
  A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf
  A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/core/functions/init/fn_clientIdleChecker.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Bug-fix, change, Ready for merge

#2479 Builder displays when you built
  Tools/Builder/buildAddons.ps1
Labels: Tools

#2485 added dirty cd fix for options
  .github/workflows/publishBranchToSteamDev.yml
Labels: Tools

#2486 added new wf to unstable for use with current mod branches
  .github/workflows/publishBranchToSteamDev.yml
Labels: Tools, CI\CD

#2487 Create CD_Steam_Dev.yml
  .github/workflows/CD_Steam_Dev.yml
Labels: Tools, CI\CD

#2489 Block players from mounting a static they're carrying and improve menu behaviour
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Dialogs/fn_moveHQObject.sqf
Labels: change, Ready for merge

#2474 Tweak ability of rebels to respond to punishments and major attacks
  A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
  A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
  A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
Labels: change, Ready for merge

#2466 Update verification
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyAssets.sqf
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyLoadout.sqf
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyLoadoutsData.sqf
Labels: Ready for merge

#2480 attachTo use bounding box dimensions
  A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
Labels: Ready for merge

#2472 Compatible magazines in jna
  A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf
  A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
Labels: change, Ready for merge

#2490 Fix enemy militia trucks not being sellable
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
Labels: Bug-fix, change, Ready for merge

#2491 Create UpdateDevBuild.yml
  .github/workflows/UpdateDevBuild.yml
Labels: CI\CD

#2493 To unstable
  .github/workflows/UpdateDevBuild.yml
Labels: CI\CD

#2427 Template and Integration GM
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
  A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
  A3A/addons/core/Templates/fn_detector.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3A/addons/core/functions/Utility/fn_getItemListFromDLC.sqf
Labels: enhancement, Review pending

#2494 Fix missing _fnc prefixes created during merges
  A3A/addons/core/functions/Templates/Verification/fn_TV_verifyAssets.sqf
Labels: Bug-fix, Priority, Ready for merge

#2496 Fix/tweak various rebel gear & loot issues found in public testing
  A3A/addons/core/functions/Ammunition/fn_fillLootCrate.sqf
  A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
  A3A/addons/core/functions/Ammunition/fn_loot.sqf
  A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf
  A3A/addons/core/functions/REINF/fn_equipRebel.sqf
Labels: Bug-fix, change, Ready for merge

#2497 First Localization Merge
  A3A/addons/GUI/Stringtable.xml
  A3A/addons/Garage/Stringtable.xml
  A3A/addons/core/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
Labels: localisation

#2498 Stringtable adaptation for #2476
  A3A/addons/GUI/Stringtable.xml
Labels: localisation

#2499 patches forgotten hasRHS checks with suitable replacements
  A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
  A3A/addons/core/functions/CREATE/fn_civVEHinit.sqf
  A3A/addons/core/functions/REINF/fn_stealStatic.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Bug-fix

#2500 Tweaks and fixes to GM templates
  A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
Labels: Bug-fix, Balance

#2501 Fixes from testing
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/AI/fn_fleeToSide.sqf
  A3A/addons/core/functions/Base/fn_addHC.sqf
  A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_initZones.sqf
Labels: Bug-fix

#2502 removed biber from list of engineering vehicles
  A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
Labels: change

#2509 fixed "looser" typo
  A3A/addons/core/functions/Base/fn_markerChange.sqf
  changelog.rst
Labels: change, Ready for merge

#2508 rough fix for infinite money exploit
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
Labels: Bug-fix, Ready for merge

#2510 Improve attack selection dependency on rebel HQ position
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Base/fn_chooseAttack.sqf
Labels: Ready for merge, Balance

#2513 Fix case where autoload game had different params list
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug-fix, Ready for merge

#2507 Virolahti - removed "edit terrain object" modules
  A3A/addons/maps/Antistasi_vt7.vt7/mission.sqm
Labels: change, Map Issue, Ready for merge

#2503 Player and Rebel Faction starting money parameters
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: enhancement, Ready for merge

#2515 Rename Unsung NVA to PAVN / Loadout Adjustments
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/UNS/UNS_AI_PAVN.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_AI_US.sqf
Labels: bug, change, Templates
