Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-06, with the labels that each got.

#2755 Allow rebels to purchase AT and AA missile launcher troops
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/Base/fn_garrisonInfo.sqf
  A3A/addons/core/functions/Dialogs/fn_unit_recruit.sqf
  A3A/addons/core/functions/REINF/fn_equipRebel.sqf
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/core/functions/REINF/fn_garrisonDialog.sqf
  A3A/addons/core/functions/REINF/fn_reinfPlayer.sqf
  A3A/addons/core/functions/Templates/fn_compileGroups.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: enhancement, Ready for merge

#2768 Fix syntax for adding WS CDLC static AA to rebel templates
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
Labels: Bug-fix, Ready for merge

#2769 Fix trailing comma and missing AA plane in ION Temperate
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Bug-fix, Ready for merge

#2773 Refactor buyable item management
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
  A3A/addons/core/functions/AI/fn_surrenderAction.sqf
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/LTC/fn_carryCrate.sqf
  A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
  A3A/addons/core/functions/LTC/fn_spawnCrate.sqf
  A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf
  A3A/addons/core/functions/REINF/fn_addFIAveh.sqf
  A3A/addons/core/functions/REINF/fn_build.sqf
  A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
  A3A/addons/core/functions/UtilityItems/fn_initMovableObject.sqf
  A3A/addons/core/functions/UtilityItems/fn_initObject.sqf
  A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf
  A3A/addons/core/functions/UtilityItems/fn_medicalBox.sqf
  A3A/addons/core/functions/UtilityItems/fn_medicalBoxFill.sqf
  A3A/addons/core/functions/UtilityItems/fn_openDoorsTent.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initUtilityItems.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
  A3A/addons/garage/CfgFunctions.hpp
  A3A/addons/garage/Core/fn_confirm.sqf
  A3A/addons/garage/Core/fn_confirmPlacement.sqf
  A3A/addons/garage/Public/fn_addVehicle.sqf
  A3A/addons/garage/Public/fn_callbackHandler.sqf
  A3A/addons/garage/Stringtable.xml
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
  A3A/addons/logistics/Private/fn_initPackableObjects.sqf
  A3A/addons/logistics/Private/fn_packObject.sqf
  A3A/addons/logistics/Private/fn_unpackObject.sqf
  A3A/addons/logistics/Private/fn_unpackObjectAction.sqf
Labels: change, Ready for merge

#2780 Update Spanish translation
  A3A/addons/core/Stringtable.xml
  A3A/addons/gear/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
Labels: localisation, Ready for merge

#2789 Remove unintentional enemy skill dependence on resource balance setting
  A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
Labels: Bug-fix, Ready for merge

#2791 Dive bombing & CAS fixes
  A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
Labels: Bug-fix, Ready for merge

#2793 Remove deleted files from logistics CfgFunctions
  A3A/addons/logistics/CfgFunctions.hpp
Labels: Bug-fix, Ready for merge

#2797 ACRE Jamming
  A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Ready for merge
