Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-08, with the labels that each got.

#2889 Fix trailing comma and missing AA plane in ION Temperate (master repair attempt)
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Bug-fix

#2887 Fix autoRearm first aid kits jam bug and reduce waitUntil spam
  A3A/addons/core/functions/AI/fn_autoRearm.sqf
Labels: Bug-fix, performance, Ready for merge

#2891 Fix Lafette tripod category override typo
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
Labels: Bug-fix, Ready for merge

#2898 Fix for undefined variable in ArmStatics
  A3A/addons/patcom/functions/Patcom/fn_patrolArmStatics.sqf
Labels: Bug-fix, Ready for merge

#2902 3.3.3 changelog update
  changelog.rst
Labels: Review pending

#2904 3.3.3 unstable to master
  A3A/addons/core/functions/AI/fn_autoRearm.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/CREATE/fn_AAFroadPatrol.sqf
  A3A/addons/core/functions/CREATE/fn_reinforcementsAI.sqf
  A3A/addons/patcom/functions/Patcom/fn_patrolArmStatics.sqf
  changelog.rst
Labels: change, Ready for merge

#2905 Fix static saving mis-commit
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
Labels: Bug-fix, Priority

#2881 logistics_localization
  A3A/addons/core/functions/SalvageRope/fn_salvageRope.sqf
  A3A/addons/logistics/Dev/fn_generateCargoOffset.sqf
  A3A/addons/logistics/Private/fn_addAction.sqf
  A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
  A3A/addons/logistics/Private/fn_addWeaponAction.sqf
  A3A/addons/logistics/Private/fn_load.sqf
  A3A/addons/logistics/Private/fn_tryLoad.sqf
  A3A/addons/logistics/Private/fn_unload.sqf
  A3A/addons/logistics/Stringtable.xml
Labels: enhancement, localisation, Ready for merge

#2899 Enable rebel AI to use rifle+muzzle combo grenade launchers
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
Labels: enhancement, Ready for merge

#2886 jeroen_arsenal_localization
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_handleAction.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_vehicleArsenal.sqf
  A3A/addons/jeroen_arsenal/JND/fn_debugv2.sqf
  A3A/addons/jeroen_arsenal/Stringtable.xml
Labels: enhancement, localisation, Ready for merge

#2917 Fix to allow AI use light helis in QRF
  A3A/addons/core/functions/CREATE/fn_createAttackForceAir.sqf
Labels: Bug-fix, Ready for merge

#2842 Moving Ace Init
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/init/fn_initACE.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Ready for merge

#2876 PATCOM Garrisons minor fixes and adjustments
  A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
  A3A/addons/patcom/functions/Patcom/fn_patrolInit.sqf
Labels: change, enhancement, Ready for merge

#2910 Apex and jets uavs
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
Labels: Ready for merge, Templates

#2916 CSAT enoch and arid transport planes
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
Labels: change, Ready for merge, Templates

#2921 Multiple bug fixes
  A3A/addons/core/functions/AI/fn_fastrope.sqf
  A3A/addons/core/functions/AI/fn_landThreatEval.sqf
  A3A/addons/core/functions/AI/fn_rearmCall.sqf
  A3A/addons/core/functions/Base/fn_placementselection.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
  A3A/addons/core/functions/Garrison/fn_updateGarrison.sqf
  A3A/addons/core/functions/Missions/fn_RES_Refugees.sqf
  A3A/addons/core/functions/REINF/fn_buildMinefield.sqf
  A3A/addons/core/functions/init/fn_initUtilityItems.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/events/functions/fn_validateEventArguments.sqf
Labels: Bug-fix, Ready for merge

#2922 Fixed missing include
  A3A/addons/core/functions/AI/fn_mortarDrill.sqf
Labels: Bug-fix, Ready for merge

#2925 package name change
  A3A/addons/config_fixes/Stringtable.xml
  A3A/addons/core/Stringtable.xml
  A3A/addons/events/Stringtable.xml
  A3A/addons/garage/Stringtable.xml
  A3A/addons/gear/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/jeroen_arsenal/Stringtable.xml
  A3A/addons/logistics/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
Labels: localisation, CI\CD

#2926 Fix mismatched lowercased a3a in some config_fixes files
  A3A/addons/config_fixes/RHS/chdkz_rhs.hpp
  A3A/addons/config_fixes/bomb_weapons.hpp
Labels: Priority, Refactor

#2923 " rebells"-fix
  A3A/addons/core/Templates/Templates.hpp
Labels: Bug-fix, Ready for merge
