Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-11, with the labels that each got.

#3020 Update setPlaneLoadout with missing WS faction aircraft
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#3021 Improve createSupport logging
  A3A/addons/core/functions/Supports/fn_createSupport.sqf
Labels: Change, Ready for merge, Data Lock Approved

#3023 Rework builder UI alignment to work with non 1080p resolutions:
  A3A/addons/gui/dialogues/placerHintsRsc.hpp
  A3A/addons/gui/dialogues/teamLeaderBuilder.hpp
  A3A/addons/gui/functions/GUI/fn_teamLeaderRTSPlacerDialog.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#3025 Added WS AA/Zu truck vehicle attributes
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Vehicle_Attributes.sqf
Labels: Change, Ready for merge, Data Lock Approved

#3026 Fix logistics JIP bugs
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/logistics/Public/fn_addLoadAction.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#3027 Add Arma version checking
  A3A/addons/core/Includes/script_mod.hpp
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Change, Ready for merge, Data Lock Approved

#3030 Fix mouse scrolling in building placer
  A3A/addons/gui/functions/GUI/fn_teamLeaderRTSPlacerDialog.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#3033 3.4 changelog
  changelog.rst
Labels: Ready for merge, Data Lock Approved

#3018 Adds Kozlice 12G to rebels
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
Labels: Change, Ready for merge

#3042 Move bool param conversion to initServer to fix autoload
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
Labels: Bug, Ready for merge

#3044 Improve double-revive case
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Revive/fn_actionRevive.sqf
Labels: Bug, Ready for merge

#3047 SIFA -> SFIA typo fix
  A3A/addons/config_fixes/WS/CfgMarkers.hpp
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
Labels: Bug, Ready for merge

#3061 Add log/notify only option to punishment system
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_checkStatus.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
Labels: Change, Ready for merge

#3063 Fix for minor header bug
  A3A/addons/core/Scripts/fn_advancedTowingInit.sqf
  A3A/addons/core/functions/Base/fn_mrkWIN.sqf
  A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf
  A3A/addons/core/functions/REINF/fn_controlunit.sqf
Labels: Bug, Ready for merge

#3055 Csat enoch marksmens dlc for 3.4.1
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
Labels: Bug, Ready for merge

#3058 params update
  A3A/addons/core/Params.hpp
Labels: Change, Ready for merge

#3064 Assassinate mission misc fixes
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Missions/fn_AS_Official.sqf
  A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
  A3A/addons/core/functions/Missions/fn_AS_specOP.sqf
Labels: Bug, Ready for merge

#3043 Fix errors when there are no suitable buildings to garrison
  A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
Labels: Bug, Ready for merge, Review pending

#3059 Fix some real and theoretical revive issues
  A3A/addons/core/functions/Revive/fn_handleDamage.sqf
  A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
  A3A/addons/core/functions/Revive/fn_unconsciousAAF.sqf
Labels: Bug, Change, Ready for merge

#3066 Vanilla templates adjusted to pass loadout validation.
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
Labels: Bug, Ready for merge

#3068 Corrected magazine for RHS 2S1 Artillery
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF.sqf
Labels: Bug, Ready for merge

#3069 3-4-1 changelog and version
  A3A/addons/core/Includes/script_version.hpp
  README.md
  changelog.rst
Labels: Ready for merge

#3071 Unstable to master for 3.4.1 release
  A3A/addons/config_fixes/WS/CfgMarkers.hpp
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Scripts/fn_advancedTowingInit.sqf
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
  A3A/addons/core/functions/Base/fn_mrkWIN.sqf
  A3A/addons/core/functions/CREATE/fn_AAFroadPatrol.sqf
  A3A/addons/core/functions/Missions/fn_AS_Official.sqf
  A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
  A3A/addons/core/functions/Missions/fn_AS_specOP.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_checkStatus.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
  A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf
  A3A/addons/core/functions/REINF/fn_controlunit.sqf
  A3A/addons/core/functions/Revive/fn_actionRevive.sqf
  A3A/addons/core/functions/Revive/fn_handleDamage.sqf
  A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
  A3A/addons/core/functions/Revive/fn_unconsciousAAF.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/garage/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
  A3A/addons/jeroen_arsenal/Stringtable.xml
  A3A/addons/logistics/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
  A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
  README.md
  changelog.rst
Labels: Ready for merge

#2866 [Map Port] Isla duala
  A3A/addons/config_fixes/IslaDuala3/config.cpp
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/cba_settings.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/description.ext
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/initServer.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/mapInfo.hpp
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/mission.sqm
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/navGrid - backup prebridge cut.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/navGrid.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: Enhancement, Map Issue, Draft
