Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-01, with the labels that each got.

#2617 #2592 and #2591 to Unstable
  A3A/addons/core/Includes/cba_settings.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
Labels: change, Ready for merge

#2604 Rewrite playerMarkers so that it works
  A3A/addons/core/functions/init/fn_playerMarkers.sqf
Labels: Bug-fix, Ready for merge

#2603 Fix marker side loading
  A3A/addons/core/functions/Save/fn_loadServer.sqf
Labels: Bug-fix, Ready for merge

#2608 force disable acex_headless
  A3A/addons/core/Includes/cba_settings.sqf
Labels: change, Ready for merge

#2615 Childproof 3CBBAF
  A3A/addons/core/Templates/Templates.hpp
Labels: Bug-fix, Ready for merge

#2610 Fix original save detection
  A3A/addons/core/functions/Save/fn_collectSaveData.sqf
Labels: Bug-fix, Ready for merge

#2600 typo fix leafes-leaves
  A3A/addons/maps/Stringtable.xml
Labels: localisation

#2611 HC Mortar faction key fix
  A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
Labels: Bug-fix, Ready for merge

#2619 Fix RHS USAF non-arid artillery copypaste bugs
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
Labels: Bug-fix, Ready for merge

#2618 Fix early battle menu key use
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/keybinds/fn_keyActions.sqf
Labels: Bug-fix, Ready for merge

#2616 Add CUP BW, HIL, TKM Reb, TKC Civs. (Some Love for CUP ☕)
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_HIL.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Civ_CHC.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Civ_TKC.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
  A3A/addons/core/functions/AI/fn_undercoverAI.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
Labels: change, enhancement, Technically Ready For Merge

#2476 Buy item GUI (PART 1)
  A3A/addons/GUI/CfgFunctions.hpp
  A3A/addons/GUI/dialogues/buyVehicleDialog.hpp
  A3A/addons/GUI/dialogues/dialogs.hpp
  A3A/addons/GUI/dialogues/ids.inc
  A3A/addons/GUI/dialogues/textures.inc
  A3A/addons/GUI/functions/GUI/fn_buyVehicleDialog.sqf
  A3A/addons/GUI/functions/GUI/fn_buyVehicleTabs.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Ready for merge

#2628 Dedicated Server/Headless client air tables fix
  A3A/addons/core/functions/Intel/fn_placeIntel.sqf
Labels: Bug-fix

#2624 remove old addactions
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Bug-fix

#2623 Fix setIdentity
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_initPetros.sqf
  A3A/addons/core/functions/CREATE/fn_CIVinit.sqf
  A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
  A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
  A3A/addons/core/functions/Missions/fn_RES_Prisoners.sqf
  A3A/addons/core/functions/Missions/fn_RES_Refugees.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
  A3A/addons/core/functions/REINF/fn_FIAinit.sqf
  A3A/addons/core/functions/Utility/fn_setIdentity.sqf
  A3A/addons/core/functions/Utility/fn_setIdentityLocal.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Bug-fix

#2631 Cicd meta fix
  .github/workflows/UpdateDevBuild.yml
  .github/workflows/publishBranchToSteam.yml
  .github/workflows/publishBranchToSteamDev.yml
  .github/workflows/publishBranchToSteamDev2.yml
  Tools/Builder/buildAddons.ps1
Labels: CI\CD

#2632 update dependency
  .github/workflows/UpdateDevBuild.yml
Labels: CI\CD

#2635 lowercase key name
  Tools/Builder/buildAddons.ps1
Labels: CI\CD

#2636 update key names
  Tools/Builder/buildAddons.ps1
Labels: CI\CD

#2637 skip vehicles that are not in cfgVehicles BuyVehicle GUI
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
Labels: Bug-fix

#2638 3.1.0 preliminary changelog
  changelog.rst
Labels: change

#2640 Improved setup process feedback hints
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
  A3A/addons/core/functions/init/fn_startGame.sqf
  changelog.rst
Labels: enhancement
