Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-03, with the labels that each got.

#2663 Bugfix/cdlc ws detection
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
Labels: Bug-fix, Ready for merge

#2664 Include WS config in logistics config
  A3A/addons/logistics/CfgLogistics.hpp
Labels: Bug-fix, Ready for merge

#2622 Garrison Limit
  .gitignore
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_garrisonInfo.sqf
  A3A/addons/core/functions/Base/fn_mrkUpdate.sqf
  A3A/addons/core/functions/Garrison/fn_getGarrisonLimit.sqf
  A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
Labels: Change Requested

#2677 Fix static crew simulation bug
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
Labels: Bug-fix, Ready for merge

#2672 Add Chemlights to the starting equipment
  A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
Labels: change, enhancement, Ready for merge

#2671 Fix edge case in minefields mine count
  A3A/addons/core/functions/Dialogs/fn_mineDialog.sqf
Labels: Bug-fix, Ready for merge

#2670 making moveHQObjects non-lethal
  A3A/addons/core/functions/Dialogs/fn_moveHQObject.sqf
Labels: Bug-fix, Ready for merge

#2669 Large fuel tank saving
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
Labels: Bug-fix, Ready for merge

#2673 Add the ability for carrable objects to be placed on surfaces
  A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
Labels: change, enhancement, Ready for merge

#2542 Logistics items (BUY ITEM PART 2)
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
  A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
  A3A/addons/core/functions/UtilityItems/fn_initMovableObject.sqf
  A3A/addons/core/functions/UtilityItems/fn_medicalBox.sqf
  A3A/addons/core/functions/UtilityItems/fn_medicalBoxFill.sqf
  A3A/addons/core/functions/UtilityItems/fn_openDoorsTent.sqf
  A3A/addons/garage/Public/fn_callbackHandler.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/buyVehicleDialog.hpp
  A3A/addons/gui/dialogues/dialogs.hpp
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/dialogues/textures.inc
  A3A/addons/gui/functions/GUI/fn_buyVehicleDialog.sqf
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
  A3A/addons/logistics/Cargo/ACE.hpp
  A3A/addons/logistics/Cargo/Vanilla.hpp
  A3A/addons/logistics/CfgFunctions.hpp
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Packable/Vanilla.hpp
  A3A/addons/logistics/Private/fn_initPackableObjects.sqf
  A3A/addons/logistics/Private/fn_packObject.sqf
  A3A/addons/logistics/Private/fn_unpackObject.sqf
Labels: change, enhancement, Ready for merge

#2680 Fix GM artillery error
  A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
Labels: Bug-fix, Ready for merge

#2651 Disable lambs danger when it is loaded
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: change, Ready for merge

#2678 Rewrite radioJam, improve perf and fix last-tower bug
  A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf
Labels: Bug-fix, performance, Ready for merge

#2679 Fix HQ position desync
  A3A/addons/core/functions/Base/fn_buildHQ.sqf
  A3A/addons/core/functions/Base/fn_placementselection.sqf
  A3A/addons/core/functions/Base/fn_relocateHQObjects.sqf
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug-fix, Refactor, Ready for merge

#2574 implement undercover removal when approaching downed heli
  A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
Labels: Ready for merge, Exploit

#2662 RHS SAF Template/support
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: enhancement, Ready for merge, Templates

#2687 Rewrite spawn positions so QRFs and garrisons coexist
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_distance.sqf
  A3A/addons/core/functions/CREATE/fn_availableBasesLand.sqf
  A3A/addons/core/functions/CREATE/fn_countFreeSpawnPositions.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackForceMixed.sqf
  A3A/addons/core/functions/CREATE/fn_findSpawnPosition.sqf
  A3A/addons/core/functions/CREATE/fn_freeSpawnPositions.sqf
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
  A3A/addons/core/functions/CREATE/fn_patrolReinf.sqf
  A3A/addons/core/functions/CREATE/fn_spawnVehicleAtMarker.sqf
  A3A/addons/core/functions/EventHandler/fn_vehicleDeletedEH.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
  A3A/addons/core/functions/Supports/fn_SUP_QRFAir.sqf
  A3A/addons/core/functions/Supports/fn_SUP_QRFLand.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
  A3A/addons/core/functions/init/fn_initSpawnPlaces.sqf
  A3A/addons/core/functions/init/fn_prepareMarkerArrays.sqf
Labels: Bug-fix, enhancement, Ready for merge

#2674 Add dive bombing capability to CAS supports
  A3A/addons/config_fixes/$PBOPREFIX$
  A3A/addons/config_fixes/CfgMagazines.hpp
  A3A/addons/config_fixes/CfgVehicles.hpp
  A3A/addons/config_fixes/CfgWeapons.hpp
  A3A/addons/config_fixes/CfgWeapons/bomb_weapons.hpp
  A3A/addons/config_fixes/Stringtable.xml
  A3A/addons/config_fixes/config.cpp
  A3A/addons/config_fixes/script_component.hpp
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBomb.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRun.sqf
Labels: enhancement, Ready for merge
