Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-12, with the labels that each got.

#3078 Move FF damage notifications into evaluateEvent (master)
  A3A/addons/core/functions/Punishment/fn_punishment.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
Labels: Bug, Refactor, Ready for merge

#3076 Isladuala kujari testing week fixes
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/mission.sqm
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: Bug, Ready for merge

#3079 Minor fixes for breaching vehicles
  A3A/addons/core/functions/Base/fn_startBreachVehicle.sqf
Labels: Bug, Ready for merge

#3086 Fixed: itemprice of packed object not extended to package.
  A3A/addons/logistics/Private/fn_packObject.sqf
Labels: Bug, Ready for merge

#3087 Add and Update KAM Support for KAM 2.13.3
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
Labels: Enhancement, Ready for merge

#3088 Update ACE Food Item (Add bananas)
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
Labels: Enhancement, Ready for merge

#3090 Miscellaneous logs fix for garage
  A3A/addons/garage/Public/fn_addVehicle.sqf
  A3A/addons/garage/Public/fn_addVehiclesByClass.sqf
Labels: Ready for merge

#3092 Bugfix: broke patrol max distance check in #3031
  A3A/addons/core/functions/CREATE/fn_AAFroadPatrol.sqf
Labels: Ready for merge

#3093 Fix garrison spawning case where all buildings are destroyed
  A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
Labels: Bug, Ready for merge

#3053 Fix ACE fuel state not being correctly set on ungaraging
  A3A/addons/garage/StatePreservation/fn_setFuel.sqf
Labels: Bug, Ready for merge
