Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-09, with the labels that each got.

#2930 Add GM Assets
  A3A/addons/core/functions/init/fn_initZones.sqf
Labels: change, Ready for merge

#2928 Retextured RHS Mi8's to chdkz camo
  A3A/addons/config_fixes/RHS/chdkz_rhs.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
Labels: Ready for merge

#2829 Add member & guest lock limits to garage
  A3A/addons/garage/CfgFunctions.hpp
  A3A/addons/garage/Core/fn_getLockCount.sqf
  A3A/addons/garage/Core/fn_toggleLock.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/garage/Public/fn_addVehicle.sqf
  A3A/addons/garage/Stringtable.xml
Labels: enhancement, Ready for merge

#2941 Add files via upload
  .github/workflows/syncStringtables.yml
  Tools/antistasi_translation_sync-0.5.0-py3-none-any.whl
Labels: localisation, CI\CD

#2944 Update debug.hpp
  A3A/addons/maps/MissionDescription/debug.hpp
Labels: Ready for merge

#2945 Land_Cargo_HQ_V4_F addition
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
Labels: change, Ready for merge

#2942 Autumn cleaning - multiple small changes and fixes
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_POL_Arctic.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_POL_Arid.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_POL_Temperate.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV_Arctic.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV_Arid.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV_Temperate.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Arctic.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Arid.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm
  A3A/addons/maps/Antistasi_tem_anizay.tem_anizay/mapInfo.hpp
Labels: Bug-fix, Ready for merge

#2863 Better GC Tracking
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
Labels: change, Ready for merge

#2890 Added self-revive and modified damage system
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
  A3A/addons/core/functions/EventHandler/fn_enemyUnitKilledEH.sqf
  A3A/addons/core/functions/Revive/fn_actionRevive.sqf
  A3A/addons/core/functions/Revive/fn_calcVestDamageAdj.sqf
  A3A/addons/core/functions/Revive/fn_fatalWound.sqf
  A3A/addons/core/functions/Revive/fn_handleDamage.sqf
  A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf
  A3A/addons/core/functions/Revive/fn_respawn.sqf
  A3A/addons/core/functions/Revive/fn_selfRevive.sqf
  A3A/addons/core/functions/Revive/fn_selfReviveReset.sqf
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
  A3A/addons/core/functions/Revive/fn_unconsciousAAF.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
Labels: Bug, Change, Enhancement, Ready for merge

#2947 Fix Huron (vanilla Chinook-like) not using gear on combat landing
  A3A/addons/core/functions/AI/fn_combatLanding.sqf
Labels: Bug, Ready for merge

#2931 Vanilla DLC & WS CDLC Vehicles
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf
Labels: Ready for merge, Templates
