Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-10, with the labels that each got.

#2956 Move headless clients with HQ to theoretically improve AI responses
  A3A/addons/core/functions/Base/fn_relocateHQObjects.sqf
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Change, Ready for merge

#2955 Update RHS_AI_ChDKZ
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
Labels: Ready for merge

#2960 Add vehiclesLightTanks template category
  A3A/addons/core/Templates/Templates/FactionDefaults/EnemyDefaults.sqf
  A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Enhancement

#2950 Adds logistics nodes for WS offroads
  A3A/addons/logistics/Nodes/WS.hpp
Labels: Ready for merge

#2933 Militia offroads & civilian CH-49 Retextures
  A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp
  A3A/addons/config_fixes/Vanilla/air.hpp
  A3A/addons/config_fixes/Vanilla/config.cpp
  A3A/addons/config_fixes/Vanilla/soft.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
Labels: Ready for merge, Templates

#2959 Fix RPT error when admin disconnects
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug

#2932 Vanilla DLC Weapons
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
Labels: Ready for merge, Templates

#2961 Stringtable fixes
  A3A/addons/core/Stringtable.xml
  A3A/addons/logistics/Stringtable.xml
Labels: Localisation, Ready for merge

#2919 CUP civilian vehicles pack
  A3A/addons/core/Templates/AddonVics.hpp
  A3A/addons/core/Templates/AddonVics/cup_veh_Civ.sqf
Labels: Change, Enhancement, Ready for merge

#2974 Fix missing comma in CUP civ vehicles addon
  A3A/addons/core/Templates/AddonVics/cup_veh_Civ.sqf
Labels: Bug

#2975 Prevent high command squad icons from being visible in 3d display
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Change, Ready for merge

#2977 Carry, rotate and loot to crate stringtable fixes
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
Labels: Priority, Bug, Ready for merge

#2979 Fix non-basic backpack in SPE FFF rebel template
  A3A/addons/core/Templates/Templates/SPE/SPE_REB_FFF.sqf
Labels: Bug, Ready for merge

#2936 Western Sahara North Africa CSAT template
  A3A/addons/config_fixes/Vanilla/air.hpp
  A3A/addons/config_fixes/Vanilla/armor.hpp
  A3A/addons/config_fixes/Vanilla/soft.hpp
  A3A/addons/config_fixes/WS/CfgVehicles.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Vehicle_Attributes.sqf
Labels: Ready for merge, Templates

#2937 Western Sahara Arganian Defence Force template
  A3A/addons/config_fixes/Vanilla/armor.hpp
  A3A/addons/config_fixes/Vanilla/soft.hpp
  A3A/addons/config_fixes/WS/CfgVehicles.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
Labels: Ready for merge, Templates

#2938 Western Sahara SFIA template
  A3A/addons/config_fixes/Vanilla/air.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
Labels: Ready for merge, Templates

#2939 Western Sahara ION Services template
  A3A/addons/config_fixes/Vanilla/air.hpp
  A3A/addons/config_fixes/Vanilla/soft.hpp
  A3A/addons/config_fixes/WS/CfgVehicles.hpp
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
Labels: Ready for merge, Templates

#2686 Add Ace ropes to the starting Arsenal.
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
  A3A/addons/core/functions/init/fn_initACE.sqf
Labels: Enhancement, Ready for merge

#2983 Fix missing semicolon in initACE ropeDeployed handler
  A3A/addons/core/functions/init/fn_initACE.sqf
Labels: Priority, Bug, Ready for merge

#2982 config_fixes-cleanup
  A3A/addons/config_fixes/CUP/config.cpp
  A3A/addons/config_fixes/CfgMagazines.hpp
  A3A/addons/config_fixes/CfgVehicles.hpp
  A3A/addons/config_fixes/CfgWeapons.hpp
  A3A/addons/config_fixes/RHS/CfgVehicles.hpp
  A3A/addons/config_fixes/RHS/chdkz_rhs.hpp
  A3A/addons/config_fixes/RHS/config.cpp
  A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp
  A3A/addons/config_fixes/Vanilla/air.hpp
  A3A/addons/config_fixes/Vanilla/armor.hpp
  A3A/addons/config_fixes/Vanilla/config.cpp
  A3A/addons/config_fixes/Vanilla/sea.hpp
  A3A/addons/config_fixes/Vanilla/soft.hpp
  A3A/addons/config_fixes/WS/CfgMarkers.hpp
  A3A/addons/config_fixes/WS/CfgVehicles.hpp
  A3A/addons/config_fixes/WS/config.cpp
  A3A/addons/config_fixes/WS/ws_ion.hpp
  A3A/addons/config_fixes/bomb_weapons.hpp
  A3A/addons/config_fixes/config.cpp
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
Labels: Refactor, Ready for merge

#2953 3CB FIA & TKM Starting enfields
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf
Labels: Ready for merge

#2984 Fixed loadout validation in WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
Labels: Bug, Ready for merge

#2987 Fix theBoss var not being published in autostart case
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug, Ready for merge

#2988 playtesting fixes
  A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
  A3A/addons/core/functions/Builder/fn_initBuilderMonitors.sqf
  A3A/addons/core/functions/Builder/fn_placeBuilderObjects.sqf
Labels: Bug, Change, Ready for merge

#2990 Fix missing semicolon in placeBuilderObjects
  A3A/addons/core/functions/Builder/fn_placeBuilderObjects.sqf
Labels: Priority, Bug, Ready for merge

#2978 ACE 3.16.0 stuff
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
  A3A/addons/core/functions/Base/fn_startBreachVehicle.sqf
  A3A/addons/core/functions/Builder/fn_addBuildingActions.sqf
  A3A/addons/core/functions/Builder/fn_buildingPlacerStart.sqf
  A3A/addons/core/functions/Builder/fn_initBuilderMonitors.sqf
  A3A/addons/core/functions/Intel/fn_placeIntel.sqf
  A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
  A3A/addons/core/functions/Utility/fn_isEngineer.sqf
  A3A/addons/garage/Extras/fn_isRepairSource.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
Labels: Change, Ready for merge

#2993 Fix build placer permissions
  A3A/addons/core/functions/Builder/fn_buildingPlacerStart.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#2994 Zeus logging spam fixes
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initZeusLogging.sqf
Labels: Bug, Change, Ready for merge, Data Lock Approved

#2996 Fix building repair not working on MP clients
  A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
  A3A/addons/core/functions/Builder/fn_lockBuilderBox.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#2997 SPE panzerfaust and mortyAI fixes
  A3A/addons/core/Templates/Templates/SPE/SPE_REB_FFF.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
  A3A/addons/core/functions/AI/fn_mortyAI.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#2998 Fix HC icons being visible after leaving HC mode
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#3001 Map fixes
  A3A/addons/maps/Antistasi_Enoch.Enoch/mission.sqm
  A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm
Labels: Change

#3003 Add routine for better spawning of high command vehicles
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf
  A3A/addons/core/functions/REINF/fn_spawnHCVeh.sqf
  A3A/addons/core/functions/Utility/fn_boxCollisionCheck.sqf
Labels: Enhancement, Ready for merge, Data Lock Approved

#3004 fixed base weapon Vektor R5 GL
  A3A/addons/config_fixes/WS/CfgWeapons.hpp
  A3A/addons/config_fixes/WS/config.cpp
Labels: Ready for merge, Data Lock Approved

#3006 Manually force building placement to nearby composite surface normal
  A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
Labels: Enhancement, Ready for merge, Data Lock Approved

#3007 Localized parameters
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/maps/MissionDescription/params.hpp
  A3A/addons/maps/Stringtable.xml
Labels: Localisation, Ready for merge, Data Lock Approved

#3008 arifle_AK12_GL_lush_F
  A3A/addons/config_fixes/Vanilla/CfgWeapons.hpp
  A3A/addons/config_fixes/Vanilla/config.cpp
Labels: Ready for merge, Data Lock Approved

#3010 Western sahara template update
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
Labels: Ready for merge, Data Lock Approved

#3011 Fix ACE setName spam and JIP error
  A3A/addons/core/functions/Utility/fn_setIdentityLocal.sqf
Labels: Bug, Performance, Ready for merge, Data Lock Approved

#3012 Add ACE_suture to initial rebel equipment
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
Labels: Enhancement, Ready for merge, Data Lock Approved

#3013 Fix basic/medical gear missing in SPE/IFA FFF rebel faction
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Bug, Ready for merge, Data Lock Approved

#3015 todo comments
  A3A/addons/core/functions/Ammunition/fn_ammunitionTransfer.sqf
  A3A/addons/core/functions/Base/fn_AILoadInfo.sqf
  A3A/addons/core/functions/Base/fn_NATOFT.sqf
  A3A/addons/core/functions/Base/fn_garrisonInfo.sqf
  A3A/addons/core/functions/Base/fn_localizar.sqf
  A3A/addons/core/functions/Base/fn_markerChange.sqf
  A3A/addons/core/functions/Base/fn_resourcesFIA.sqf
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
  A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
  A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
  A3A/addons/core/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/core/functions/Dialogs/fn_squadOptions.sqf
  A3A/addons/core/functions/Dialogs/fn_squadRecruit.sqf
  A3A/addons/core/functions/Dialogs/fn_unit_recruit.sqf
  A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
  A3A/addons/core/functions/OrgPlayers/fn_theBossTransfer.sqf
  A3A/addons/core/functions/Punishment/fn_punishment.sqf
  A3A/addons/core/functions/REINF/fn_buildMinefield.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf
  A3A/addons/core/functions/Supports/fn_showInterceptedSetupCall.sqf
  A3A/addons/core/functions/Supports/fn_showInterceptedSupportCall.sqf
  A3A/addons/core/functions/init/fn_credits.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/gui/functions/GUI/fn_aiManagementTab.sqf
  A3A/addons/gui/functions/GUI/fn_hqDialog.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupLoadgameTab.sqf
Labels: Localisation, Ready for merge, Data Lock Approved

#3016 Fix some weird/broken UI config dependencies
  A3A/addons/garage/defines.hpp
  A3A/addons/gui/config.cpp
  A3A/addons/gui/dialogues/arsenalLimitsDialog.hpp
Labels: Bug, Ready for merge, Data Lock Approved
