Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-07, with the labels that each got.

#2808 Fix trailing comma and missing AA plane in ION Temperate
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Bug-fix

#2805 Bugfix (Duplicate rebel vehicles/unarmed AFRF tigr) #2779 #2765
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
Labels: Ready for merge

#2790 Fix some RHS flags
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf
  A3A/addons/core/config.cpp
  A3A/addons/core/data/map/markers/flags/cdf_ca.paa
  A3A/addons/core/data/map/markers/flags/napa_ca.paa
  A3A/addons/core/data/map/markers/flags/serbia_ca.paa
Labels: Merge pending

#2809 Fix mismerge of LTC radius parameter PR
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initUtilityItems.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
Labels: Bug-fix, Priority

#2813 Discounted rebel 7.62 and 5.56 vics & statics
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
Labels: enhancement, Ready for merge

#2816 Don't place units or statics on destroyed buildings
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
  A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
Labels: Bug-fix, Ready for merge

#2818 Don't spam hints on top of setup UI
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: change, Ready for merge

#2817 Fix undercover backpack exploit
  A3A/addons/core/functions/AI/fn_undercoverAI.sqf
Labels: bug, enhancement, Ready for merge, Exploit

#2794 Rudimentary Sog 1.3 Update
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Ready for merge, Templates

#2750 Add Zeus Logs
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/core/functions/init/fn_initZeusLogging.sqf
Labels: Ready for merge

#2833 Fix typos in lightAPC & IFV categorization
  A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
Labels: Bug-fix, Ready for merge

#2838 Support/resource balance tweaks:
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
Labels: Ready for merge, Balance

#2839 Rebalance mission effects on enemy resources
  A3A/addons/core/functions/Base/fn_timingCA.sqf
  A3A/addons/core/functions/Missions/fn_AS_Official.sqf
  A3A/addons/core/functions/Missions/fn_AS_specOP.sqf
  A3A/addons/core/functions/Missions/fn_CON_Outpost.sqf
  A3A/addons/core/functions/Missions/fn_DES_Antenna.sqf
  A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
  A3A/addons/core/functions/Missions/fn_DES_Vehicle.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Ammo.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Bank.sqf
  A3A/addons/core/functions/Missions/fn_REP_Antenna.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
Labels: Ready for merge, Balance

#2796 RHS Chdkz AI template
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Pictures/Markers/cdf_ca.paa
  A3A/addons/core/Pictures/Markers/chdkz_co.paa
  A3A/addons/core/Pictures/Markers/napa_ca.paa
  A3A/addons/core/Pictures/Markers/serbia_ca.paa
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Vehicle_Attributes.sqf
Labels: Ready for merge, Templates

#2840 Add CAS planes used by chdkz to setPlaneLoadout
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Labels: Bug-fix, Ready for merge

#2832 Check client vs server version on init
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: enhancement, Ready for merge

#2843 Chdzk tank-flag quick-fix, crew update
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
Labels: Ready for merge

#2819 Chernarus2020 port
  A3A/addons/core/data/map/markers/flags/cdf_ca.paa
  A3A/addons/core/data/map/markers/flags/napa_ca.paa
  A3A/addons/core/data/map/markers/flags/serbia_ca.paa
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/cba_settings.sqf
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/description.ext
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/initServer.sqf
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/mapInfo.hpp
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/mission.sqm
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/navGrid.sqf
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: enhancement, Map Issue, Ready for merge

#2846 fixed duplicated https:// in readme link
  A3A/addons/core/Stringtable.xml
  README.md
Labels: Ready for merge

#2848 Spearhead Integration
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/SPE/SPE_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE/SPE_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPE/SPE_CIV.sqf
  A3A/addons/core/Templates/Templates/SPE/SPE_REB_FFF.sqf
  A3A/addons/core/Templates/Templates/SPE/flag_fr.paa
  A3A/addons/core/Templates/Templates/SPE/flag_ger.paa
  A3A/addons/core/Templates/Templates/SPE/flag_us.paa
  A3A/addons/core/Templates/Templates/SPE/spe_logo.paa
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_CIV.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/flag_fr.paa
  A3A/addons/core/Templates/Templates/SPE_IFA/flag_ger.paa
  A3A/addons/core/Templates/Templates/SPE_IFA/flag_us.paa
  A3A/addons/core/Templates/Templates/SPE_IFA/spe_ifa_logo.paa
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initSpawnPlaces.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/core/functions/init/fn_initZones.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_itemType.sqf
  A3A/addons/logistics/Cargo/SPE.hpp
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/D3S.hpp
  A3A/addons/logistics/Nodes/SPE.hpp
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/Pictures/Mission/whiteboard.paa
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/cba_settings.sqf
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/description.ext
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/initServer.sqf
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/mapInfo.hpp
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/mission.sqm
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/navGrid.sqf
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: change, enhancement, Ready for merge

#2853 Change SPE-IFA militia cars to kubelwagens, fix unarmed car navigation bug
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
Labels: Bug-fix, change, Ready for merge

#2852 Fix arsenal loadout loading broken by SPE fakemag check
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_itemType.sqf
Labels: Bug-fix, Priority, Ready for merge

#2854 changelog and version update
  A3A/addons/core/Includes/script_version.hpp
  changelog.rst
Labels: Bug-fix, Ready for merge

#2855 Unstable to Master for 3.3.1 hotfix release
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_itemType.sqf
  changelog.rst
Labels: Bug-fix

#2856 Fix unarmed militia vehicles being used in roadblocks
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
Labels: Bug-fix, Priority, Ready for merge

#2861 Simplifying map placed objects - Normandy
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/mission.sqm
Labels: change, Map Issue, Ready for merge

#2872 Block units from spawning in additional SPE bocage mounds
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
Labels: change, Ready for merge

#2874 Various vehicle/static save fixes
  A3A/addons/core/functions/REINF/fn_addFIAveh.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
Labels: Bug-fix, Priority, Ready for merge

#2877 Update Stringtable.xml
  A3A/addons/core/Stringtable.xml
Labels: Bug-fix, localisation, Ready for merge
