Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-05, with the labels that each got.

#2753 additional GM template stuff
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
Labels: Bug-fix, Ready for merge

#2751 Korean translation improved
  A3A/addons/core/Stringtable.xml
  A3A/addons/garage/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
Labels: localisation

#2762 Fix units being inappropriately revealed to garrisons
  A3A/addons/core/functions/CREATE/fn_FIAinitBASES.sqf
  A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
Labels: bug, performance, Ready for merge

#2763 Remove debug marker
  A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm
Labels: Bug-fix

#2754 updated GM templates with new assets
  A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
  A3A/addons/core/Templates/Templates/GM/GM_AI_BW_arctic.sqf
  A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
  A3A/addons/core/Templates/Templates/GM/GM_AI_NVA_arctic.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
  A3A/addons/logistics/Nodes/GM.hpp
Labels: enhancement, Ready for merge

#2764 3.2 preliminary changelog
  changelog.rst
Labels: Ready for merge, Review pending
