Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-04, with the labels that each got.

#2546 More vehicles for rebels (BUY_ITEM_VEHICLE PART 3)
  A3A/addons/Logistics/Packable/Vanilla.hpp
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/AI/fn_landThreatEval.sqf
  A3A/addons/core/functions/AI/fn_mineSweep.sqf
  A3A/addons/core/functions/AI/fn_mortyAI.sqf
  A3A/addons/core/functions/AI/fn_staticAutoT.sqf
  A3A/addons/core/functions/Base/fn_airspaceControl.sqf
  A3A/addons/core/functions/Base/fn_createOutpostsFIA.sqf
  A3A/addons/core/functions/Base/fn_moveHQ.sqf
  A3A/addons/core/functions/Base/fn_outpostDialog.sqf
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_createFIAOutposts2.sqf
  A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf
  A3A/addons/core/functions/CREATE/fn_createSDKgarrisonsTemp.sqf
  A3A/addons/core/functions/Dialogs/fn_buyVehicle.sqf
  A3A/addons/core/functions/Dialogs/fn_buyVehicleCiv.sqf
  A3A/addons/core/functions/Dialogs/fn_createDialog_setParams.sqf
  A3A/addons/core/functions/Dialogs/fn_mineDialog.sqf
  A3A/addons/core/functions/Dialogs/fn_squadOptions.sqf
  A3A/addons/core/functions/Dialogs/fn_squadRecruit.sqf
  A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
  A3A/addons/core/functions/REINF/fn_NATObomb.sqf
  A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf
  A3A/addons/core/functions/REINF/fn_buildMinefield.sqf
  A3A/addons/core/functions/REINF/fn_dismissSquad.sqf
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/core/functions/REINF/fn_garrisonDialog.sqf
  A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
  A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/garage/Public/fn_callbackHandler.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
  A3A/addons/logistics/Private/fn_unpackObject.sqf
Labels: change, enhancement, Ready for merge

#2682 2652 - Czech and German translations
  A3A/addons/core/Stringtable.xml
Labels: enhancement, localisation, Review pending

#2689 Add ACE Hearing reset to Vehicle Box
  A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
Labels: enhancement, Ready for merge

#2690 Fix bunkers being counted as static weapons for rebel AI manning
  A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
Labels: Bug-fix, Ready for merge

#2692 Delete A3A/addons/Logistics/Packable directory
  A3A/addons/Logistics/Packable/Vanilla.hpp
Labels: Bug-fix, Ready for merge

#2695 Limit spawn distance and civ limit settings to admins
  A3A/addons/core/dialogs.hpp
Labels: Bug-fix, Ready for merge

#2696 Temp fix for buyItems
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
  A3A/addons/logistics/Private/fn_unpackObject.sqf
Labels: Bug-fix, Ready for merge

#2702 Fix garage static weapon vehicle swap exploit
  A3A/addons/garage/Extras/fn_reloadMounts.sqf
Labels: Bug-fix, Ready for merge, Exploit

#2697 Workaround Arma bug with moveInAny
  A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
Labels: Bug-fix, Ready for merge

#2699 Fix support mortar spawn places
  A3A/addons/core/functions/EventHandler/fn_vehicleDeletedEH.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, Priority, Ready for merge

#2700 Fix inmuneConvoy running its bridge hack after reaching its objective
  A3A/addons/core/functions/AI/fn_inmuneConvoy.sqf
Labels: Bug-fix, Ready for merge

#2705 Fix Unsung radio detection
  A3A/addons/core/functions/Ammunition/fn_hasARadio.sqf
Labels: Bug-fix, Ready for merge

#2707 Fix ASF loiter altitude
  A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf
Labels: Bug-fix, Ready for merge

#2710 Rotate Item Fix
  A3A/addons/core/functions/UtilityItems/fn_initMovableObject.sqf
Labels: Bug-fix, Ready for merge

#2706 Add more vehicle tabs to the gui
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/buyVehicleDialog.hpp
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/functions/GUI/fn_buyVehicleDialog.sqf
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
Labels: change, enhancement, Ready for merge

#2715 Fix incorrect addTimeForIdle
  A3A/addons/core/functions/Base/fn_distance.sqf
Labels: Bug-fix, Priority, Ready for merge

#2714 Fix support mortars not entering active info correctly
  A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
Labels: Bug-fix, Ready for merge

#2720 Fixing rotations again
  A3A/addons/core/functions/UtilityItems/fn_rotateItem.sqf
Labels: Bug-fix, Ready for merge

#2719 Fix undercover for civ planes
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: change, Ready for merge

#2722 Change SU-230 models depending on the gun
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ADA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ANA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_HIDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_KRG.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_MDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_Mix.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_West.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
Labels: Ready for merge

#2723 Remote exec packing
  A3A/addons/logistics/CfgFunctions.hpp
  A3A/addons/logistics/Private/fn_packObject.sqf
  A3A/addons/logistics/Private/fn_unpackObjectAction.sqf
Labels: Ready for merge

#2724 Fix case where napalm bomb lands before spawn runs
  A3A/addons/core/functions/AI/fn_airbomb.sqf
Labels: Bug-fix, Ready for merge

#2727 Workaround some bad GL configs
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf
Labels: Bug-fix

#2716 🚚(cont.)Bank/Convoy truck convertation to template variable
  A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
  A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3A/addons/core/functions/Convoy/fn_createAIAction.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Bank.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Supplies.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Needs Testing, Refactor, Testing needed

#2735 Fix freak case where mrkWIN can flip the wrong marker
  A3A/addons/core/functions/Base/fn_mrkWIN.sqf
Labels: Bug-fix, Ready for merge

#2734 Add lost Fliegerfaust magazine
  A3A/addons/core/Templates/Templates/BWA3/BWA3_AI_BW_Arid.sqf
  A3A/addons/core/Templates/Templates/BWA3/BWA3_AI_BW_Temperate.sqf
Labels: Bug-fix, change, Ready for merge, Templates

#2731 Support response tweaks
  A3A/addons/core/functions/Base/fn_markerChange.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf
  A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Bug-fix, change, Ready for merge

#2730 Undercover fixes
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
Labels: Bug-fix, Ready for merge

#2736 Prevent HC squads reboarding to travel after an explicit dismount order
  A3A/addons/core/functions/AI/fn_attackDrillAI.sqf
  A3A/addons/core/functions/REINF/fn_vehStats.sqf
Labels: change, Ready for merge

#2725 Rework Petros death handling
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_createPetros.sqf
  A3A/addons/core/functions/Base/fn_initPetros.sqf
  A3A/addons/core/functions/Base/fn_petrosDeathMonitor.sqf
  A3A/addons/core/functions/Base/fn_placementselection.sqf
Labels: Bug-fix, Ready for merge

#2740 Fix crate transfer not updating arsenal unlocks with new items
  A3A/addons/core/functions/Ammunition/fn_arsenalManage.sqf
Labels: Bug-fix, Ready for merge

#2741 Prevent use of ACE grenade throwing near HQ
  A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf
Labels: enhancement, Ready for merge, Exploit

#2742 change vehiclemarker error to info
  A3A/addons/core/functions/init/fn_initSpawnPlaces.sqf
Labels: Bug-fix, Ready for merge

#2744 map error fixes
  A3A/addons/maps/Antistasi_Altis.Altis/mission.sqm
  A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm
  A3A/addons/maps/Antistasi_Takistan.takistan/mission.sqm
  A3A/addons/maps/Antistasi_Tanoa.Tanoa/mission.sqm
  A3A/addons/maps/Antistasi_cam_lao_nam.cam_lao_nam/mission.sqm
Labels: Bug-fix, Map Issue, Ready for merge

#2745 Test-fix for establishing a roadblock using remote control
  A3A/addons/core/functions/Base/fn_createOutpostsFIA.sqf
Labels: Bug-fix
