Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2023-02, with the labels that each got.

#2643 Vehicle Arsenal dupe fix
  A3A/addons/jeroen_arsenal/JNA/fn_vehicleArsenal.sqf
Labels: bug, Ready for merge, Exploit

#2646 Petros' new drip - Antistasi Berets
  A3A/addons/gear/$PBOPREFIX$
  A3A/addons/gear/CfgPatches.hpp
  A3A/addons/gear/CfgVehicles.hpp
  A3A/addons/gear/CfgWeapons.hpp
  A3A/addons/gear/Stringtable.xml
  A3A/addons/gear/config.cpp
  A3A/addons/gear/headgear/CfgVeh_headgear.hpp
  A3A/addons/gear/headgear/CfgWea_headgear.hpp
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01.rvmat
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_01.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_01_ca.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_02.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_02_ca.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_03.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_03_ca.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_04.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_04_ca.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_nohq.paa
  A3A/addons/gear/headgear/beret_01/data/a3a_g_beret_01_smdi.paa
  A3A/addons/gear/script_component.hpp
Labels: enhancement, Ready for merge

#2626 Automatic GC
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: enhancement, Ready for merge

#2627 minor resourcecheck old code cleanup
  A3A/addons/core/functions/CREATE/fn_CIVinit.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
Labels: Refactor, Ready for merge

#2625 Ensure cargo turrets (eg. door guns) are crewed
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_createVehicleCrew.sqf
Labels: Bug-fix, Ready for merge

#2645 Silent server setup notifi. + custom hint dismiss tip local.
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/UI/fn_customHintRender.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: change, Ready for merge
