Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2024-05, with the labels that each got.

#3204 RF Compatibility - WS Templates
  A3A/addons/config_fixes/RF/CfgVehicles.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
  A3A/addons/logistics/Nodes/RF.hpp
Labels: Enhancement, Ready for merge, Templates

#3227 Moving Airplane loadouts to configs
  A3A/addons/core/Templates/AircraftLoadouts/3CB/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/CUP/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/RHS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/SPE/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/Tornado_AWS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/UNS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/VN/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/Vanilla/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/WS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/config.cpp
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
Labels: Change, Ready for merge

#3237 Garage Sell Button
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_getVehicleSellPrice.sqf
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
  A3A/addons/garage/CfgDefines.inc
  A3A/addons/garage/CfgFunctions.hpp
  A3A/addons/garage/Core/fn_onLoad.sqf
  A3A/addons/garage/Core/fn_removeFromPool.sqf
  A3A/addons/garage/Core/fn_requestSelectionChange.sqf
  A3A/addons/garage/Core/fn_sellVehGRG.sqf
  A3A/addons/garage/Core/fn_sellVehGRGLocal.sqf
  A3A/addons/garage/Core/fn_toggleLock.sqf
  A3A/addons/garage/Dialogs.hpp
  A3A/addons/garage/Extras/fn_findMount.sqf
  A3A/addons/garage/Extras/fn_reloadExtras.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/garage/Stringtable.xml
Labels: Enhancement, Ready for merge

#3251 Fix breaking error in citySupportChange type-safety checks
  A3A/addons/core/functions/Base/fn_citySupportChange.sqf
Labels: Priority, Bug, Ready for merge

#3172 RHS & 3CB: A-29 & T-28 CAS plane fix
  A3A/addons/core/Templates/AircraftLoadouts/3CB/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/RHS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/config.cpp
  A3A/addons/core/Templates/Templates/3CB/3CBFactions_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_HIDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_MDF.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRun.sqf
Labels: Change, Ready for merge, Templates

#3242 Cargo nodes for 3CB Hilux (Covered)
  A3A/addons/logistics/Nodes/3CBFactions.hpp
Labels: Bug, Ready for merge

#3252 Removed testing code
  A3A/addons/core/Templates/AircraftLoadouts/Vanilla/config.cpp
Labels: Priority, Bug, Ready for merge

#3254 Refugee mission timer fix
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Missions/fn_RES_Refugees.sqf
Labels: Bug, Ready for merge

#3258 "Re-adds" the RPD to the 3CB SOV template
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_SOV.sqf
Labels: Bug, Ready for merge, Templates

#3233 Switch respawn & self-revive keys to custom keybinds
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Revive/fn_respawn.sqf
  A3A/addons/core/functions/Revive/fn_selfRevive.sqf
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
  A3A/addons/core/keybinds/CfgDefaultKeysPresets.hpp
  A3A/addons/core/keybinds/CfgUserActions.hpp
  A3A/addons/core/keybinds/UserActionGroups.hpp
  A3A/addons/core/keybinds/UserActionsConflictGroups.hpp
Labels: Enhancement, Ready for merge

#3259 Parachutes in airbase crates
  A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
Labels: Enhancement, Ready for merge

#3261 Adding a few RHS items to GC
  A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
Labels: Bug, Low priority, Ready for merge

#3264 Fix lootToCrate issues with IFA gear
  A3A/addons/core/functions/LTC/fn_lootToCrate.sqf
Labels: Bug, Ready for merge
