Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2024-09, with the labels that each got.

#3182 Adds 3CB CSAT Scimitar, Gryphon, Bear, and Viper regiment
  A3A/addons/core/Templates/AircraftLoadouts/3CB/config.cpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Bru.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Bru_S.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Bru_U.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Bru_W.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Chi.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Chi_G.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Chi_N.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Fre.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Per.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Per_B.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Per_F.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_CSAT/3CB_AI_CSAT_Per_M.sqf
Labels: Ready for merge, Templates

#3376 More frequent militia vehicles/transports early game
  A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
  A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf
Labels: Suggestion, Ready for merge, Balance

#3386 Flatten out support responses and block support calls for mine kills
  A3A/addons/core/functions/AI/fn_callForSupport.sqf
  A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
Labels: Bug, Ready for merge, Balance, Testing needed

#3388 Implement mortar/artillery support ranging shot and walking barrage
  A3A/addons/core/functions/Supports/fn_SUP_artillery.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
  A3A/addons/core/functions/Supports/fn_requestSupport.sqf
Labels: Ready for merge, Balance

#3390 Fix HQ actions being available through remote controls
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/garage/Public/fn_initGarage.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_init.sqf
Labels: Bug, Ready for merge

#3393 Fix skill upgrade tooltip not updating
  A3A/addons/core/functions/REINF/fn_FIAskillAdd.sqf
Labels: Bug, Ready for merge

#3395 Fix errors caused by tags function
  A3A/addons/core/functions/init/fn_tags.sqf
Labels: Bug, Ready for merge

#3397 Fix arsenal not clearing client IDs on disconnect
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug, Ready for merge

#3402 Prevent rebels AIs being equipped with VN melee weapons
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
Labels: Bug, Ready for merge

#3406 Fix base class for srifle_GM6_snake_lxWS
  A3A/addons/config_fixes/WS/CfgWeapons.hpp
Labels: Bug, Ready for merge

#3389 Injector success and UID logging
  A3A/addons/core/functions/init/fn_initACE.sqf
Labels: Change, Enhancement, Ready for merge
