Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2024-03, with the labels that each got.

#3184 CDLC compatiblity - Reaction Forces
  A3A/addons/config_fixes/RF/CfgVehicles.hpp
  A3A/addons/config_fixes/RF/config.cpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Civ.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/RF.hpp
Labels: Enhancement, Templates

#3136 Avoid spamming unlockedXXX publicVariables
  A3A/addons/core/functions/Ammunition/fn_arsenalManage.sqf
  A3A/addons/core/functions/Ammunition/fn_unlockEquipment.sqf
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Performance, Ready for merge

#3154 Fix case where loadout_addItems loses magazines
  A3A/addons/core/functions/Templates/Loadouts/fn_loadout_addItems.sqf
Labels: Bug, Ready for merge

#3162 Minor fixes 20240302
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Bug, Change, Ready for merge

#3167 Removed old Kajman & Orca version from CSAT
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
Labels: Bug, Ready for merge, Templates

#3170 3CB Weapons & New Stuff Patch
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ADA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ANA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arctic.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Tropical.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_SOV.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_US.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_HIDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_KRG.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_MDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_East.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_Mix.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Civ_CHC.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Civ_TKC.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_ION.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/logistics/Cargo/3CBFactions.hpp
  A3A/addons/logistics/Nodes/3CBFactions.hpp
Labels: Bug, Change, Ready for merge, Templates

#3175 WS minuscule patch
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
Labels: Bug, Low priority, Ready for merge

#3152 Params for no fast travel and no box restore
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Enhancement, Ready for merge

#3179 RHS ChDKZ T-72 Event Handler Inheritance
  A3A/addons/config_fixes/RHS/chdkz_rhs.hpp
Labels: Bug, Ready for merge

#3177 Vanilla UK/NATO faction
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Tropical.sqf
Labels: Change, Ready for merge, Templates

#3176 Vanilla ION pmc faction
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_PMC.sqf
Labels: Change, Ready for merge, Templates

#3185 CDLC Compatibility - Reaction Forces
  A3A/addons/config_fixes/RF/CfgVehicles.hpp
  A3A/addons/config_fixes/RF/config.cpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Civ.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/RF.hpp
Labels: Enhancement, Ready for merge, Templates

#3190 3.5.2 changelog and version
  A3A/addons/core/Includes/script_version.hpp
  README.md
  changelog.rst
Labels: Ready for merge
