Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2024-08, with the labels that each got.

#3327 Reduce artillery/mortar ratio at high war tiers
  A3A/addons/core/functions/Supports/fn_SUP_artilleryAvailable.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortarAvailable.sqf
Labels: Ready for merge, Balance

#3335 Improve CUP and IFA plane turn rates when flown by AI
  A3A/addons/config_fixes/CUP/CfgVehicles.hpp
  A3A/addons/config_fixes/IFA/CfgVehicles.hpp
Labels: Change, Ready for merge

#3338 Fix slow-server UI issue and incorrect licensing in arsenal limits
  A3A/addons/gui/dialogues/arsenalLimitsDialog.hpp
  A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf
Labels: Bug, Ready for merge

#3343 Slow down self-revive timeout when downed
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
Labels: Change, Ready for merge, Exploit

#3337 Default Arsenal Magazine Limits
  A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_init.sqf
Labels: Change, Ready for merge

#3359 Fix issue where running destroyCity with CUP interiors could crash
  A3A/addons/core/functions/Base/fn_destroyCity.sqf
Labels: Bug, Ready for merge

#3362 Disallow sling-loading HQ objects
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug, Ready for merge, Exploit

#3363 Remove CUP Cluster MLRS
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_HIL.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
Labels: Bug, Change, Ready for merge

#3364 Workaround Arma bug with CDLC detection and arma3.cfg mod loading method
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
Labels: Bug, Ready for merge

#3367 Fix support crew being provided for free and then refunded
  A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_UAVRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_artillery.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
Labels: Bug, Ready for merge

#3369 Seaport Ammobox Protection
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/logistics/Private/fn_addAction.sqf
  A3A/addons/logistics/Public/fn_addLoadAction.sqf
Labels: Bug, Enhancement, Ready for merge, Exploit

#3356 SPE_IFA 1.1 Template Updates
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_CIV.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_Vehicle_Attributes.sqf
  A3A/addons/logistics/Nodes/SPE.hpp
Labels: Change, Enhancement, Ready for merge, Templates

#3365 Very small sell price rework
  A3A/addons/core/functions/Base/fn_getVehicleSellPrice.sqf
Labels: Bug, Change, Ready for merge, Exploit

#3371 Spearhead 1944 1.1 - Mortain Map Port
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupDialog.sqf
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/Pictures/Mission/whiteboard.paa
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/cba_settings.sqf
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/description.ext
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/initServer.sqf
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/mapInfo.hpp
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/mission.sqm
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/navGrid.sqf
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/onPlayerRespawn.sqf
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/mission.sqm
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: Review pending, Map port

#3349 Create new classes for Antistasi AI units, block those from group join
  A3A/addons/core/CfgVehicles.hpp
  A3A/addons/core/config.cpp
  A3A/addons/core/functions/Templates/fn_compatibilityLoadFaction.sqf
  A3A/addons/core/functions/init/fn_initACE.sqf
Labels: Bug, Performance, Review pending

#3368 Fix inability to rebuild non-outpost radio towers
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_rebuildAssets.sqf
Labels: Bug, Refactor, Review pending

#3372 Make dive bomb runs less accurate against infantry targets
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
Labels: Ready for merge, Balance

#3320 Skip time improvements
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Dialogs/fn_skiptime.sqf
Labels: Bug, Enhancement, Ready for merge

#3370 Add attributeMoreTrucks and IFV-only option to ground transport selection
  A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf
Labels: Ready for merge, Balance

#3373 SPE Rebel template tuned, enemy template adapted for #3370
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
Labels: Change, Ready for merge, Balance, Templates

#3375 Replace all uses of GETOUT waypoints
  A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3A/addons/core/functions/CREATE/fn_patrolReinf.sqf
  A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
Labels: Bug, Ready for merge

#3377 SPE flashlight fix
  A3A/addons/core/CfgVehicles.hpp
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
Labels: Bug, Ready for merge

#3379 Missing semi colon in IFA_SOV lore line.
  A3A/addons/core/Templates/Templates.hpp
Labels: Bug, Ready for merge

#3381 Fix SoldierGB inheritance chain for CBA XEH. Probably.
  A3A/addons/core/CfgVehicles.hpp
Labels: Bug, Ready for merge

#3380 3.7 changelog and version
  A3A/addons/core/Includes/script_version.hpp
  README.md
  changelog.rst
Labels: Ready for merge
