Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2024-06, with the labels that each got.

#3234 Allow guests to use of arsenal limits dialog and set default guest limit to 0
  A3A/addons/core/Params.hpp
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/Save/fn_deleteSave.sqf
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/arsenalLimitsDialog.hpp
  A3A/addons/gui/dialogues/controls.hpp
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_vehicleArsenal.sqf
Labels: Change, Ready for merge

#3250 Rework anti-air support response balance
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_AIreactOnKill.sqf
  A3A/addons/core/functions/Base/fn_addRecentDamage.sqf
  A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
  A3A/addons/core/functions/Base/fn_airspaceControl.sqf
  A3A/addons/core/functions/Base/fn_distance.sqf
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/CREATE/fn_availableBasesAir.sqf
  A3A/addons/core/functions/CREATE/fn_vehKilledOrCaptured.sqf
  A3A/addons/core/functions/OrgPlayers/fn_playerLeash.sqf
  A3A/addons/core/functions/Supports/fn_SUP_ASF.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CAS.sqf
  A3A/addons/core/functions/Supports/fn_SUP_SAM.sqf
  A3A/addons/core/functions/Supports/fn_SUP_SAMAvailable.sqf
  A3A/addons/core/functions/Supports/fn_initSupports.sqf
  A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, Balance

#3257 Remove restriction from AILoadInfo action
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Change, Ready for merge

#3266 Improve getArtilleryRanges, fix IFA mortar case
  A3A/addons/core/functions/Supports/fn_getArtilleryRanges.sqf
Labels: Bug, Ready for merge

#3209 RHS HIDF Template
  A3A/addons/config_fixes/RHS/CfgVehicles.hpp
  A3A/addons/config_fixes/RHS/CfgWeapons.hpp
  A3A/addons/config_fixes/RHS/config.cpp
  A3A/addons/config_fixes/RHS/hidf_rhs.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Vehicle_Attributes.sqf
Labels: Ready for merge, Templates

#3255 Convert corpse/wreck timed cleanup into a server queue with max cap
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_surrenderAction.sqf
  A3A/addons/core/functions/Base/fn_postmortem.sqf
  A3A/addons/core/functions/Base/fn_postmortemLoop.sqf
  A3A/addons/core/functions/EventHandler/fn_enemyUnitKilledEH.sqf
  A3A/addons/core/functions/LTC/fn_lootToCrate.sqf
  A3A/addons/core/functions/REINF/fn_FIAinit.sqf
  A3A/addons/core/functions/REINF/fn_postmortem.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/patcom/functions/Civilian/fn_civilianInitEH.sqf
Labels: Enhancement, Ready for merge

#3256 Destroy Heli mission fixes
  A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
Labels: Bug, Enhancement, Ready for merge

#3271 RHS VDV Templates
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
Labels: Ready for merge, Templates

#3273 Prevent concurrent major attacks, and add a planning cost
  A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
  A3A/addons/core/functions/Base/fn_chooseAttack.sqf
  A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
  A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
  A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
Labels: Priority, Bug, Ready for merge, Balance

#3281 3CB Factions baseWeapon config fix
  A3A/addons/config_fixes/3CB/CfgWeapons.hpp
  A3A/addons/config_fixes/3CB/config.cpp
Labels: Bug, Merge pending, Ready for merge

#3283 Fix incorrect config array specifier for diveParams
  A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/SPE/config.cpp
Labels: Priority, Bug, Ready for merge

#3267 RHS Tanoan Liberation Army (TLA)
  A3A/addons/config_fixes/RHS/CfgVehicles.hpp
  A3A/addons/config_fixes/RHS/tla_rhs.hpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf
Labels: Ready for merge, Templates

#2800 SFP templates
  A3A/addons/config_fixes/CUP/CfgVehicles.hpp
  A3A/addons/config_fixes/CUP/config.cpp
  A3A/addons/config_fixes/CUP/sfp_air.hpp
  A3A/addons/core/Templates/AircraftLoadouts/SFP/config.cpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/SFP/SFP_AI_SWE.sqf
  A3A/addons/core/Templates/Templates/SFP/SFP_AI_SWE_early.sqf
  A3A/addons/core/Templates/Templates/SFP/SFP_AI_SWE_early_snow.sqf
  A3A/addons/core/Templates/Templates/SFP/SFP_AI_SWE_snow.sqf
  A3A/addons/core/Templates/Templates/SFP/SFP_Vehicle_Attributes.sqf
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/SFP.hpp
Labels: Ready for merge, Templates

#3166 Iron Front AiO templates
  A3A/addons/config_fixes/IFA/CfgVehicles.hpp
  A3A/addons/config_fixes/IFA/CfgWeapons.hpp
  A3A/addons/config_fixes/IFA/config.cpp
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Pictures/Flags/ifa_ak.paa
  A3A/addons/core/Pictures/Flags/ifa_allies.paa
  A3A/addons/core/Pictures/Flags/ifa_ffi.paa
  A3A/addons/core/Pictures/Flags/ifa_fr.paa
  A3A/addons/core/Pictures/Flags/ifa_pl.paa
  A3A/addons/core/Pictures/Flags/ifa_sov.paa
  A3A/addons/core/Pictures/Flags/ifa_weh.paa
  A3A/addons/core/Pictures/Markers/ifa_ak.paa
  A3A/addons/core/Pictures/Markers/ifa_allies.paa
  A3A/addons/core/Pictures/Markers/ifa_ffi.paa
  A3A/addons/core/Pictures/Markers/ifa_sov.paa
  A3A/addons/core/Pictures/Markers/ifa_weh.paa
  A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_CIV_Common.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_CIV_FR.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_CIV_PL.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_REB_AK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_REB_FFI.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_Vehicle_Attributes.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_itemType.sqf
  A3A/addons/logistics/Cargo/IFA.hpp
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/IFA.hpp
Labels: Ready for merge, Templates, Testing needed, RFC

#3260 Artillery marker improvements
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_artySupport.sqf
  A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
  A3A/addons/maps/MissionDescription/CfgNotificationsContents.hpp
Labels: Bug, Enhancement, Ready for merge, Testing needed

#3284 Temp membership logging
  A3A/addons/core/functions/OrgPlayers/fn_memberAdd.sqf
Labels: Enhancement, Ready for merge

#3285 Pre3.6 setup gui fixes
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/gui/dialogues/setupDialog.hpp
  A3A/addons/gui/functions/SetupGUI/fn_setupFactionsTab.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupLoadgameTab.sqf
Labels: Priority, Bug, Ready for merge

#3286 Fix inconsistent parameter bug with createAttackForceLand
  A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf
  A3A/addons/core/functions/Supports/fn_SUP_tankRoutine.sqf
Labels: Priority, Bug, Ready for merge

#3287 Prevent SAM supports being used by WW2 factions
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/functions/Supports/fn_initSupports.sqf
Labels: Priority, Bug, Ready for merge

#3214 Map Port of Pulau
  A3A/addons/maps/Antistasi_pulau.pulau/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_pulau.pulau/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_pulau.pulau/cba_settings.sqf
  A3A/addons/maps/Antistasi_pulau.pulau/description.ext
  A3A/addons/maps/Antistasi_pulau.pulau/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_pulau.pulau/initServer.sqf
  A3A/addons/maps/Antistasi_pulau.pulau/mapInfo.hpp
  A3A/addons/maps/Antistasi_pulau.pulau/mission.sqm
  A3A/addons/maps/Antistasi_pulau.pulau/navGrid.sqf
  A3A/addons/maps/Antistasi_pulau.pulau/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: Ready for merge, Map port

#3288 Fix mistype in DES_Vehicle
  A3A/addons/core/functions/Missions/fn_DES_Vehicle.sqf
Labels: Bug, Ready for merge

#3278 Livonia SF update
  A3A/addons/maps/Antistasi_Enoch.Enoch/mission.sqm
Labels: Change, Map Issue, Ready for merge

#3289 Update sfp_air.hpp with eventHandler inheritance
  A3A/addons/config_fixes/CUP/sfp_air.hpp
Labels: Bug, Ready for merge

#3290 Standardized IFA attribute location
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_Vehicle_Attributes.sqf
Labels: Refactor, Ready for merge

#3291 Fix buy vehicle menu function tagging
  A3A/addons/gui/dialogues/buyVehicleDialog.hpp
  A3A/addons/gui/functions/GUI/fn_buyVehicleDialog.sqf
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
Labels: Priority, Bug, Ready for merge

#3277 Updated CUP Garage Store
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
Labels: Enhancement, Ready for merge

#3292 Update Pulau mission.sqm, make blufor & indfor hostile
  A3A/addons/maps/Antistasi_pulau.pulau/mission.sqm
Labels: Priority, Bug, Map Issue, Ready for merge

#3282 Allow commanders to make custom HC squads
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/REINF/fn_convertToSquad.sqf
  A3A/addons/core/functions/REINF/fn_reinfPlayer.sqf
Labels: Enhancement, Ready for merge

#3293 Fix potential double-carry or double-drop errors under heavy script load
  A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
  A3A/addons/core/functions/UtilityItems/fn_dropItem.sqf
Labels: Bug, Ready for merge

#3294 Fetch current arsenal data before displaying the arsenal limits dialog
  A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf
Labels: Bug, Ready for merge

#3296 Donate money fixes
  A3A/addons/core/functions/OrgPlayers/fn_sendMoney.sqf
  A3A/addons/gui/functions/GUI/fn_donateTab.sqf
Labels: Bug, Ready for merge

#3297 Speculative init order fix
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: Bug, Ready for merge

#3295 Add explosiveSpecialist and UAVHacker traits to default commander slot
  A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
Labels: Change, Ready for merge

#3304 updated IFA radio backpacks, AK headwear, Parachutes
  A3A/addons/core/Templates/Templates/IFA/IFA_REB_AK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_REB_FFI.sqf
Labels: Ready for merge, Templates

#3300 Fix move asset not working on Petros
  A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
Labels: Priority, Bug, Ready for merge

#3301 3.6 Testing Fixes 1
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/AI/fn_artySupport.sqf
  A3A/addons/garage/Core/fn_sellVehGRG.sqf
  A3A/addons/garage/Dialogs.hpp
  A3A/addons/gui/functions/SetupGUI/fn_setupFactionsTab.sqf
Labels: Bug, Change, Enhancement, Ready for merge, Exploit

#3312 Fix for vehicle sell DS
  A3A/addons/garage/Core/fn_removeFromPool.sqf
  A3A/addons/garage/Core/fn_sellVehGRG.sqf
Labels: Bug, Ready for merge, Exploit

#3308 IFA Replaced police vehicle with something less civilian
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf
Labels: Ready for merge, Templates

#3315 Buff IFA mortars closer to mk6
  A3A/addons/config_fixes/IFA/CfgAmmo.hpp
  A3A/addons/config_fixes/IFA/CfgVehicles.hpp
  A3A/addons/config_fixes/IFA/CfgWeapons.hpp
  A3A/addons/config_fixes/IFA/config.cpp
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_REB_AK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_Reb_Vehicle_Attributes.sqf
Labels: Change, Ready for merge

#3317 Ifa aircraft price update & loadout tweak
  A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_Vehicle_Attributes.sqf
Labels: Ready for merge, Templates

#3318 Update RHS_AI_TLA military NVGs
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
Labels: Ready for merge, Templates

#3319 Adjust air support response for cheap planes
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_Vehicle_Attributes.sqf
  A3A/addons/core/functions/Supports/fn_SUP_ASF.sqf
  A3A/addons/core/functions/Supports/fn_SUP_SAM.sqf
  A3A/addons/core/functions/Supports/fn_initSupports.sqf
  A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
Labels: Ready for merge, Balance

#3325 Fixed script error in new BattleMenu.
  A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf
  A3A/addons/gui/functions/GUI/fn_commanderTab.sqf
Labels: Bug, Ready for merge

#3326 Added IFA-ACE-Compat detonators
  A3A/addons/core/Templates/Templates/IFA/IFA_REB_AK.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_REB_FFI.sqf
Labels: Ready for merge, Templates

#3321 Update RHS T50 loadouts
  A3A/addons/core/Templates/AircraftLoadouts/RHS/config.cpp
Labels: Ready for merge

#3322 Fix conflicting addon messages from aircraft loadout configs
  A3A/addons/core/Templates/AircraftLoadouts/3CB/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/CUP/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/RHS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/SFP/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/SPE/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/Tornado_AWS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/UNS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/VN/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/Vanilla/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/WS/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/config.cpp
  A3A/addons/core/script_component.hpp
Labels: Bug, Ready for merge

#3328 Pulau pics
  A3A/addons/maps/Antistasi_pulau.pulau/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_pulau.pulau/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_pulau.pulau/description.ext
  A3A/addons/maps/Antistasi_pulau.pulau/mission.sqm
  A3A/addons/maps/Stringtable.xml
Labels: Ready for merge
