Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2024-02, with the labels that each got.

#3123 Fix petros placement stringtable conversion bug
  A3A/addons/core/functions/Base/fn_placementselection.sqf
Labels: Priority, Bug, Ready for merge

#3110 Misc fixes batch 2
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
  A3A/addons/core/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
  A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
  A3A/addons/core/functions/OrgPlayers/fn_promotePlayer.sqf
  A3A/addons/core/functions/Supports/fn_showInterceptedSetupCall.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/garage/Core/fn_onLoad.sqf
  A3A/addons/garage/Core/fn_switchCategory.sqf
  A3A/addons/garage/Core/fn_toggleConfirmBttn.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
  A3A/addons/jeroen_arsenal/Stringtable.xml
  A3A/addons/patcom/functions/Patcom/fn_patrolArmStatics.sqf
Labels: Ready for merge

#3126 Fix cases where airspaceControl wouldn't execute
  A3A/addons/core/functions/Base/fn_airspaceControl.sqf
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Bug, Exploit

#3134 Add hint to help older players find the new construction system
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/dialogs.hpp
Labels: Change

#3131 readded debug functions second time
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Debug/fn_debugSpawnVics.sqf
  A3A/addons/core/functions/Debug/fn_spawnSelectedTemplateAI.sqf
Labels: Ready for merge

#3139 Cull large builder boxes because they don't work yet
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/init/fn_initUtilityItems.sqf
Labels: Change, Ready for merge

#3137 Vehicle discounts with no seaports
  A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
Labels: Added to changelog, Ready for merge

#3128 Make SLAT IFVs CBA-compatible
  A3A/addons/config_fixes/Vanilla/ifv.hpp
  A3A/addons/config_fixes/WS/ws_ifv.hpp
Labels: Bug, Review pending

#3135 preliminary 3.5.0 changelog
  changelog.rst
Labels: Review pending

#3143 Orbital strike already destroys the city naturally, don't do it twice
  A3A/addons/core/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
Labels: Bug

#3144 Fix missing localize in actionRevive
  A3A/addons/core/functions/Revive/fn_actionRevive.sqf
Labels: Bug

#3147 3.5.1 Undercover and Defend fixes
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
Labels: Priority, Bug, Ready for merge

#3150 Fix rogue var breaking vanilla LDF template
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
Labels: Priority, Bug, Ready for merge

#3151 Disable forced marker spawn in artySupport
  A3A/addons/core/functions/AI/fn_artySupport.sqf
Labels: Bug, Change, Ready for merge

#3155 3119 - kujari map fixes
  A3A/addons/maps/Antistasi_tem_kujari.tem_kujari/mission.sqm
Labels: Map Issue, Ready for merge

#3156 3.5.1 version and changelog
  A3A/addons/core/Includes/script_version.hpp
  README.md
  changelog.rst
Labels: Review pending

#3158 unstable into master for 3.5.1 update
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/functions/AI/fn_artySupport.sqf
  A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
  A3A/addons/maps/Antistasi_tem_kujari.tem_kujari/mission.sqm
  README.md
  changelog.rst
Labels: Ready for merge
