Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2024-01, with the labels that each got.

#3073 [Map Port] Colombia
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/NavGrid.sqf
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/cba_settings.sqf
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/description.ext
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/initServer.sqf
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/mapInfo.hpp
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/mission.sqm
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: Ready for merge

#3075 [Map Port] Weferlingen
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/NavGrid.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/cba_settings.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/description.ext
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/initServer.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mapInfo.hpp
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/onPlayerRespawn.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/NavGrid.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/cba_settings.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/description.ext
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/initServer.sqf
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mapInfo.hpp
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: Ready for merge

#3082 Vanilla LFF rebel faction
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
Labels: Ready for merge

#3098 Added: More builder boxes
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf
  A3A/addons/core/functions/init/fn_initUtilityItems.sqf
  A3A/addons/logistics/Cargo/Vanilla.hpp
Labels: Ready for merge

#3102 Miscellaneous fixes - Batch 1 (Tiny)
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_vehicleMarkers.sqf
  A3A/addons/core/functions/Base/fn_airspaceControl.sqf
  A3A/addons/core/functions/Base/fn_canMoveHQ.sqf
  A3A/addons/core/functions/Base/fn_createOutpostsFIA.sqf
  A3A/addons/core/functions/Base/fn_distance.sqf
  A3A/addons/core/functions/Base/fn_markerChange.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
  A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
  A3A/addons/core/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
  A3A/addons/core/functions/Intel/fn_selectIntel.sqf
  A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Supplies.sqf
  A3A/addons/core/functions/Missions/fn_REP_Antenna.sqf
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
  A3A/addons/core/functions/OrgPlayers/fn_promotePlayer.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_sentence_server.sqf
  A3A/addons/core/functions/REINF/fn_addBombRun.sqf
  A3A/addons/core/functions/REINF/fn_garrisonDialog.sqf
  A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
  A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
  A3A/addons/core/functions/Supports/fn_showInterceptedSupportCall.sqf
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
  A3A/addons/core/functions/init/fn_checkCampaignEnd.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/garage/Core/fn_getCatIndex.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/garage/Public/fn_addVehicle.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
Labels: Ready for merge

#3107 Weferlingen & Colombia fixes
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mapInfo.hpp
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mapInfo.hpp
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mission.sqm
Labels: Bug, Map Issue, Ready for merge

#3049 Vanilla Slat Caged APCs
  A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp
  A3A/addons/config_fixes/Vanilla/armor.hpp
  A3A/addons/config_fixes/Vanilla/ifv.hpp
  A3A/addons/config_fixes/WS/CfgVehicles.hpp
  A3A/addons/config_fixes/WS/ws_ifv.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
Labels: Ready for merge

#3022 Add CUP AFRF Desert Template
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Desert.sqf
Labels: Ready for merge, Templates

#3037 RHS CHDKZ - Officer loadout & 3CB uniform support
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
Labels: Ready for merge

#3081 3CB LSM rebel template.
  A3A/addons/config_fixes/3CB/CfgWeapons.hpp
  A3A/addons/config_fixes/3CB/config.cpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_LSM.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_Reb_Vehicle_Attributes.sqf
Labels: Ready for merge

#3108 Removed debug scope from a3a rhs t-72
  A3A/addons/config_fixes/RHS/chdkz_rhs.hpp
Labels: Ready for merge

#3109 Cleaned up vanilla/ifv.hpp & armour.hpp
  A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp
  A3A/addons/config_fixes/Vanilla/armor.hpp
  A3A/addons/config_fixes/Vanilla/ifv.hpp
Labels: Refactor, Ready for merge

#3091 Western Sahara Faction update
  A3A/addons/config_fixes/Vanilla/armor.hpp
  A3A/addons/config_fixes/WS/ws_ion.hpp
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
Labels: Ready for merge, Templates

#3116 Fix fallback code for militia lacking cargo trucks
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
Labels: Bug, Ready for merge

#3117 proper map pics and blurb fix
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_tem_kujari.tem_kujari/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Stringtable.xml
Labels: Map Issue, Ready for merge

#3114 Fix remote-controlling players despawning rebel garrisons & civs
  A3A/addons/core/functions/Base/fn_distance.sqf
Labels: Bug, Ready for merge
