Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2025-03, with the labels that each got.

#3504 removes dublicate container entry
  A3A/addons/gui/Stringtable.xml
Labels: Localisation, CI\CD

#3481 Fixed double Intel search Bug
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
Labels: Bug, Ready for merge

#3482 Ensure return value of HandleDisconnect is correct
  A3A/addons/core/functions/Base/fn_onPlayerDisconnect.sqf
Labels: Bug, Ready for merge

#3493 Add ACRE_BF888S
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, Templates

#3496 Improve paradrop placement
  A3A/addons/core/functions/AI/fn_paradrop.sqf
Labels: Change, Ready for merge

#3501 Implement loading of binocular magazine from arsenal
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
Labels: Enhancement, Ready for merge

#3507 Add some mapInfo features (banks, distances)
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_initZones.sqf
Labels: Enhancement, Ready for merge
