Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2025-04, with the labels that each got.

#3502 Improve dive bombing accuracy
  A3A/addons/config_fixes/IFA/CfgAmmo.hpp
  A3A/addons/config_fixes/SPE/CfgAmmo.hpp
  A3A/addons/config_fixes/SPE/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp
  A3A/addons/core/Templates/AircraftLoadouts/SPE/config.cpp
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
Labels: Change, Ready for merge

#3472 Fix up and re-enable UAV support for major attacks and HQ attacks
  A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
  A3A/addons/core/functions/Supports/fn_SUP_UAVRoutine.sqf
  A3A/addons/core/functions/Supports/fn_initSupports.sqf
  A3A/addons/core/functions/Supports/fn_requestArtillery.sqf
  A3A/addons/core/functions/Supports/fn_requestSupport.sqf
Labels: Bug, Enhancement, Ready for merge

#3508 Added appropriate names to SOG factions
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf
  A3A/addons/core/Templates/Templates/VN/VN_CIV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
Labels: Low priority, Ready for merge, Templates

#3483 Maps Napf and Napf Winter as playable
  A3A/addons/maps/Antistasi_Napf.Napf/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_Napf.Napf/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_Napf.Napf/cba_settings.sqf
  A3A/addons/maps/Antistasi_Napf.Napf/description.ext
  A3A/addons/maps/Antistasi_Napf.Napf/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_Napf.Napf/initServer.sqf
  A3A/addons/maps/Antistasi_Napf.Napf/mapInfo.hpp
  A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm
  A3A/addons/maps/Antistasi_Napf.Napf/navGrid.sqf
  A3A/addons/maps/Antistasi_Napf.Napf/onPlayerRespawn.sqf
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/cba_settings.sqf
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/description.ext
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/initServer.sqf
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mapInfo.hpp
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/navGrid.sqf
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: Ready for merge, Map port

#3378 Additional garage categories + dlc info
  A3A/addons/garage/CfgDefines.inc
  A3A/addons/garage/Core/fn_confirm.sqf
  A3A/addons/garage/Core/fn_getCatIndex.sqf
  A3A/addons/garage/Core/fn_onLoad.sqf
  A3A/addons/garage/Core/fn_switchCategory.sqf
  A3A/addons/garage/Core/fn_toggleConfirmBttn.sqf
  A3A/addons/garage/Dialogs.hpp
  A3A/addons/garage/Extras/fn_findMount.sqf
  A3A/addons/garage/Extras/fn_reloadExtras.sqf
  A3A/addons/garage/Extras/fn_reloadMounts.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/garage/Public/fn_loadSaveData.sqf
  A3A/addons/garage/Refuel/fn_getTotalFuelCargo.sqf
  A3A/addons/garage/Stringtable.xml
Labels: Enhancement, Ready for merge

#3522 Napf Hotfix
  A3A/addons/maps/Antistasi_Napf.Napf/mapInfo.hpp
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mapInfo.hpp
Labels: Priority, Bug, Ready for merge

#3516 Fix ACE Veh Repair breaking undercover
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
Labels: Bug, Ready for merge

#3517 Fix wrong laptop hack string
  A3A/addons/core/functions/Intel/fn_searchIntelOnLaptop.sqf
Labels: Bug, Ready for merge

#3514 Start with ACE plotting board
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
Labels: Enhancement, Ready for merge

#3454 Naval Support for Attacks
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_PMC.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/functions/AI/fn_enemyReturnToBase.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackForceMixed.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackForceSea.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3A/addons/core/functions/CREATE/fn_spawnVehicleAtMarker.sqf
  A3A/addons/core/functions/Pathfinding/fn_findSeaPath.sqf
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
Labels: Enhancement, Merge pending

#3440 Normalised and weighted vehicle spawns for airbases
  A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
Labels: Change, Ready for merge, Balance

#3512 RF & WS Faction Updates
  A3A/addons/config_fixes/RF/CfgVehicles.hpp
  A3A/addons/config_fixes/WS/CfgMarkers.hpp
  A3A/addons/config_fixes/WS/CfgWeapons.hpp
  A3A/addons/config_fixes/WS/config.cpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_PMC.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
Labels: Enhancement, Ready for merge, Templates

#3521 TFAR Signal distance scaling off Radio towers.
  A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf
Labels: Change, Ready for merge

#3524 Update garage count on load
  A3A/addons/garage/Core/fn_onLoad.sqf
Labels: Bug, Ready for merge

#3526 Rebel static sell pricing fix
  A3A/addons/core/functions/Base/fn_getVehicleSellPrice.sqf
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
  A3A/addons/garage/CfgDefines.inc
  A3A/addons/garage/Core/fn_confirm.sqf
  A3A/addons/garage/Core/fn_onLoad.sqf
  A3A/addons/garage/Core/fn_removeFromPool.sqf
  A3A/addons/garage/Core/fn_sellVehGRG.sqf
  A3A/addons/garage/Core/fn_switchCategory.sqf
  A3A/addons/garage/Core/fn_toggleConfirmBttn.sqf
  A3A/addons/garage/Extras/fn_findMount.sqf
  A3A/addons/garage/Extras/fn_reloadExtras.sqf
  A3A/addons/garage/Extras/fn_reloadMounts.sqf
  A3A/addons/garage/Public/fn_loadSaveData.sqf
  A3A/addons/garage/Refuel/fn_getTotalFuelCargo.sqf
Labels: Change, Ready for merge

#3527 Made SPE bridges indestructible
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/initServer.sqf
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/initServer.sqf
Labels: Bug, Change, Ready for merge

#3529 Vlash271 napf loading screen
  A3A/addons/maps/Antistasi_Napf.Napf/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_Napf.Napf/description.ext
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/description.ext
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/navGrid.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
Labels: Change, Enhancement, Merge pending, Map Issue

#3534 CAS speed limit imposed to minimise lawn darting
  A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
Labels: Bug, Ready for merge

#3532 Add explanatory tooltips to some setup UI new-game options
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/setupDialog.hpp
Labels: Enhancement, Ready for merge

#3531 RPT fixes: AFK div zero and double-construct cases
  A3A/addons/core/functions/Builder/fn_buildingComplete.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
  A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
  A3A/addons/gui/dialogues/controls.hpp
  A3A/addons/gui/dialogues/setupDialog.hpp
Labels: Bug, Ready for merge

#3519 3CB Grozovia Armed Forces
  A3A/addons/core/Templates/AircraftLoadouts/3CB/config.cpp
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_GAF.sqf
Labels: Enhancement, Ready for merge, Templates
