Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2025-05, with the labels that each got.

#3535 [Change] Update fn_createAIResources.sqf to have militia patrols at resources and factories
  A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
Labels: Change, Ready for merge

#3511 Gun shop
  A3A/addons/config_fixes/CUP/CfgAmmo.hpp
  A3A/addons/config_fixes/CUP/CfgWeapons.hpp
  A3A/addons/config_fixes/CUP/config.cpp
  A3A/addons/config_fixes/IFA/CfgWeapons.hpp
  A3A/addons/config_fixes/RHS/CfgWeapons.hpp
  A3A/addons/config_fixes/SPE/CfgWeapons.hpp
  A3A/addons/config_fixes/SPE/config.cpp
  A3A/addons/config_fixes/Vanilla/CfgAmmo.hpp
  A3A/addons/config_fixes/Vanilla/CfgWeapons.hpp
  A3A/addons/config_fixes/Vanilla/config.cpp
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_vehicleConvoyHeliTravel.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_configSort.sqf
  A3A/addons/core/functions/Ammunition/fn_setCargoItems.sqf
  A3A/addons/core/functions/Base/fn_findBasesForConvoy.sqf
  A3A/addons/core/functions/Base/fn_getVehiclesAirSupport.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_fillVehicleCrewCargo.sqf
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
  A3A/addons/core/functions/Missions/fn_GSMission.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
  A3A/addons/core/functions/Missions/fn_supplyDrop.sqf
  A3A/addons/gui/CfgFunctions.hpp
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/controls.hpp
  A3A/addons/gui/dialogues/dialogs.hpp
  A3A/addons/gui/dialogues/gunShop.hpp
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/dialogues/textures.inc
  A3A/addons/gui/dialogues/textures/filter_ca.paa
  A3A/addons/gui/dialogues/textures/list_ca.paa
  A3A/addons/gui/dialogues/textures/shopping_cart_ca.paa
  A3A/addons/gui/functions/gunShop/blackListedItems.json
  A3A/addons/gui/functions/gunShop/fn_addItemToBlackList.sqf
  A3A/addons/gui/functions/gunShop/fn_addToCart.sqf
  A3A/addons/gui/functions/gunShop/fn_blackListedItems.sqf
  A3A/addons/gui/functions/gunShop/fn_calculateItemPrice.sqf
  A3A/addons/gui/functions/gunShop/fn_checkOut.sqf
  A3A/addons/gui/functions/gunShop/fn_createFilters.sqf
  A3A/addons/gui/functions/gunShop/fn_createGunShopTab.sqf
  A3A/addons/gui/functions/gunShop/fn_fetchGunShopLists.sqf
  A3A/addons/gui/functions/gunShop/fn_gatherGunShopLists.sqf
  A3A/addons/gui/functions/gunShop/fn_gunShop.sqf
  A3A/addons/gui/functions/gunShop/fn_handleSearchEvents.sqf
  A3A/addons/gui/functions/gunShop/fn_lcgRand.sqf
  A3A/addons/gui/functions/gunShop/fn_updateCartNumber.sqf
  A3A/addons/gui/functions/gunShop/fn_updateCartPositions.sqf
  A3A/addons/gui/functions/gunShop/fn_updateFilters.sqf
  A3A/addons/gui/functions/gunShop/fn_updateTotalCost.sqf
Labels: Change, Enhancement, Ready for merge

#3523 Roadblocks & specop camps placement/management rewrite
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_deleteControls.sqf
  A3A/addons/core/functions/Base/fn_markerChange.sqf
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
  A3A/addons/core/functions/MinorSites/fn_addMinorSite.sqf
  A3A/addons/core/functions/MinorSites/fn_deleteMinorSite.sqf
  A3A/addons/core/functions/MinorSites/fn_deleteNearSites.sqf
  A3A/addons/core/functions/MinorSites/fn_generateCamps.sqf
  A3A/addons/core/functions/MinorSites/fn_generateRoadblockPairs.sqf
  A3A/addons/core/functions/MinorSites/fn_generateRoadblocks.sqf
  A3A/addons/core/functions/MinorSites/fn_initMinorSites.sqf
  A3A/addons/core/functions/MinorSites/fn_renderRoadblocks.sqf
  A3A/addons/core/functions/MinorSites/fn_selectRoadBetweenMarkersNav.sqf
  A3A/addons/core/functions/MinorSites/fn_selectRoadBetweenMarkersRand.sqf
  A3A/addons/core/functions/MinorSites/fn_updateMinorSites.sqf
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
  A3A/addons/core/functions/Pathfinding/fn_findPathSimple.sqf
  A3A/addons/core/functions/Save/fn_deleteSave.sqf
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/init/fn_generateRoadblock.sqf
  A3A/addons/core/functions/init/fn_initBases.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_initZones.sqf
  A3A/addons/core/functions/init/fn_prepareMarkerArrays.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/maps/Antistasi_Altis.Altis/mission.sqm
  A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
  A3A/addons/maps/Antistasi_chernarus.chernarus/mission.sqm
  A3A/addons/maps/Antistasi_chernarus_summer.chernarus_summer/mission.sqm
  A3A/addons/maps/Antistasi_chernarus_winter.chernarus_winter/mission.sqm
  A3A/addons/maps/Antistasi_regero.regero/mission.sqm
Labels: Enhancement, Ready for merge

#3536 Explosive placement logging
  A3A/addons/core/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
Labels: Enhancement, Ready for merge

#3538 Disable dive bomb test debug spam
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
Labels: Change, Ready for merge

#3537 New UI: Context menu fix
  A3A/addons/gui/functions/GUI/fn_playerTab.sqf
Labels: Bug, Ready for merge

#3539 Fix some Petros death handling
  A3A/addons/core/functions/AI/fn_airbomb.sqf
  A3A/addons/core/functions/AI/fn_napalm.sqf
  A3A/addons/core/functions/AI/fn_napalmDamage.sqf
  A3A/addons/core/functions/Base/fn_initPetros.sqf
Labels: Bug, Ready for merge

#3540 Added MG cars and engineer squads to new squad purchase UI
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/dialogues/recruitSquadDialog.hpp
  A3A/addons/gui/dialogues/textures.inc
  A3A/addons/gui/dialogues/textures/icon_eng_squad.paa
  A3A/addons/gui/dialogues/textures/icon_mg_car.paa
  A3A/addons/gui/functions/GUI/fn_recruitSquadDialog.sqf
Labels: Bug, Enhancement, Ready for merge

#3444 Update fn_initVarServer.sqf with more helicopters to fast rope from
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Change, Ready for merge

#3543 Fix altis SQM control count
  A3A/addons/maps/Antistasi_Altis.Altis/mission.sqm
Labels: Bug, Ready for merge

#3544 Update garage box to not use vehicle ammo boxes
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/mission.sqm
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/mission.sqm
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mission.sqm
  A3A/addons/maps/Antistasi_regero.regero/mission.sqm
  A3A/addons/maps/Antistasi_tem_kujari.tem_kujari/mission.sqm
Labels: Priority, Ready for merge

#3553 Fix ancient specops bug with missing UAVs
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
Labels: Bug, Ready for merge

#3551 Playtesting UI fixes 1
  A3A/addons/core/functions/Dialogs/fn_canFastTravel.sqf
  A3A/addons/core/functions/OrgPlayers/fn_theBossToggleEligibility.sqf
  A3A/addons/core/keybinds/fn_keyActions.sqf
  A3A/addons/gui/dialogues/mainDialog.hpp
  A3A/addons/gui/functions/GUI/fn_commanderTab.sqf
  A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
  A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf
  A3A/addons/gui/functions/GUI/fn_playerTab.sqf
  A3A/addons/gui/functions/GUI/fn_requestMissionDialog.sqf
Labels: Bug, Ready for merge

#3550 Soften postmortem cleanup rules
  A3A/addons/core/functions/Base/fn_postmortemLoop.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Change, Ready for merge

#3549 Regero testing fixes
  A3A/addons/maps/Antistasi_regero.regero/mission.sqm
Labels: Bug, Ready for merge

#3545 Update 3CB_AI_GAF.sqf with militia marksmen rifle fix
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_GAF.sqf
Labels: Bug, Ready for merge

#3570 Arty rangetable in start gear
  A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
Labels: Change, Ready for merge

#3569 Playtesting UI fixes 2
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf
  A3A/addons/gui/functions/GUI/fn_commanderTab.sqf
Labels: Bug, Change, Ready for merge

#3566 Final baseWeapon fix
  A3A/addons/config_fixes/3CB/CfgWeapons.hpp
  A3A/addons/config_fixes/Aegis/CfgWeapons.hpp
  A3A/addons/config_fixes/Vanilla/CfgWeapons.hpp
  A3A/addons/config_fixes/WS/CfgWeapons.hpp
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_addItem.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
Labels: Bug, Ready for merge

#3563 Optimized mapDrawOutpostsEH
  A3A/addons/gui/functions/GUI/fn_mapDrawHcGroupsEH.sqf
  A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf
Labels: Performance, Ready for merge

#3562 Fix bank mission truck proximity checks for arbitrary bank buildings
  A3A/addons/core/functions/Missions/fn_LOG_Bank.sqf
Labels: Bug, Ready for merge

#3561 Fix massive server stall on garage refuel attempt
  A3A/addons/garage/CfgDefines.inc
  A3A/addons/garage/Refuel/fn_reciveStateUpdate.sqf
  A3A/addons/garage/Refuel/fn_refuelVehicleFromSources.sqf
Labels: Priority, Bug, Ready for merge

#3560 Fix case where gun shop mission may be started without a city
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
Labels: Bug, Ready for merge

#3559 Napf (and Napf Winter) play test changes
  A3A/addons/maps/Antistasi_Napf.Napf/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_Napf.Napf/initServer.sqf
  A3A/addons/maps/Antistasi_Napf.Napf/mapInfo.hpp
  A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/initServer.sqf
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mapInfo.hpp
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
Labels: Bug, Change, Ready for merge

#3554 Fix towns on Napf and Napf Winter
  A3A/addons/config_fixes/Napf/config.cpp
  A3A/addons/maps/Antistasi_Napf.Napf/mapInfo.hpp
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mapInfo.hpp
Labels: Bug, Ready for merge

#3573 Fix controlsX remnant in HQ position setup dialog
  A3A/addons/gui/functions/SetupGUI/fn_setupHQPosDialog.sqf
Labels: Bug, Ready for merge

#3580 Worst hack ever written
  A3A/addons/core/keybinds/fn_keyActions.sqf
  A3A/addons/gui/dialogues/mainDialog.hpp
Labels: Bug, Ready for merge, Arma bug

#3574 Clean up orphaned towing helpers to prevent log spam
  A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp
  A3A/addons/core/Scripts/fn_advancedTowingInit.sqf
Labels: Change, Ready for merge

#3579 Reduce punishment chance after successful punishment defence
  A3A/addons/core/functions/Base/fn_chooseAttack.sqf
  A3A/addons/core/functions/Base/fn_findAttackTargets.sqf
  A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: Ready for merge, Balance

#3571 Update findBasesForConvoy to use new navgrid-based logic
  A3A/addons/core/functions/Base/fn_findBasesForConvoy.sqf
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
Labels: Enhancement, Performance, Refactor, Ready for merge

#3572 Fix misplaced camp on Napf plus an incorrect log line
  A3A/addons/core/functions/MinorSites/fn_generateCamps.sqf
  A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
Labels: Bug, Ready for merge

#3575 Garage Category Culling 1
  A3A/addons/garage/CfgDefines.inc
  A3A/addons/garage/Core/fn_getCatIndex.sqf
  A3A/addons/garage/Core/fn_switchCategory.sqf
  A3A/addons/garage/Dialogs.hpp
  A3A/addons/garage/Public/fn_loadSaveData.sqf
  A3A/addons/garage/Stringtable.xml
Labels: Enhancement, Ready for merge

#3581 Playtesting UI Fixes 3
  A3A/addons/core/keybinds/fn_keyActions.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/functions/GUI/fn_commanderTab.sqf
  A3A/addons/gui/functions/GUI/fn_hqDialog.sqf
  A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
Labels: Bug, Change, Ready for merge

#3582 Napf town edits, Seap_5_Mortar fix, capitalisation of Napf winter's climate
  A3A/addons/config_fixes/Napf/config.cpp
  A3A/addons/maps/Antistasi_Napf.Napf/mapInfo.hpp
  A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mapInfo.hpp
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
Labels: Change, Ready for merge

#3585 Reduce Osprey speed before combat landing
  A3A/addons/core/functions/AI/fn_combatLanding.sqf
Labels: Change, Ready for merge

#3584 Various gunshop/supply drop edge case fixes:
  A3A/addons/core/functions/Ammunition/fn_setCargoItems.sqf
  A3A/addons/core/functions/Missions/fn_GSMission.sqf
  A3A/addons/core/functions/Missions/fn_supplyDrop.sqf
Labels: Bug, Ready for merge

#3586 Not the final baseWeapon fix
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_addItem.sqf
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
Labels: Bug, Ready for merge

#3587 Fix bug with garage category defaulting to helicopter
  A3A/addons/garage/Core/fn_getCatIndex.sqf
  A3A/addons/garage/Public/fn_loadSaveData.sqf
Labels: Priority, Bug, Ready for merge

#3588 RHIB replacing assault boat, all templates
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arctic.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Tropical.sqf
  A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_US.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_BAF_Tropical.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_Iran.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_Russia.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_US_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_US_Temperate.sqf
  A3A/addons/core/Templates/Templates/BWA3/BWA3_AI_BW_Arid.sqf
  A3A/addons/core/Templates/Templates/BWA3/BWA3_AI_BW_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_HIL.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
  A3A/addons/core/Templates/Templates/CWR/CWR_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Arid.sqf
  A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
  A3A/addons/core/Templates/Templates/SPE/SPE_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE/SPE_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPEX/SPEX_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPEX/SPEX_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
Labels: Ready for merge, Balance

#3592 Remove invisible map icon usage with 360 angle trick
  A3A/addons/gui/functions/GUI/fn_mapDrawHcGroupsEH.sqf
  A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf
Labels: Performance, Ready for merge

#3595 Fix RHS M252 appearing in armour category in garage
  A3A/addons/garage/Core/fn_getCatIndex.sqf
Labels: Bug, Ready for merge

#3596 Preload map icons in attempt to workaround Arma crash bug
  A3A/addons/gui/dialogues/mainDialog.hpp
Labels: Ready for merge, Arma bug

#3589 Airbase heli balancing
  A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
Labels: Change, Technically ready for merge

#3598 Origins panel slight UI tweaks
  A3A/addons/garage/CfgDefines.inc
  A3A/addons/garage/Dialogs.hpp
Labels: Bug, Ready for merge

#3599 Minor garrison fixes
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf
Labels: Bug, Enhancement, Ready for merge

#3600 Change UI setting to a per-user toggle in game options
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/dialogs.hpp
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: Enhancement, Ready for merge, RFC

#3605 3.9.0 Unstable -> Master Hotfixes
  A3A/addons/core/Templates/Templates.hpp
Labels: Priority, Bug, Ready for merge
