Repository official-antistasi-community/A3-Antistasi, pull requests merged in 2025-07, with the labels that each got.

#3593 Improve loadout randomization
  A3A/addons/core/functions/CREATE/fn_createUnit.sqf
  A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
  A3A/addons/core/functions/Templates/fn_loadFaction.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
Labels: Enhancement, Ready for merge

#3608 Airstrike/Napalm Nerfs
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_airbomb.sqf
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/REINF/fn_NATObomb.sqf
  A3A/addons/core/functions/REINF/fn_addBombRun.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/functions/GUI/fn_airSupportTab.sqf
Labels: Change, Enhancement, Ready for merge

#3609 DES Heli mission probability fixes
  A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
Labels: Change, Ready for merge

#3614 Unit RC AI Disable
  A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf
  A3A/addons/core/functions/REINF/fn_controlunit.sqf
Labels: Bug, Ready for merge

#3631 Playtesting UI Fixes 4
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/Dialogs/fn_canSkipTime.sqf
  A3A/addons/gui/functions/GUI/fn_commanderTab.sqf
  A3A/addons/gui/functions/GUI/fn_fastTravelTab.sqf
  A3A/addons/gui/functions/GUI/fn_playerTab.sqf
  A3A/addons/gui/functions/GUI/fn_recruitDialog.sqf
Labels: Bug, Ready for merge

#3626 Ammo cargo tracking
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/UtilityItems/fn_remainingAmmo.sqf
  A3A/addons/core/functions/init/fn_initUtilityItems.sqf
  A3A/addons/garage/CfgFunctions.hpp
  A3A/addons/garage/Public/fn_addVehicle.sqf
  A3A/addons/garage/StatePreservation/fn_getAmmoCargo.sqf
  A3A/addons/garage/StatePreservation/fn_getState.sqf
  A3A/addons/garage/StatePreservation/fn_setAmmoCargo.sqf
  A3A/addons/garage/StatePreservation/fn_setState.sqf
  A3A/addons/garage/Stringtable.xml
Labels: Enhancement, Ready for merge

#3648 Ammo transfer + Airsupport fixes
  A3A/addons/core/functions/Ammunition/fn_ammunitionTransfer.sqf
  A3A/addons/core/functions/UtilityItems/fn_remainingAmmo.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
Labels: Bug, Ready for merge

#3647 Radio key saving
  A3A/addons/core/functions/Intel/fn_selectIntel.sqf
  A3A/addons/core/functions/Save/fn_deleteSave.sqf
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/Supports/fn_useRadioKey.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
Labels: Enhancement, Ready for merge
